### ISSUE TITLE
Auto HIdding

### ISSUE THREAD

**Issue by miroslawWasylik** [Ross-Patterson/Portals-Desktop-Organization#1]
HI, one feature which is not available is auto hidding when cursor is on it (focused). This is very helpful.

**Comment by miroslawWasylik** [comment]
And I mean when cursor is on panel all workspace is showing and then cursor is out workspace is hidding (minimalized) - see on Fences software

**Comment by Ross-Patterson** [comment]
@miroslawWasylik this is already available in the settings, look for the checkbox "Auto-minimize when focus is lost".

**Comment by Ross-Patterson** [comment]
Ahh you mean that hovering over the titlebar should expand the Portal, then when hover is lost minimize it again.

I have tried this in the past but it behaved quite erratically, so i settled for using Focus rather than hover, i will keep trying to make this work.

**Comment by miroslawWasylik** [comment]
Yeah exacly that's what I mean. It could be better than focus.

wt., 29 mar 2022 o 19:59 Ross Patterson ***@***.***>
napisał(a):

**Comment by Ross-Patterson** [comment]
An experimental version of this is now available in v2.1.0.4.

Its not perfect but should get you by.
