### ISSUE TITLE
Icon caching

### ISSUE THREAD

**Issue by agamotto** [Ross-Patterson/Portals-Desktop-Organization#10]
Ross wonderful job with Portals, used Fences before and was way slower/clunkier. So this is like a breath of fresh air on my desktop.

If I could make a suggestion for improvement it would be some kind of icon caching mechanism to make initial loading faster. I have a portal/folder with some 90 items and it takes some seconds to load when I first login.

**Comment by Ross-Patterson** [comment]
Have you tried the "Use Alternate Icon Retrieval Method" option? it may be faster.

I will look into other options i.e icon caching.

**Comment by agamotto** [comment]
Yes I tried the alternative method but didn't find much difference in terms of speed.

Many thanks for looking into my request.

**Comment by Ross-Patterson** [comment]
in v3.0.0 portals will load with temporary icons until all of the icons are pulled.
