### ISSUE TITLE
You cannot launch Steam from a shortcut inside a Portal

### ISSUE THREAD

**Issue by NyaomiDEV** [Ross-Patterson/Portals-Desktop-Organization#100]
**Describe the bug**
Literally as the title says. The executable gets launched, but after the "updater wrapper" step, Steam says that its UI component is broken, and it will crash.

**To Reproduce**
1. Put the Steam shortcut inside a portal
2. Click on it
3. Wait for Steam to launch
4. See the error message box

**Expected behavior**
Well.. as with any links, they should launch just fine?

**Screenshots**
Not really applicable to this scenario I guess? It's just a messagebox.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 2.1.0.6

**Additional context**
Not applicable.

**Comment by Ross-Patterson** [comment]
Are you sure this isnt an issue with Steam itself?

**Comment by NyaomiDEV** [comment]
I am pretty sure it's not. It launches just fine if I open the same shortcut inside Explorer, or anywhere else. Competitor software launches it fine, too.

**Comment by Ross-Patterson** [comment]
Try in v3.0.0, I can launch Steam games just fine
