### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by Laoxo** [Ross-Patterson/Portals-Desktop-Organization#104]
Portals keeps crashing on startup. And whenever I try to reopen it still shows this crash. Even tried reinstalling and that didn't work.

[portals_crashlog_2023-02-27_14-18-27_0670494.log](https://github.com/Ross-Patterson/Portals-Desktop-Organization/files/10843254/portals_crashlog_2023-02-27_14-18-27_0670494.log)

![Portals_OUcHZFSqGs](https://user-images.githubusercontent.com/114558322/221661800-a985d0b1-c54c-4a3b-9ad9-2937da11d7f6.jpg)

**Comment by Ross-Patterson** [comment]
Try v3.0.0
