### ISSUE TITLE
Feature Request: Auto-align portals being moved to the borders of the other existing ones

### ISSUE THREAD

**Issue by Max1234-Ita** [Ross-Patterson/Portals-Desktop-Organization#105]
**Is your feature request related to a problem? Please describe.**
I like to keep my portal well aligned at the top of the desktop and stacked in columns; unfortunately I'm forced to do manually the pixel-alignment every time i move or modify a portal.

![image](https://user-images.githubusercontent.com/15315381/222409780-c117a3b1-9c76-423f-960a-f87b419e4267.png)

So I think it would be nice if the portals could automatically align to others when they are close enough  (either horizontal or vertical borders):

**Describe the solution you'd like**
Moving a portal on the desktop, as soon as the distance between one of its borders and the corresponding border of another existing portal is lower than a predefined threshold, the form being moved should auto-align to the other.

The image below shows the example of top border alignment, but that should apply also to bottom and side borders (for column alignment)

![image](https://user-images.githubusercontent.com/15315381/222410392-6f1eefc0-7b8f-45e9-aa1a-00de6e261b55.png)

**Describe alternatives you've considered**
Manual alignment of the portals (quite uncomfortable)

**Additional context**
--

**Comment by Ross-Patterson** [comment]
This is now available in v3.0.2.0 via the beta channel in the settings.

Note I have added it as a Preview Feature.
