### ISSUE TITLE
Import / Export

### ISSUE THREAD

**Issue by f3n3k** [Ross-Patterson/Portals-Desktop-Organization#106]
Hello

Is-it possible to have a export/import option please?
Or if you have a solution after a windows reinstall to load my previous setting on portals

Thanks a lot

Cya

**Comment by Ross-Patterson** [comment]
Hi, this isn't on the UI, but you can take a backup of C:\Users\<username>\AppData\Local\Portals

I can add this to the UI.

**Comment by f3n3k** [comment]
hooo cool, so if I understand correctly, if I take this folder and put it in my new installation, I find on my new desktop, my old portals and my icons in it?

**Comment by Ross-Patterson** [comment]
Yes - the icons are pulled fresh every time based on the contents of the folders. But yes the Portals with all of the customisations will load back in.

**Comment by f3n3k** [comment]
Awesome !! Thank you again for your help and your quick response!!
