### ISSUE TITLE
always show window's context menu when right clicking

### ISSUE THREAD

**Issue by MRGOOSE81** [Ross-Patterson/Portals-Desktop-Organization#109]
**Is your feature request related to a problem? Please describe.**
not really, but many people prefer windows's context menu over portal's

**Describe the solution you'd like**
there should be an option is settings that disables portal's context menu when right clicking and uses window's context menu instead

**Describe alternatives you've considered**
using other software? no, but i just came to portals after using Stardock Fences, i like portals but i just dont like portal's context menu

**Additional context**
nothing.

**Comment by Ross-Patterson** [comment]
Duplicate of #89
