### ISSUE TITLE
Portals move randomly when plugging/unplugging external screens to my laptop.

### ISSUE THREAD

**Issue by kosheiry** [Ross-Patterson/Portals-Desktop-Organization#110]
**Describe the bug**

When I assign the location of portals on my laptop desktop, while having my 2 external screens plugged in, then I later unplug the screens and plug them again, portals randomly change locations. 

**To Reproduce**

1. assign a location to portals on laptop screen. Make sure 1 or 2 external screens are connected.
2. unplug/disconnect the external screens.
3. Shut down the PC or put it to sleep.
4. (step 2 and 3 are interchangeable)
5. reconnect/plug the external screens.
6. Turn on the laptop.

**Expected behavior**

Portals being located where they are supposed to be.

**Screenshots**

**Desktop (please complete the following information):**

Windows 11

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ross-Patterson** [comment]
I'd suggest, using v3.0.0, save each of your display setups, then assign a layout to each one. Use the "Auto-Apply" option to make portals auto-apply the layout when it detects a display change.
