### ISSUE TITLE
Feature Request: Add the feature to modify path to a portal directory

### ISSUE THREAD

**Issue by Shashank03200** [Ross-Patterson/Portals-Desktop-Organization#111]
- I'm always frustrated when I have to rename a portal folder or organize nested folders.
- I would like to have a feature to modify the existing path to a portal directory without modifying its position, layout, other options.

Thanks

**Comment by Ross-Patterson** [comment]
This is now available in the beta channel v3.0.1.0, switch to it in the settings:
![image](https://user-images.githubusercontent.com/66630787/234682352-d05be0d3-1399-43e8-b774-e7bff9bccb1d.png)

**Comment by Ross-Patterson** [comment]
this is now released to prod channel, so closing this issue.
