### ISSUE TITLE
Feature Request: Ability to cycle through files inside a Portal by pressing a letter key

### ISSUE THREAD

**Issue by TBat** [Ross-Patterson/Portals-Desktop-Organization#113]
**Please describe.**
Portals are nice for visual organization, but when I have a ton of files/apps per Portal, finding a file whose name I know becomes more tedious.

**Describe the solution you'd like**
I'd like the ability to press a letter key to cycle through files starting with that letter inside a Portal. This is already a feature of the Desktop and Windows Explorer.
E.g. if a portal has the dozens of files named `"Aardvark.jpg", "Anteater.jpg", "Armadillo.jpg", ..., "Zebra.jpg"` and I know there's a `"Monkey.jpg"` in there, I want to press "M" a few times to cycle through the files starting with "M" so I can find it much faster.

**Describe alternatives you've considered**
The only alternative I currently use is the "Everything" search app, which currently supersedes Portals' usefulness for finding specific files even on the Desktop.

**Additional context**
Cycling through files should also work while the user isn't in the scope of a particular Portal, e.g. after clicking on a blank space in the desktop. In this case it should probably start with the Portal in the top-left, continuing to the right until it reaches the bottom-right Portal. It might be best if the cycling direction was an option in the Portal Settings.

**Comment by Ross-Patterson** [comment]
This has been deployed in the latest update.
