### ISSUE TITLE
Portals stuck during load - Never appears nor does the taskbar icon

### ISSUE THREAD

**Issue by wakitcha** [Ross-Patterson/Portals-Desktop-Organization#115]
**Describe the bug**
When launched, Portals gets stuck during loading.  The Portals never appear and there is no other sign that it is running, no taskbar icon, other then the task in Task Manager.

**To Reproduce**
1. Open Portals.  
2. Note that the Portals have not appeared.  

**Expected behavior**
The Portals appear and the taskbar icon is present and functional.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Portals on this computer has worked previously.  We have taken clones of the computer at various points in the past and on those copies Portals is still working.

**Comment by Ross-Patterson** [comment]
Try upgrading to v3.0.0
