### ISSUE TITLE
Feature Request :  Latest opened Portal to auto bring to front.

### ISSUE THREAD

**Issue by BigJinge** [Ross-Patterson/Portals-Desktop-Organization#116]
Scenario :

I don't keep portals open on the screen all the time. When I want to open up an app, I open the portal.
Currently, depending where the portal is listed in Window Order, if you open a portal, you'll see other portal title bars, et al (even if Content Area Transparency is set to full opaque).  

All you want to see is your selected portal, brought to the front by selection of it, overlaying everything else. 

Proposed fix :
Add an checkbox / tick option in Portals / Settings / Portal Behavior that says "Allow Selected Portal to always be on top"

Thanks

**Comment by Ross-Patterson** [comment]
This has been deployed in the latest update.
