### ISSUE TITLE
Use Image As Background, unable to toggle

### ISSUE THREAD

**Issue by frogiraffe** [Ross-Patterson/Portals-Desktop-Organization#117]
**Describe the bug**
With the new update, when u use, "use image as background" option for header background you cant click on header and toggle the portal.

**To Reproduce**
1. Go to Customize
2. Click on "use image as background" for background color
3. try clicking on header
4. it doesnt toggle

**Expected behavior**
it should toggle

**Desktop (please complete the following information):**
 - OS: Win11
 - Software Version 3.0.0.4

**Comment by Ross-Patterson** [comment]
This is because you haven't chosen an image yet. So the header is fully transparent and click-through. Choose an image and it will work:
![PortalsImageBg](https://user-images.githubusercontent.com/66630787/233687766-bb9209d2-42ce-40b4-92d0-848406c28585.gif)
