### ISSUE TITLE
Latest Portals update wiped out my Portals setup.  I don't know where the settings are stored.  Was I supposed to manually export the settings before updating the program?  I wish the update prompt had warned my that this would happen.

### ISSUE THREAD

**Issue by archtrtd1** [Ross-Patterson/Portals-Desktop-Organization#118]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by archtrtd1** [comment]
I don't know where the settings are stored.  Was I supposed to manually export the settings before updating the program?  I wish the update prompt had warned my that this would happen.

**Comment by DexeconGithub** [comment]
same thing here. the folders still exist, but when i try to load a layout, it says "portal already exists"

**Comment by Dark-Peace** [comment]
It only wiped half of the customisation for me. I'm not gonna complain because I've been able to see the new customisation features, which I believe were added now.

**Comment by Ross-Patterson** [comment]
I'm sorry to hear this - this was a full rebuild and I tried my best to ensure the old settings would be picked up. But there have obviously been a few people where this didn't work properly.

Are the portals listed in the table on the main settings window?

**Comment by archtrtd1** [comment]
My main settings window was completely empty and I could not get portals to see my Portals folders location.  I just started up my computer and now my portals are showing up on my desktop. Some of the settings (font changes) didn't carry through, but at least I have them now.  I should have restarted my computer after the update.  I apologize for the inconvenience.  Thank you for your help and wonderful program!
