### ISSUE TITLE
Cannot drag icons into portals, dragging from portals works fine.

### ISSUE THREAD

**Issue by notloogi** [Ross-Patterson/Portals-Desktop-Organization#120]
You cannot drag and drop icons from the desktop into the portals, only from the portal to desktop. I have to show hidden files and put the icons into the folder itself. Dragging icons from inside the portal works just fine. Not sure if intended or not. 

**To Reproduce**
Just try to drag icons into the portal. 

**Expected behavior**
I expect to be able to drag icons into/out of the portal but only the latter works. Maybe I'm just being thick here lol

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2 19044.2846

**Comment by Ross-Patterson** [comment]
I am not able to replicate this unfortunately:
![PortalsDragDrop](https://user-images.githubusercontent.com/66630787/233686362-3847d6e6-b3b7-4e6a-a41d-3d0910e9c31f.gif)

Have you tried a simple restart?

**Comment by Dark-Peace** [comment]
I had the same bug and restarting did fix it!

**Comment by notloogi** [comment]
Has persisted through application restarts and system restarts. Now beginning to think its something with my computer...
![portal drag-drop](https://user-images.githubusercontent.com/68039638/233688302-ee7e5a91-dbc1-44a6-a97b-59c44a1f253b.gif)

**Comment by notloogi** [comment]
I should note this was happening before the update as well, at least a few weeks

**Great product otherwise!**

**Comment by Ross-Patterson** [comment]
Very strange... could it be a permissions issue?

Where are your portal folders stored at?

**Comment by notloogi** [comment]
hidden portal folders are stored on the desktop, account is admin

**Comment by Ross-Patterson** [comment]
Hmm... It could be that the files are in your Public desktop, instead of the Desktop associated with your userprofile maybe:
![image](https://user-images.githubusercontent.com/66630787/233693379-52831245-4247-489b-a649-b36e39d6701c.png)

**Comment by notloogi** [comment]
The only thing in my public desktop is the Portals shortcut, portal folders are in userprofile desktop folder. Will try a fresh install of Portals and will get back to you

**Comment by notloogi** [comment]
Fresh install seems to have fixed the problem. Not sure what it was exactly. Thank you for your help.
