### ISSUE TITLE
Blurred icons and cropped icons on the top row

### ISSUE THREAD

**Issue by Dark-Peace** [Ross-Patterson/Portals-Desktop-Organization#121]
**Describe the bug**
After the new update, all the icons inside the portals became blurred, which is not visually pleasing. Furthermore, the icons on the top row lack some pixels which is even less visually pleasing.
I apologize if I missed a setting for that.

**To Reproduce**
1. Get the last update.

**Expected behavior**
I wish to have icons just as they appear on my desktop and not cropped in the portals.

**Screenshots**
Screenshot :
![image](https://user-images.githubusercontent.com/74102789/233689568-0b1833db-e64d-48df-92be-fc7f7d97355b.png)
You can see the difference between in and out a portal. And the top is cropped (yes it's scrolled all the way up)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Vivaldi
 - Version : 3.0.0.4

**Comment by Ross-Patterson** [comment]
Try going into your settings and setting the icon size to Medium:
![image](https://user-images.githubusercontent.com/66630787/233690501-684f1410-442c-4258-ba22-dd3824131168.png)

**Comment by Dark-Peace** [comment]
It kinda works ? Although it just feels like higher resolution blur.
![image](https://user-images.githubusercontent.com/74102789/233691351-29df6174-438b-4069-b2bb-8fc10ea6e9e0.png)
But I need small icons, I have to many icons for them to be medium. I think it was fine before the update.

**Comment by Dark-Peace** [comment]
And what about the cropping ?

**Comment by Ross-Patterson** [comment]
Check the settings for item size and item margin, maybe they are in the negative?
![image](https://user-images.githubusercontent.com/66630787/233691905-cf8c7d50-eac1-4ddd-a7eb-713fe965ff5c.png)

**Comment by Ross-Patterson** [comment]
I am unsure what is causing the blur for you - I am not seeing any blurry icons on my side.

Is this a newly created Portal? Could you try close it and re-create it?

**Comment by Ross-Patterson** [comment]
Can you try re installing, downloading it from here:
https://portals-app.com/

**Comment by Dark-Peace** [comment]
Yeah, it's just reinstalling the version I already have. It's still blurry

**Comment by Dark-Peace** [comment]
Btw I confirm that going back to the previous version fixes it

**Comment by Ross-Patterson** [comment]
Can you do this for me:

1. Clear the contents of C:\Users\<username>\AppData\Local\Portals  (take a backup if you want)
2. Start v3.0.0 and re-create the problem in 1 Portal with some dummy files (Word, PPT, Excel, Image files - not shortcuts to installed apps)
3. Send me the:
    - new contents of C:\Users\<username>\AppData\Local\Portals
    - Portal folder and its contents.

I will try to re-create the exact situation on my machine.

**Comment by Dark-Peace** [comment]
@Ross-Patterson 
The folder :
[Dummy.zip](https://github.com/Ross-Patterson/Portals-Desktop-Organization/files/11301594/Dummy.zip)
The AppData content : 
[Portals.zip](https://github.com/Ross-Patterson/Portals-Desktop-Organization/files/11301596/Portals.zip)

**Comment by Ross-Patterson** [comment]
Thanks,
This is what it looks like on my side:
![image](https://user-images.githubusercontent.com/66630787/233792928-a2caf1a0-b059-47cd-8c85-e5388454bce3.png)

I assume its not like that for you?

Do you have any special display settings set i.e. 125% scaling?

**Comment by Dark-Peace** [comment]
Yeah I should've given you the screenshot on my end too. 
![image](https://user-images.githubusercontent.com/74102789/233794633-f334712a-a2c6-4d09-b24b-ffb493aa49f7.png)
And here's the icons on the desktop, they're smaller but feel less blurry than the ones in the Portal
![image](https://user-images.githubusercontent.com/74102789/233794739-703be66d-639c-4011-bb27-c81cad1e83cc.png)

Yes it's 1920*1080 125% scaling, but that's the recommended settings

**Comment by Ross-Patterson** [comment]
Ok, I know the issue, its the 125% scaling.

Will fix it in the next release.

Current (at 125% scaling):
![image](https://user-images.githubusercontent.com/66630787/233795287-335772a4-8af8-46ac-b8c9-19ec98026559.png)

After Change (at 125% scaling):
![image](https://user-images.githubusercontent.com/66630787/233795349-76e882eb-ad76-4a62-a6e7-0a781a112769.png)

**Comment by Dark-Peace** [comment]
Thank you !!!
I hope you'll find how to fix the portals auto-expanding on startup too 👍

**Comment by Ross-Patterson** [comment]
Yes - already fixed that in my local environment and will also include in the next release.

**Comment by Ross-Patterson** [comment]
Version 3.0.1.0 now available from the beta channel, if you switch to the beta channel in the settings. Your icons should be crisp even at 125% now.

![image](https://user-images.githubusercontent.com/66630787/234681941-3ff33f7b-0259-4c12-bbc1-33d1064c1e20.png)

**Comment by Dark-Peace** [comment]
It works like a charm ! Thx
