### ISSUE TITLE
expand all portals when start the program

### ISSUE THREAD

**Issue by hamedagule** [Ross-Patterson/Portals-Desktop-Organization#122]
First thanks for new update(3.0) it fixed many issues

But there is a annoying bug that introduced in new update:
I have some collapsed portals , when I restart windows or just close portal program and reopen it all collapsed portals become expanded , I want those portals remember last state and don't expand automatically when the program restart (Like previous version)

Many Thanks.

**Comment by Ross-Patterson** [comment]
Thanks for reporting, will look into this

**Comment by Dark-Peace** [comment]
Yeah I have that too.
Honestly, I think I'll go back to the previous version. There's too much little bugs. I'll update back when it'll be more stable.

**Comment by Ross-Patterson** [comment]
v3.0.1.0 is available from the beta channel now if you switch to it in the settings, Portals will keep their last minimized/maximized state now.
![image](https://user-images.githubusercontent.com/66630787/234681602-a388ebc2-c126-4016-bc73-18db5c324d74.png)

**Comment by hamedagule** [comment]
Thanks for fixing new version looks awesome

**Comment by Ross-Patterson** [comment]
3.0.1.0 is now released to prod channel, so closing this issue.
