### ISSUE TITLE
BUG: Portals dissappear when hot plugging second monitor.

### ISSUE THREAD

**Issue by privatedev11** [Ross-Patterson/Portals-Desktop-Organization#123]
**Describe the bug**
When my laptop is on and I plug in another monitor, my portals dissappear, even when the app is running. However, if it is shutdown when I plug it in, they are there.

**To Reproduce**
1. Open portals on a laptop.
2. Plug into a second monitor **whilst it is on**

**Expected behavior**
Portals dissappear, even when restarting portals.

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2

**Comment by Ross-Patterson** [comment]
I would recommend using the Display Setups & Layouts features to create a layout for each display setup you have.
