### ISSUE TITLE
Portals keep expanding after PC reboot

### ISSUE THREAD

**Issue by Jabo889** [Ross-Patterson/Portals-Desktop-Organization#124]
All the portals on the Windows 10 desktop keep expanding after a PC reboot. I cannot find an option to keep the portals contracted on boot. This issue started as soon as the portals were updated to version 3.0. In the previous version, everything worked fine.

**Comment by Ross-Patterson** [comment]
This is a regression that will be fixed in the next patch, coming in a few days.

**Comment by Ross-Patterson** [comment]
Duplicate of #122
