### ISSUE TITLE
Can't launch Portals to activate the license

### ISSUE THREAD

**Issue by Maurilio97-P** [Ross-Patterson/Portals-Desktop-Organization#126]
**Describe the bug**
Can't launch Portals to activate the license, It says the application is already running (but without a license I can't change any settings).

After the last update, I did not like the solid background (I liked the transparent), but now I can't change it. 

![image](https://user-images.githubusercontent.com/74433142/235554045-3f78ea14-a20b-45d6-b03f-cf49a3ec1c04.png)

This box is not showing :(
![image](https://user-images.githubusercontent.com/74433142/235555452-8ce3d79e-d1a3-4d87-b8b4-e3353d82a9e8.png)

I am using Windows 10

**Comment by Ross-Patterson** [comment]
Did you get it to work?

**Comment by Maurilio97-P** [comment]
Yes, thanks
