### ISSUE TITLE
Portals 3.0.1 CRASHES ON LAUNCH

### ISSUE THREAD

**Issue by RannerBoss** [Ross-Patterson/Portals-Desktop-Organization#128]
After installing the new version cannot open the app, keeps me crashing on start.

Windows Crashed Info:
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	Portals.exe
  Problem Signature 02:	3.0.1.0
  Problem Signature 03:	cbe5d8d5
  Problem Signature 04:	Microsoft.AppCenter
  Problem Signature 05:	5.0.1.0
  Problem Signature 06:	b66560a3
  Problem Signature 07:	17e
  Problem Signature 08:	2c
  Problem Signature 09:	System.EntryPointNotFound
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	16394
  Additional Information 1:	8f20
  Additional Information 2:	8f20fa7a67701791979b8ee469446218
  Additional Information 3:	4330
  Additional Information 4:	4330303de04332138c01fbddb32ea7b7
####################################################################

Event Viewer log:
Faulting application name: Portals.exe, version: 3.0.1.0, time stamp: 0xcbe5d8d5
Faulting module name: KERNELBASE.dll, version: 6.1.7601.24545, time stamp: 0x5e0eb6bd
Exception code: 0xe0434352
Fault offset: 0x000000000000b87d
Faulting process id: 0xe30
Faulting application start time: 0x01d97dfb96295e51
Faulting application path: F:\Portals\Portals.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: d438b3bd-e9ee-11ed-8d37-6cf049e83124

#############################################################
Application: Portals.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.EntryPointNotFoundException
   at Microsoft.AppCenter.Utils.WindowsHelper.GetCurrentPackageFullName(Int32 ByRef, System.Text.StringBuilder)
   at Microsoft.AppCenter.Utils.WindowsHelper._IsRunningAsUwp()
   at Microsoft.AppCenter.Utils.WindowsHelper..cctor()

Exception Info: System.TypeInitializationException
   at Microsoft.AppCenter.Utils.WindowsHelper.add_OnMinimized(Microsoft.AppCenter.Utils.WinEventDelegate)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..cctor()

Exception Info: System.TypeInitializationException
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..ctor()
   at Microsoft.AppCenter.ApplicationLifecycleHelper.get_Instance()
   at Microsoft.AppCenter.AppCenter..ctor()
   at Microsoft.AppCenter.AppCenter.get_Instance()
   at Microsoft.AppCenter.AppCenter.PlatformStart(System.String, System.Type[])
   at Portals.EntryPoint.SetupAnalytics()
   at Portals.EntryPoint.Main(System.String[])

It was working fine till the latest update, can i do a rollback or how do i solve this?

**Comment by Ross-Patterson** [comment]
Is it crashing consistently?

**Comment by RannerBoss** [comment]
Doesnt work anymore over Win7 x64??  did a fresh install and still same crash error on loading the App...can i get the link for previous versions?

**Comment by Ross-Patterson** [comment]
Windows 7 isn't "officially" supported unfortunately. It reached its end of life in Jan23.

You could try installing .NET Framework 4.8 runtime on your Win 7 PC:
https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-web-installer

If that doesn't work, here is the link to v2.1.0.6 which you will be limited to:
https://downloads.portals-app.com/installers%2F2.1.0.6%2Fportals_installer_v2-1-0-6.exe?alt=media
