### ISSUE TITLE
Icons for Modern apps

### ISSUE THREAD

**Issue by Ampa** [Ross-Patterson/Portals-Desktop-Organization#13]
The icon for Modern apps (installed via the Microsoft Store) appear blank white when in a Portal.

Can you add support for this type of app?

**Comment by Ampa** [comment]
Here is a screenshot.

Fresh Paint is a 'Modern' app installed via the Microsoft Store.

![Modern App Portals](https://user-images.githubusercontent.com/1459388/166109455-0fd6f683-553e-4dc4-a7f5-cacd9f738836.png)

Interestingly the same issue seems present in Coodesker!

![Modern App Coodesker](https://user-images.githubusercontent.com/1459388/166109465-7d343ab0-2568-4bc7-8897-70cdfef57c19.png)

I think that the icon was present to begin with in both apps, but then disappears after some time (possibly a reboot, or resume from sleep?)

**Comment by Ross-Patterson** [comment]
Unfortunately I don't think there is much that can be done here. 

Does the icon appear if you move it to the normal desktop?

Seems like an issue with Windows not storing the icon properly, meaning 3rd Party apps can't pull the icon.

**Comment by Mookiefer** [comment]
I have the same problem with Portals and Microsoft Store apps. What you say about 3rd Party apps is not true though. I use Stardock Fences on my work PC and those icons show up correctly within that app.

**Comment by Ross-Patterson** [comment]
Can you try in v3.0.0?

**Comment by Ross-Patterson** [comment]
Icons pulling correctly for modern apps in the new version:
![image](https://user-images.githubusercontent.com/66630787/234970041-cdec8095-4dde-4d76-8daa-2f9dfdd0866d.png)
