### ISSUE TITLE
BUG: Portal hide when double click on icon in desktop

### ISSUE THREAD

**Issue by jerrrb** [Ross-Patterson/Portals-Desktop-Organization#132]
**Describe the bug**
When double click to hide portal is enabled double clicking on an icon to open a program hide (or show) the protals.

**Expected behavior**
Double clicking on an icon should not trigger the hide/show feature

**Desktop:**
 - OS: WIN 10

**Comment by dking02** [comment]
The option to double-click on the desktop to show/hide portals should be left disabled, grayed-out, or removed from the app settings until the developer can figure out how to confine its effectivity to double-clicks on a blank area of the desktop. The double-click app setting was introduced in v2.0.6 and I reported the problem to the developer by email in late Oct 2022 along with a related secondary issue of two double-clicks being required in some cases. Per the Discussions section (#107), the developer originally removed the double-click option in Portals v3.0.0 but re-instated it when some beta testers noticed it missing, explaining that the reason he had removed the option in the first place was that it required extra double-clicks in some cases and apparently forgetting that the primary problem was that it was triggering the portals to show/hide when a desktop icon was double-clicked. In v3.0.1, this primary problem persists. The secondary problem with requiring extra double-clicks in some cases appears to have been resolved in v3.0.1.

**Comment by jerrrb** [comment]
I'm aware of the troubled history of the double click, but I think that
even with those slightly inconvenient bugs is an awesome feature and should
not be removed

Il ven 12 mag 2023, 12:49 dking02 ***@***.***> ha scritto:

**Comment by Ross-Patterson** [comment]
It was actually removed in 3.0.0, then got lots of requests to add it back in, even with its issue of currently firing even when double clicking a desktop icon. So I added it back in, and it is turned OFF by default.

If you don't want to use it because of is known issues, just turn it off.

**Comment by Ross-Patterson** [comment]
In Addition, this issue will be fixed in 3.0.2:
![PortalsDblClick](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/a857bbad-86b1-4888-adbf-d9765c105388)

**Comment by Ross-Patterson** [comment]
v3.0.2.0 now available via beta channel in the settings.
