### ISSUE TITLE
FEATURE REQUEST: no go zone for desktop auto placement

### ISSUE THREAD

**Issue by jerrrb** [Ross-Patterson/Portals-Desktop-Organization#133]
**Is your feature request related to a problem? Please describe.**
When a program create a file on desktop (eg: save to desktop in ms office) an icon is created in the topleftmost empty space in desktop, that for me usually is under a visible portal

**Describe the solution you'd like**
Would be perfect if windows auto placement would not place icon under existing portals or the ability to set no go zone for auto placement

**Describe alternatives you've considered**
invisible placeholder to put on desktop maybe

**Comment by Ross-Patterson** [comment]
The intention of Portals is never to manipulate your actual desktop icons (like fences seems to do). So this will not be implemented unfortunately.
