### ISSUE TITLE
Libraries as Portals?

### ISSUE THREAD

**Issue by github1328** [Ross-Patterson/Portals-Desktop-Organization#134]
Right now Windows (10) Libraries can't be used as a portal, the OK button is greyed out when selecting a library.
Is there any chance this might be a future option?

**Comment by Ross-Patterson** [comment]
From what I see, each Library has an equivalent folder inside it, which you can create a Portal from:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/0f5478a7-c94f-42c5-b810-f6ee91e37747)

**Comment by github1328** [comment]
Well, that's because your libraries only have one (the default) folder in them. If you add another folder (which is the purpose of the library) you will have all those folders listed under the library.

**Comment by Ross-Patterson** [comment]
Yes, so all you have to do is create the portal from the 2nd level folder, see example where the library contains folders:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/db309536-fe71-4e8e-aca8-7030afcbb9af)

**Comment by github1328** [comment]
> Yes, so all you have to do is create the portal from the 2nd level folder, see example where the library contains folders
Sadly isn't the solution. It does work, but it defeats the purpose of the library as it will only use that one folder as the portal, not the library with all it's folders. 
![portals libraries](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/132098201/bd0f689e-488b-42dc-8f8f-e6843e3a8b53)

I don't know how the Windows libraries work but it's probably so different from normal folder that it doesn't work with the way you built Portals.
Maybe Portals can have it's own library function - allow the portals to be comprised of files/folders from different places? 

I have neurological problems that make organizing difficult for me and it's not always possible to have all files in the same folder that have some sort of connection; which I mitigate using the libraries.

Excuse my pushiness, it's not a problem if there's not solution, I love your program regardless. 
Thanks for taking the time to reply.
