### ISSUE TITLE
BUG: Incorrect icon displayed for internet shortcuts (.url files)

### ISSUE THREAD

**Issue by dking02** [Ross-Patterson/Portals-Desktop-Organization#135]
Portals v3.0.1 displays a blank (generic file) icon for internet shortcuts (.url files) for which File Explorer displays the icon of the user's default browser. This difference is a regression from v2.1.0.6 which correctly displayed the same icon as File Explorer. A workaround is to use an application type .lnk shortcut with the target being the default browser executable with the URL as its argument as illustrated in the following example:

(1) .url (displays incorrect icon in Portals): target = https://portals-app.com/

(2) .lnk (displays browser icon in Portals): target = 
    "C:\Program Files\Google\Chrome\Application\chrome.exe" https://portals-app.com/

Per the Discussions section (#107), a fix has already been developed that will be included in the next update. This bug issue has been opened to document and provide status of the problem in the current v3.0.1 release.

Note: This problem with Portals displaying a different icon than File Explorer does not apply to .url files whose icons have been explicitly set (changed) to a local copy of the site's favicon or to some other icon different from the default browser's executable.

This problem was observed in Portals v3.0.1 in both Windows 10 and 11 (64-bit).

**Comment by Ross-Patterson** [comment]
Thanks for raising, yes it has already been discussed in #107 and a fix is coming in v3.0.2.

**Comment by Ross-Patterson** [comment]
v3.0.2.0 now available via beta channel in the settings.
