### ISSUE TITLE
BUG: "Close All Portals" not working

### ISSUE THREAD

**Issue by dking02** [Ross-Patterson/Portals-Desktop-Organization#136]
In v3.0.1, the "Close All Portals" option at (Setup > Home tab > Menu button) does not close any of the current portals listed on the Home tab. As a result, it is necessary to close each of the affected portals individually.

This problem was observed in v3.0.1 on both Windows 10 and 11 and is a regression from v2.1.0.6 where this option did work as intended.

**Comment by Ross-Patterson** [comment]
Thanks for reporting, will fix in v3.0.2

**Comment by Ross-Patterson** [comment]
v3.0.2.0 now available via beta channel in the settings.

**Comment by dking02** [comment]
I checked out the 3 fixes identified in your emails plus the 2 preview features included in Portals v3.0.2.0. All checked out OK on Windows 11.

 

See the attached PDF for details and some other items.

 

David A. King

Mountain View, California, USA

***@***.*** ***@***.***>

**Comment by Ross-Patterson** [comment]
Can't see any PDF attached, I assume you probably replied to the email rather than commenting directly on this issue in GitHub.
