### ISSUE TITLE
FEATURE REQUEST: Include arrow overlay on icons for shortcuts

### ISSUE THREAD

**Issue by dking02** [Ross-Patterson/Portals-Desktop-Organization#137]
Portals does not currently display icons for shortcuts with the characteristic shortcut/arrow overlay (the little blue arrow at the bottom left corner of an icon) used to visually distinguish a shortcut (.url or .lnk file) from a regular file or folder. This is inconsistent with the normal appearance of desktop shortcuts or shortcuts further down in the file system in Windows. When using Portals, this difference is readily apparent as most items on the desktop are shortcuts.

The icons for shortcuts in portals should include a shortcut/arrow overlay by default. Shortcut icons without the overlay could possibly be left as an option in Portals for those who have hacked the registry of their system to remove the overlay on the rest of their shortcuts.

**Comment by Ross-Patterson** [comment]
Released to beta channel as 3.0.2.1 but as a preview feature.
