### ISSUE TITLE
FEATURE REQUEST: Add “Info” column to the Layouts table

### ISSUE THREAD

**Issue by dking02** [Ross-Patterson/Portals-Desktop-Organization#138]
Add an “Info” column to the Layouts table so the user can check the contents of the selected layout before applying it. Pushing the button in the column should display a list of the portals included in the layout, name is sufficient. An alternative would be a simplified version of the portals table on the Home tab but which is read-only and does not include the Customize and Close columns.

**Comment by Ross-Patterson** [comment]
I can do this - will require a bit more work so will keep it for 3.0.3 probably.

**Comment by Ross-Patterson** [comment]
Released to beta channel as 3.0.2.1.

**Comment by dking02** [comment]
I have confirmed successful implementation of the suggested alternative in v3.0.2.1 (beta).
