### ISSUE TITLE
FEATURE REQUEST: Add name of affected portal to “Customize Portal” display

### ISSUE THREAD

**Issue by dking02** [Ross-Patterson/Portals-Desktop-Organization#140]
Add the name of affected portal to the Customize Portal display opened by Customize Portal option of the portal’s Menu Button so it is clear which portal will be or has been affected by the customization when multiple portals are in the vicinity.

Screenshot (Example)
![Customize Portal](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/64233068/fcd6aa48-51a0-4471-ab89-82fe36de315a)

**Comment by Ross-Patterson** [comment]
This is easily done, will probably do this as a 3.0.2.1 before fully releasing 3.0.2

**Comment by Ross-Patterson** [comment]
There we go:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/21a45d8e-bf0d-4f2c-838a-59a9c0e9ff55)

**Comment by Ross-Patterson** [comment]
Released to beta channel as 3.0.2.1.

**Comment by dking02** [comment]
I have confirmed successful implementation of the requested feature in v3.0.2.1 (beta).
