### ISSUE TITLE
BUG: Clicking the “Ascending” sort order button causes Portals to crash

### ISSUE THREAD

**Issue by dking02** [Ross-Patterson/Portals-Desktop-Organization#141]
The following problem is being observed in Portals v3.0.1 and is a regression from v2.1.0.6.

When sorting the contents of a portal by name, type, date, or size, clicking the “Ascending” sort order button will cause a crash. This will occur whether the current sort order of the portal as indicated by the button with the check mark is (1) ascending or (2) descending.

(1) When the current sort order is ascending order, clicking the “Descending” button will change the sort order to descending and move the check mark to the “Descending” button as expected.  However, if you click the “Ascending” button instead, Portals will crash. 

(2) When the current sort order is descending order, the expected next user action would be to click the “Ascending” button to change the sort order to ascending. However, clicking the “Ascending” button, will cause Portals to crash. Clicking the “Descending” button which already has the check mark will cause the sort order to change to ascending.

What is occurring: The “Descending” button is acting as a toggle. Each time it is clicked, the sort order changes. The “Ascending” button never changes the order but instead always causes Portals to crash.

What should happen: When you click the button for the sort order which is already in effect (check mark), no change should occur. When you click the button for the sort order which is currently not in effect (no check mark), the sort order and check mark on the button should change to the other state.

**Comment by Ross-Patterson** [comment]
Replicated on my side, will hopefully fix before prod release of 3.0.2

**Comment by Ross-Patterson** [comment]
Released to beta channel as 3.0.2.1.

**Comment by dking02** [comment]
The crash has been eliminated but the UI has not been implemented correctly. 

As implemented in v3.0.2.1 (beta), clicking on either button (Ascending or Descending) will toggle the sort order. When two buttons are provided, only clicking on the button opposite the current state should change the state (as described in the issue).  See the Sort menu in File Explorer for an example.

Alternatively, the separate Ascending and Descending buttons could be eliminated and the single button for each property (name, type, date, size) augmented to include an up or down arrow to indicate the current sort order; e.g., Name  -  (^ or v). This alternative UI would be similar to clicking on the headings of columns in File Explorer or MS Office applications to sort a list or table.

**Comment by Ross-Patterson** [comment]
Or maybe just get rid of the "Ascending" button, and ascending is the default. If descending if checked it is active, otherwise it is ascending.

**Comment by dking02** [comment]
Or get rid of the "Ascending" button and the checkmark, and label the remaining sort order button with the current sort order. Then simply toggle the button label between "Ascending" and Descending" each time it is pressed and the sort order is reversed.
