### ISSUE TITLE
will not open...

### ISSUE THREAD

**Issue by chkster** [Ross-Patterson/Portals-Desktop-Organization#142]
**Describe the bug**
Got this error when trying to open on silicon mac PowerBook pro 2021 (-10661**)
To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ross-Patterson** [comment]
Any more info you can give? Not much to go on from the above.

Any crashlog generated?

**Comment by Ross-Patterson** [comment]
Closing due to no response.
