### ISSUE TITLE
.LNK File extension is not hidden even if "Hide .lnk and .url extensions" option is active

### ISSUE THREAD

**Issue by Max1234-Ita** [Ross-Patterson/Portals-Desktop-Organization#144]
**Describe the bug**
As per the subject, if a link file has extension ".LNK" (uppercase), that extension is not hidden.

Most probably this is due to strict check on extension string (case sensitive), although Windows behaviour is mostly case insensitive. 
I suspect the same issue affects also .URL files and other variations (.Lnk, .urL, etc.)

Hope this is easy to fix. Thanks for all the work!

_
**To Reproduce**
1. Have a portal created and displayed, pointing to any directory in the local computer.
2. In the computer Desktop, create a link to any (existing) application or document and rename it so the extension is _".LNK"_ (all uppercase characters)
3. Double click the link and verify it actually launches the pointed app.
4. Move the link into the portal
5. Verify that the file extension is not hidden
6. Go to the Portals configuration menu and change the velue of "Hide .lnk and .url extensions" option; Verify the _.LNK_ extension is never hidden.

_
**Expected behavior**
If _"Hide .lnk and .url extensions"_ option is enabled, _.LNK_ extension should be hidden as well as _.lnk_

_
**Screenshots**
Posting an example screenshot (highlighted icon in picture shows the issue)

_
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/15315381/a6bb5ba7-6e0e-4afb-bf95-5ae468912e76)

**Desktop (please complete the following information):**
 - OS:Windows 10 Professional

**Additional context**
Using Portals v. 3.0.1.0

**Comment by Ross-Patterson** [comment]
Thanks for raising! Just a case sensitivity thing, very easy fix! Will include in 3.0.2
