### ISSUE TITLE
BUG: Portals table in Settings not updated when a “Change Folder” is performed

### ISSUE THREAD

**Issue by dking02** [Ross-Patterson/Portals-Desktop-Organization#149]
“Change Folder” allows an existing portal on the desktop to be reused for displaying a different folder rather than having to create a new portal. However, the path in the portals table in Settings is not updated when a “Change Folder” is performed from the menu button of the portal. The name in the header of the portal changes to the name of the new folder as expected but the path of the portal in Settings remains pointing to the old folder, even if the main window is closed and then reopened. This situation can be very confusing since the portal table no longer reflects the actual path (identity) of the corresponding portal on the desktop. If it is not possible to refresh the table automatically (i.e., programmatically), add a manual refresh button to the table.

A current workaround for this problem is to click on the heading of the Path column in the portals table to sort the list of portals. This will refresh the table and update the paths of the portals.

**Comment by Ross-Patterson** [comment]
Good catch. Have fixed it in 3.0.2.2 which will be the main release.

The table on the main home page actually should not be sortable - because dragging the items in that table controls the window order of the portals and sorting would make it not aligned, have fixed that also.

**Comment by dking02** [comment]
Actually, clicking on the path column heading would toggle the sort in the table and had refreshed the path but the actual order of the portals on the desktop became stuck in reverse order after the first click. It then also became impossible to drag and drop entries in the table to adjust the order. As you note above, these problems are resolved in the v3.0.2.2 release of 31 May 2023.
