### ISSUE TITLE
FEATURE REQUEST: Add context menu items to open the target folder of an icon in a portal to a new portal or the same portal

### ISSUE THREAD

**Issue by dking02** [Ross-Patterson/Portals-Desktop-Organization#151]
The context (right-click) menu for icons in a portal already includes a menu item to “Open” a target file or folder in Explorer in a new window. This suggested enhancement would add two Portals-specific context menu items to the icons for folders or folder shortcuts ("Open in **NEW** portal” and “Open in **SAME** portal”) to open the target folder in a portal instead of an Explorer window. These two options would be corollaries to the options in Explorer to open a subfolder either in a new window or the same window.

“Open in **NEW** Portal” would replicate the function of the existing “Create portal from folder” Explorer menu item but would not require the user to have added the item when Portals was installed.

“Open in **SAME** portal” would be similar to the “Change Folder” option of a portal’s menu button but without the need for the user to browse to and select the desired folder.

**Comment by dking02** [comment]
The suggested implementation above should also satisfy issue #47, Feature Request: Folder browsing in portal.

**Comment by Ross-Patterson** [comment]
Folder browsing in a portal probably isn't going to happen i.e. with ability to go up/down etc.

Opening a folder in a new Portal is already possible from the Explorer Menu.

I think using "Change Folder" is fine if you want the Portal to point to a different portal - I don't want to overcomplicate it and have too many context menu buttons.

**Comment by dking02** [comment]
**_Folder browsing in a portal probably isn't going to happen i.e. with ability to go up/down etc._**

The proposed change does not suggest adding the ability to go up, back or forward through the file tree in Portals like you can in Explorer or third-party file managers. It would only allow you to go down a level to open a folder in a portal rather in a window in Explorer which will be larger in size and lack the customization of a portal. I don’t envision that it would be used for more than one or two levels in portals whose folders were specifically created to collect shortcuts to organize the desktop (as opposed to displaying the contents of existing folders on the desktop which I do regard as a primary use of Portals). The suggested enhancement would also be useful for marketing purposes.

_**Opening a folder in a new Portal is already possible from the Explorer Menu.**_

This capability is only available if the user did not deselect the addition of menu entries at time of installation, an option introduced in 3.0.2.2. It is simpler to select an entry in the portal menu rather than having to open the Explorer menu and look for the “Create Portal from Folder” entry among the many items that typically appear in the context menu for folders.  Spawning a new portal from the existing portal also provides the opportunity to have the new portal inherit the size and customization of the existing portal (similar to “Change Folder”) rather than default settings as occurs when done from the Explorer menu.

Note: It is already possible to open a folder or folder shortcut in a new portal by changing item to application shortcut to portals.exe. However, that capability will not propagate down to folder items in the new portal without the suggested change. 

_**I think using "Change Folder" is fine if you want the Portal to point to a different portal - I don't want to overcomplicate it and have too many context menu buttons.**_

This change was suggested to have a convenient method for opening a folder in a portal within Portals similar to opening a folder in a window in Explorer. Currently, the portals menu has the same seven selections for all file types in a portal. This change would add two menu items only for folders and folder shortcuts. The functions to open a folder in a portal and to change the folder of a portal are already implemented in Portals, so the amount of code to implement this enhancement should be minimal. The “Open in SAME portal” command eliminates the inconvenience of having to browse to the target folder if the folder is already present in the portal. However, as a related change, I would recommend replacing the existing browse to folder control in “Change Folder” with a standard open file dialog so that users can paste the path of the target folder into the dialog box as an alternative to browsing to the target folder.

Note: The use case for the existing “Change Folder” is not explained in the current Help documentation. As noted above, I assume it is intended to allow a similarly customized portal to be created for a different folder. However, as currently implemented, the existing portal is repurposed/replaced without warning and its customization possibly lost if it had not been saved in a layout.

**Comment by Ross-Patterson** [comment]
I have now also added the ability to use the windows explorer menu as default menu, which includes the "Create Portal from Folder" option (if you selected to add it during installation).
