### ISSUE TITLE
(BUG LISTS)  PURCHASED AND FOUND SOME BUGs: your shortcut conflicts with a Chrome shortcut 

### ISSUE THREAD

**Issue by gittmin** [Ross-Patterson/Portals-Desktop-Organization#153]
**Describe the bug**
  Your shortcut for toggling the visibility of Portals via CTRL+SHIFT+A is conflicting with Chromes shortcut to search tabs. Please make your shortcut combo editable as there's a good chance that you might still create a replacement by accident that conflicts with something else.

**To Reproduce**
Open Chrome
Press CTRL+SHIFT+A to access Chromes Search Tab feature.

You will see that Chrome will not trigger it's hotkey as Portal's hotkey is conflicting with it.

![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/97714787/90ea7f56-13aa-4d25-8913-b92b0fd0b63f)

**Desktop**
WINDOWS 11 22H
CHROME PORTABLE

**Additional context**
There are other concerns.
 Example 1 -- there is no option to have the folders root saved off of the desktop or in a custom area. This crowds the desktop which defeats the purpose of this software.
 Example 2 -- it does not immediately open on the correct screen or monitor when starting up.
 Example 3 -- there is no option to scale the size of the icons in each square. 
 Example 4 -- sometimes Portals hides all of my windows underneath it -- covering everything on my screen. 
 Example 5 -- no natural way to drag icons in order to reorganize them inside a square.
 Example 6 -- when one renames each folder directly the software does not recognize the change without manually setting it.

**Comment by Ross-Patterson** [comment]
Will definitely look into allowing the user to choose their keyboard shortcuts in the future to avoid this.

On the other points:
1, You can create your folders anywhere, then use them as Portals. There is no requirement for them to be on the desktop.
2. Are you using any custom screen scaling? i.e. 125%. The portals are just placed using an X,Y, Width, Height, so same setup should result in same position on startup.
3. This is in the Styling settings, see here:
[Styling Portals](https://portals-app.help/help/styling/)
4. I have seen this happen, usually just a click somewhere will send them back to the bottom.
5. This is in the Portal menu, see here:
[Custom Sort Order](https://portals-app.help/help/styling/use-a-custom-sort-order/)
6. Yes this is right, rename the Portal from the app itself, don't rename the folders outside of the app or they will lose their reference.
