### ISSUE TITLE
BUG: autoresize on the sides

### ISSUE THREAD

**Issue by iznDev** [Ross-Patterson/Portals-Desktop-Organization#158]
**Describe the bug**
When trying to zoom a portal directory to the side of the screen it only allows auto-expanding.

**To Reproduce**
1. Create a portal
2. Drag it to any edge of the screen.

**Video**
https://streamable.com/02xvdv

**Desktop (please complete the following information):**
Windows 11 - 22H2

**Comment by Ross-Patterson** [comment]
This is just default behaviour for a Windows window (which is all a Portal is).

Its actually related to Mouse position. So workaround is:
1. Make header on left temporarily
2. Drag to position
3. Move header back to right.

OR

1. Do a quick calculation and set it manually using X,Y on the Home window.
