### ISSUE TITLE
Zip files are opened in Explorer.exe

### ISSUE THREAD

**Issue by falulon** [Ross-Patterson/Portals-Desktop-Organization#16]
Not a big deal, but when opening zip files, they get opened in the native file explorer, instead of the designated app as always. 
![image](https://user-images.githubusercontent.com/79255543/166901125-5fed0ec3-4274-4f64-89f5-d609b1aabdac.png)
![image](https://user-images.githubusercontent.com/79255543/166901720-e213534c-53d7-4782-913a-ba60e846263d.png)

This occurs only from Portals (and not if I open the file from the Windows file explorer)

**Comment by Ross-Patterson** [comment]
I have fixed this issue in my dev version, will include in next update,
