### ISSUE TITLE
Crash on attempt of deleting file inside portal

### ISSUE THREAD

**Issue by xa19** [Ross-Patterson/Portals-Desktop-Organization#161]
**Describe the bug**
When I click on the file inside the portal and try to delete it, either by pressing Delete key on my keyboard or by using mouse (Right click on file -> Delete), the Portals crashes.
I can properly delete the file only by manually browsing the folder related to the specific portal and deleting it there (in the Windows Explorer).

**To Reproduce**
1. Create a portal
2. Add any file to it
3. Try to delete it inside the portal (select it and press Delete on the keyboard)

**Expected behavior**
The selected file disappears both, in the portal and in the related folder, without crashing.

**Screenshots**
The "Portals: Desktop Organization has stopped working" error appears.
![Screenshot](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/1276205/a729e480-aa02-41d5-a838-fbe7a63ec0f3)

**Desktop (please complete the following information):**
 - OS: Windows 10 (64-bit)
 - Browser: Firefox 114

**Additional context**
When the crash error appeared and I clicked "Debug" (which opened up Visual Studio), there was some info about the Access Violation exception.
I've added the Portals to the firewall/antivirus exclusions but that didn't change anything.
Running Portals as admin also didn't help.

**Comment by Ross-Patterson** [comment]
Any logs in 
C:\Users\<user>\AppData\Local\Portals\crashlogs\
or
C:\Users\<user>\AppData\Local\Portals\logs\

?

**Comment by Ross-Patterson** [comment]
Closing due to no response
