### ISSUE TITLE
A "restart Portals" context menu item on the mini taskbar icon to mitigate frustration with a bug

### ISSUE THREAD

**Issue by DexeconGithub** [Ross-Patterson/Portals-Desktop-Organization#162]
**Is your feature request related to a problem? Please describe.**
Portal size and locations / scaling change on startup based on which monitor turns on first (working with multiple monitors with different resolutions and scaling options) 

**Describe the solution you'd like**
for portals not to do this, but im not technical enough to understand what an actual fix might be

**Describe alternatives you've considered**
a right click context menu on the mini taskbar icon to restart portals software

**Additional context**
when closing and running portals again, it fixes the issue until the next startup. so this suggestion is just to simplify closing and running portals again

**Comment by Ross-Patterson** [comment]
Can you give more info? Is this when you are turning on monitors yourself? Or is Windows choosing a monitor (seemingly at random?).

I can add that options thats an easily thing to do.

**Comment by Ross-Patterson** [comment]
Added the option in v3.0.3.0 which is now available from the beta channel

**Comment by DexeconGithub** [comment]
> Can you give more info? Is this when you are turning on monitors yourself? Or is Windows choosing a monitor (seemingly at random?).
> 
> I can add that options thats an easily thing to do.

Apologies for the late reply!

It happens when the computer boots up, but one of the monitors is still off. (it's a 4k TV which is set to be my main display in windows, the others are 1080p, the TV has the portals laid out in it).

When i turn the TV on, windows does the weird resolution resizing thing it does, and the portals get thrown out of position. usually a simple restart of portals fixes it so i really appreciate you including that in the new beta! it'll make my life a lot more convenient.
