### ISSUE TITLE
\make Portals take up space / displace new things added to the desktop

### ISSUE THREAD

**Issue by mokkat** [Ross-Patterson/Portals-Desktop-Organization#163]
**Is your feature request related to a problem? Please describe.**
I used Fences before, and Portals is way better - except for the fact that Portals don't take up space to displace new icons/files being added on the regular Windows desktop. 
If for example I want a Portal of folders in the top left corner of my desktop, new downloaded files will get stuck in its background.

**Describe the solution you'd like**
I'd like an option for Windows to consider the volume of the Portal as space already taken up

**Describe alternatives you've considered**
Fences, but it's bad now. 
Separate Portal with files and stuff, but it's not optimal

**Additional context**
![Screenshot 2023-07-21 225514](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/43669435/a6cacb04-b8b5-4940-8962-5195497e4497)

**Comment by Ross-Patterson** [comment]
I understand its annoying but with the Portals app my commitment is that the app will never manipulate your actual desktop i.e. move/hide icons.

So unfortunately this will never be implemented.
