### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by mdjbn** [Ross-Patterson/Portals-Desktop-Organization#164]
Request Chinese support. If you need help with a Chinese translation, I can help.

**Comment by Ross-Patterson** [comment]
Hi There - I have now set up community translations, see here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/184#discussion-5743458

**Comment by Ross-Patterson** [comment]
Thanks for doing the translations for Chinese Simplified! It is much appreciated!

I have added them into the beta version v3.0.3.1 which is available now if you switch to the beta channel in the settings:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/0e1f3c58-61d4-4e5c-b03a-08684b55e68e)
