### ISSUE TITLE
Buggy Mouse Hover on Portal Header + Content due to Alpha 0

### ISSUE THREAD

**Issue by TLCPlusPlus** [Ross-Patterson/Portals-Desktop-Organization#166]
**Describe the bug**
I tried to make some completely transparent Portal Headers and Content, but it's very hard to maintain with a hover if its alpha is 0. 

**To Reproduce**
1. Go to 'Customize Portal'
2. Click on 'Portal Header' or 'Portal Content'
3. Scroll down to 'Background Color'
4. Enable (if it's not already)
5. Select drop down
6. Pick any RGB/HSV Value, but make sure A (alpha) is set to 0 for complete transparency.
7. Exit window
8. Try to access affected portal, you should see its extremely infuriating to access Portal Header + Contents

**Expected behavior**
The same behavior any other alpha value has, which hovering over the Header shows Content until mouse is no longer hovering over Header or Content.

**Screenshots**
N/A
(An animation would be more applicable)

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Version 22H2 (OS Build: 22621.1992)

**Additional context**
Current workaround is setting alpha to anything but 0 to get expected behavior. Im currently sitting at alpha 1 instead.

**Comment by Ross-Patterson** [comment]
In Windows, if a window background is transparent (alpha 0), it becomes click-through. So since each Portal is just a window, this behaviour cannot be changed :(.

Only way is setting alpha to as near to 0 as possible, but not 0.

See here:
https://stackoverflow.com/a/1646459/9420881
