### ISSUE TITLE
Double start of any app

### ISSUE THREAD

**Issue by jarod67** [Ross-Patterson/Portals-Desktop-Organization#169]
**Describe the bug**
Double start of any app

**To Reproduce**
1. click on any link
2. afterwards hit the ENTER key
3. whatever App I try to start, it gets started 2 times
4. If I double-click instead, this does not happen.

**Expected behavior**
If I hit Enter, I've to see only ONE app started

**Desktop (please complete the following information):**
 - OS: Windows11

Many thanks

**Comment by Ross-Patterson** [comment]
I am not able to reproduce this behaviour.

Can you take a screen recording maybe?

**Comment by Ross-Patterson** [comment]
Closing due to no response
