### ISSUE TITLE
Disappearing/appearing portal upon clicking

### ISSUE THREAD

**Issue by mchalapetr** [Ross-Patterson/Portals-Desktop-Organization#170]
**Describe the bug**
Sometimes (seemingly randomly) there is a disappearing (first click)/appearing (second click) portal upon clicking.
This behavior is always tied to the last portal (e.g. 6th portal out of 6, 3rd portal out of 3 etc.).
It seems to me that it has to do something with changing graphics because I often switch between laptop screen and 3 external monitors.

**To Reproduce**
Clicking onto the portal.

**Expected behavior**
Same behavior as it is on other portals. When I click onto them they do not disappear.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS:  Windows 10 Enterprise
 - Version 3.0.2.2

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by Ross-Patterson** [comment]
This is related to Win+D (Show Desktop) - see here #101 (https://github.com/Ross-Patterson/Portals-Desktop-Organization/issues/101#issuecomment-1523977037).
