### ISSUE TITLE
Portal Header Bars disappear when Show Desktop button is used

### ISSUE THREAD

**Issue by BigJinge** [Ross-Patterson/Portals-Desktop-Organization#171]
If you click on the Show Desktop button to the far right of the Taskbar, the Portal Header Bars disappear, however if instead, all of the active apps are manually minimised to get back to the desktop, the Portal Header Bars are still shown. 

What should happen is that the Portal Header Bars are still shown when the Show Desktop button is used.

Windows 11 Pro version 22H2 (OS Build 22621.2124

**Comment by Ross-Patterson** [comment]
This is a known limitation, see #101 (https://github.com/Ross-Patterson/Portals-Desktop-Organization/issues/101#issuecomment-1523977037).

Workaround is shown there.
