### ISSUE TITLE
FEATURE REQUEST: Make splash screen optional

### ISSUE THREAD

**Issue by RafaelLVX** [Ross-Patterson/Portals-Desktop-Organization#177]
**Is your feature request related to a problem? Please describe.**
Splash screens on startup are veeery late 90s, in a bad way.

**Describe the solution you'd like**
Please create a setting to make the Portals splash screen optional.

**Comment by Ross-Patterson** [comment]
This is not true - just look any any of the Microsoft Office products... the splash screen allows everything to load without the user being in the dark about what is happening.
