### ISSUE TITLE
multi-screen enhancement

### ISSUE THREAD

**Issue by adamadong** [Ross-Patterson/Portals-Desktop-Organization#178]
Hi,
I am a multi-screen user, using a big screen and the screen of the laptop. As they do not share the same resolution, the usage of the application can cause problems as I go out with only the screen of the laptop.
Therefore, I would like to know if it is possible to save a setting for each of the screen/resolution that I use.
I think this would be really helpful.
Thanks a lot

**Comment by Ross-Patterson** [comment]
Yes you can do exactly this, see here:
https://portals-app.help/help/layouts-display-setups/
