### ISSUE TITLE
Continuous CPU Usage in Background Despite Hidden Widgets on Desktop

### ISSUE THREAD

**Issue by alitekdemir** [Ross-Patterson/Portals-Desktop-Organization#179]
**Describe the bug**
The Portal application is continuously consuming processor resources, even when the widgets on the desktop are hidden, it's still processing in the background. The issue can be traced in the screenshot attached.

**To Reproduce**
1. Launch the Portal application.
2. Hide the widgets on the desktop.
3. Monitor the CPU usage in the Task Manager or any other system monitoring tool.
4. Notice the continuous processor consumption even when the widgets are hidden.

**Expected behavior**
The expected behavior is that the processor consumption should significantly reduce or ideally cease when the widgets are hidden, indicating that the application is idle in the background.

**Screenshots**
![Taskmgr_2023-10-02_01-51-39](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/1507344/27dc29f9-9492-4232-aa8d-d3e075deed21)

**Desktop (please complete the following information):**
Windows 11 
 - Version: 22H2

**Additional context**
I would like to take a moment to commend the team for the incredible work on the Portal application. I am really enjoying the software and appreciate the effort put into creating such a useful and well-designed tool. Thank you!

**Comment by Ross-Patterson** [comment]
This small CPU usage is related to the analytics library I am using which tracks crashes etc. and so will remain.

Why does this small CPU usage concern you?
