### ISSUE TITLE
Portal disappearing on click

### ISSUE THREAD

**Issue by russel-lawrence** [Ross-Patterson/Portals-Desktop-Organization#180]
**Describe the bug**
The last portal added to desktop disappears and reappears on clicking it's header. I cannot access the files in that portal due to it

**To Reproduce**
1. Add multiple portals to desktop
2. Arrange them anyway you want
3. Lock the portals
4. Click the header on the last added portal. It flickers in and out of existence

**Expected behavior**
The portal should be static, not flickering.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Portals Version: 3.0.2.2

**Comment by Creveoolus** [comment]
same issue, have you find any fix for this?

**Comment by Ross-Patterson** [comment]
See here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/issues/101#issuecomment-1523977037

Hope this helps.

**Comment by russel-lawrence** [comment]
The extra hidden portal helped quite a bit. Thanks Ross.

There's another oddity as well however, with the windows multi-finger gestures, dragging 3 fingers down shows the desktop and makes ALL portals disappear. Hoping to know whether you have a fix for this?
