### ISSUE TITLE
BUG: <TITLE>Portals ran into an unexpected error and crashed

### ISSUE THREAD

**Issue by mdjbn** [Ross-Patterson/Portals-Desktop-Organization#186]
[portals-crashlog-20231020_1519.log](https://github.com/Ross-Patterson/Portals-Desktop-Organization/files/13051472/portals-crashlog-20231020_1519.log)

**Comment by Ross-Patterson** [comment]
This is happening consistently?

**Comment by Ross-Patterson** [comment]
Ok I was able to replicate by changing my computer language to Chinese, will try to find out what is going wrong.

It worked fine before the latest update?

**Comment by Ross-Patterson** [comment]
3.0.2.2 beta now available, your crash should be fixed.
