### ISSUE TITLE
BUG: <TITLE>Unable to move files to portal by drag/drop.

### ISSUE THREAD

**Issue by mdjbn** [Ross-Patterson/Portals-Desktop-Organization#187]
https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/109398679/2539d7d1-3cf9-460a-9e8a-3c07da9ffdbf

The latest beta version unable to move files to portal by drag/drop. 
The latest release does not have this bug.

**Comment by Ross-Patterson** [comment]
Can you try just shutting down the app completely then starting it fresh?

I think this is a bug related to the restart after an update. I had the same problem and just restarting the program fixed it.

**Comment by mdjbn** [comment]
Thank you! You are right, restarting the program will fix it.

**Comment by mdjbn** [comment]
> 您可以尝试完全关闭该应用程序然后重新启动它吗？
> 
> 我认为这是与更新后重新启动相关的错误。我遇到了同样的问题，只需重新启动程序即可修复它。

Thank you! You are right, restarting the program will fix it.

**Comment by mdjbn** [comment]
> Can you try just shutting down the app completely then starting it fresh?
> 
> I think this is a bug related to the restart after an update. I had the same problem and just restarting the program fixed it.

Thank you! You are right, restarting the program will fix it.
