### ISSUE TITLE
Pressing "Enter" open twice

### ISSUE THREAD

**Issue by SbiriJJ** [Ross-Patterson/Portals-Desktop-Organization#190]
On desktop, launching a program pressing enter/cr instead of double click. 
The application start twice. 
Selecting icon with mouse o keys is the same.

**Comment by Ross-Patterson** [comment]
I'm not able to replicate this, can you take a screen recording?

**Comment by SbiriJJ** [comment]
A very fast key stroke will make this happens always.

**Comment by Ross-Patterson** [comment]
I cannot replicate event hitting the key as quickly as possible. Have you tried a different keyboard?

**Comment by Ross-Patterson** [comment]
Closed due to no response

**Comment by SbiriJJ** [comment]
Sorry, I have missed that email reply doesn't worked.
I have tried different keyboard and different computer, sometimes happens only first launch, but I have used Macro Express to simulate any speed of keystroke and this way the double run happens always, regardless of speed of computer or quickness of keyboard. Pressing and depressing trigger 2 run action on Portals.
