### ISSUE TITLE
Add Password Protection

### ISSUE THREAD

**Issue by Munim1947** [Ross-Patterson/Portals-Desktop-Organization#191]
The app is very useful for me, I love it...

Please add "Password Protection" for entering the Portals main window and also for at least one portal on the desktop...

Thanks 

great application you have made.

**Comment by Munim1947** [comment]
The app is very useful for me, I love it...

Please add "Password Protection" for entering the Portals main Settings window and also for at least one portal on the desktop...

Thanks

great application you have made.

**Comment by Ross-Patterson** [comment]
I can understand the need to password protect Portal, but why password protect the main window itself?

Passwords are always difficult from a security perspective.

What's the use-case for this?

**Comment by Ross-Patterson** [comment]
No response
