### ISSUE TITLE
BUG: Overlapping portals produce visually confusing results

### ISSUE THREAD

**Issue by mschomm** [Ross-Patterson/Portals-Desktop-Organization#194]
If portals overlap during drag&drop or when expanding a minimized portal over an expanded one the result can be visually confusing:
![2023-11-05_13h56_06](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/28079144/6c07d5f4-b77c-41ef-ae41-085e757823b5)

![2023-11-05_13h56_24](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/28079144/7ef6f144-42e2-4a73-b000-4fac2e8903c6)

**Expected behavior**
Display of overlapping portals would be much better if the overlap would work like with Stardock Fences. Here the most recently expanded Fence becomes top-most and hides the content of another one which it overlaps:
![2023-11-05_14h07_31](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/28079144/0a648680-8919-4018-bddd-cf4f73fac606)
![2023-11-05_14h09_00](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/28079144/03d42f7e-f5f5-4416-a35d-5700c1314d82)

**Comment by Ross-Patterson** [comment]
In the last update deployed just a few days ago I added this feature. When the mouse enters a Portal, it will be brought to the top.

The contents of the one below will not be hidden, best to use less transparency to overcome this.

![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/b220c1d9-3582-418a-9c9b-bc61cba51165)
