### ISSUE TITLE
Desktop link file permissions not set for current user

### ISSUE THREAD

**Issue by ksn-systems** [Ross-Patterson/Portals-Desktop-Organization#196]
**Describe the bug**
When dragging a desktop shortcut into a portals window, the current users permissions are not applied. this causes one drive to fail when it tries to sync the changed desktop link

**To Reproduce**
1. drag shortcut or any file into a portal window
2. check one drive status for error

**Expected behavior**
I would expect ath the permissions are preserved and the changed file syncs to one drive

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 pro 22H2
 - Browser N/A
 - Version N/a

Portals 3.0.3.3

**Comment by Ross-Patterson** [comment]
Can you give me some before and after screenshot? Which permissions are missing?

Your reproduction steps are pretty vague, please can you clarify the exact situation, which version of OneDrive, which file type are you dragging and where from i.e. User Desktop, Public Desktop?

**Comment by Ross-Patterson** [comment]
Closed due to no response
