### ISSUE TITLE
Display Setups Mishandled

### ISSUE THREAD

**Issue by bdneum** [Ross-Patterson/Portals-Desktop-Organization#197]
**Describe the bug**
Saving a new display mistakenly detects other saved display sets to be the same.

**To Reproduce**
Save a display setup with three monitors.  (Possibly restart.)  Attempt to save another display with only two monitors (one is the same laptop, if that matters).  Get a warning that this display setup already exists.

**Screenshots**
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/150369394/75e3395b-d2b7-4715-87a6-2a103e55d029)
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/150369394/e229ba6c-61a9-4c74-bda0-be43e21a7fce)

**Desktop (please complete the following information):**
 - OS: win10

**Comment by bdneum** [comment]
I did delete them all, saved just the laptop.  Then plugged in a monitor.  Portals actually attempts to find and match a display setting...and it matches the laptop, setup, even though it has only one display.  This also happens in reverse (start with 2, go down to 1).

**Comment by Ross-Patterson** [comment]
You are right, the code code is not checking the amount of monitors is the same, its just checking that all that are present match an existing setup. Can't believe no-one as come across this until now.

Will fix in the next update.

**Comment by bdneum** [comment]
Hey, I'm just glad that I'm reporting things that are actually wrong and that you are actually seeing them and care about fixing them.  Thanks for being a good steward of your program!

**Comment by bdneum** [comment]
The choice of which monitor is your "main" display might also affect this, for what it's worth.
