### ISSUE TITLE
FEATURE REQUEST: Ability to set folder view for a portal

### ISSUE THREAD

**Issue by tranquilcarbon** [Ross-Patterson/Portals-Desktop-Organization#198]
**Is your feature request related to a problem? Please describe.**
Currently, the only way icons are displayed in a portal is using the default method (medium icons), This however is unsuitable for folders with large amounts of files (such as a documents folder)

**Describe the solution you'd like**
I would like to propose the ability to choose the way a portal will be shown, this has already been done with Stardock's fences program (although only in folder fences)

**Describe alternatives you've considered**
the program could ask what will be stored in the folder and automatically choose a view, depending on the answer (Medium icons for programs, List view for documents, Large icons for photos and videos etc.)

**Additional context**

**Comment by Ross-Patterson** [comment]
I think you are looking for this maybe:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/issues/97#issuecomment-1796570306
