### ISSUE TITLE
choose translucency amount

### ISSUE THREAD

**Issue by ak1dd** [Ross-Patterson/Portals-Desktop-Organization#199]
I use portals to keep my desktop minimal.  I have a laptop and when I have windows open at the top of the screen there is a lot of text there.   I would like to be able to choose the translucency amount for both Portal Header and Portal content.

**Comment by Ross-Patterson** [comment]
Its already there in the color picker:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/6d16f348-1c24-4210-a4ae-477dedbcce3e)
