### ISSUE TITLE
Option to auto-update, or delay updates until I click the button manually

### ISSUE THREAD

**Issue by Boomkop3** [Ross-Patterson/Portals-Desktop-Organization#2]
Option to auto-update, or delay updates until I click the button manually. This would really clean up my boot process, it's been several times now that this has been the first thing on my pc. I'm not turning it on to do maintenance. I'm turning it on to use it.

**Comment by Ross-Patterson** [comment]
Thanks for the suggestion @Boomkop3, I can very easily implement a "Remind me in..." feature with set amounts of mins/hours/days.

I also like the idea of asking the user to opt into silent auto-updating, i will look into this.

**Comment by Boomkop3** [comment]
A simple remind me in [hardcoded amount of days] alone would be a great option already. At least for me, thanks for looking into this!

**Comment by Ross-Patterson** [comment]
@Boomkop3 I have improved the update popup window, and included a "Remind Me" button and an "Auto-Update in Future" button.

Note that the Auto-Update will still require UAC approval (the Yes/No box that pops up when you install a program).

Should be available in next release.

![image](https://user-images.githubusercontent.com/66630787/163427523-a2014aa8-dbcf-40c7-a2fd-726d721294f8.png)

**Comment by Boomkop3** [comment]
This looks great! I'll be awaiting the next release!

**Comment by Ross-Patterson** [comment]
2.1.0.4 is now available with this new update UI.

**Comment by Boomkop3** [comment]
Update installed! Thank you!
