### ISSUE TITLE
Set permissions for desktop items moved from public desktop

### ISSUE THREAD

**Issue by bantza** [Ross-Patterson/Portals-Desktop-Organization#20]
I have set desktop items to backup with OneDrive. I created a new folder/portal on desktop and moved a desktop item to that portal. I then got a sync issue in OneDrive.
![image](https://user-images.githubusercontent.com/11660822/168852653-8fbc2629-a437-495d-a391-fbc0ab92fc7d.png)
I checked the permissions of the desktop shortcut and noticed they were different. It turns out the item I moved to the portal was from public desktop (all users). OneDrive doesn't backup items from public desktop, but now the item was moved from the public desktop to my desktop because the containing folder/portal is on my desktop. Also if I move the item back from the portal to the desktop it still stays on my desktop and is not moved back to public desktop where it originated.

I realize that this is not really a problem for the function of the Portals, but it could be solved with an additional feature in Portals. Make an option to change the permissions for items moved from public desktop to portals on my desktop.

**Comment by Ross-Patterson** [comment]
Portals is just invoking a move from the Windows API, so the same behavior should happen when not using Portals to move. So I won't be implementing anything in the application itself to change permissions of files.
