### ISSUE TITLE
Menu via right click

### ISSUE THREAD

**Issue by ak1dd** [Ross-Patterson/Portals-Desktop-Organization#200]
I like to keep my desktop as minimal as possible.   I'd prefer to have no buttons but still have access to options from each portal.  I'd like to be able to right click the Portal Window and have the Menu that appears if you have the menu button enabled.

I have a suggestion for the UI that might make using buttons clearer.

Have a top level item under Portal Header settings that says "Enable buttons".  Then indented sub-items that say:
- Show Lock/Unlock button...
- Show Customize Button...
- Show search button on header...
- ...
- Show Menu on right click

**Comment by Ross-Patterson** [comment]
its all already there in the settings, menu will appear in the right click menu after disabling the menu in the settings:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/46a02d38-95fc-4afc-a8c0-8dedad3dd05d)
