### ISSUE TITLE
Bring Portal to Top on Mouse over

### ISSUE THREAD

**Issue by ak1dd** [Ross-Patterson/Portals-Desktop-Organization#201]
Forgive this report if I just don't understand the feature.

I have used Fences for years and find the lack of developer attention frustrating.  I just found Portals.   In the Stardock fences forums you will see people requesting the ability for fences to come to the top of all windows on mouse over many times over many years.  The latest version still doesn't do it and developers (or forum support) have said in the past it isn't a priority.

Perhaps the Portals|Preview Features|Bring Portal to Top on Mouse Over is supposed to be this functionality.   I could not get this to work.   I am able to have windows obstructing the Portal and get them to auto expand, but the Portal window does not come to the top.

**Comment by Ross-Patterson** [comment]
Also already there:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/b1f958ed-884a-4f9e-942a-db136b0cd4d9)
