### ISSUE TITLE
Possible to change left margin size?

### ISSUE THREAD

**Issue by ak1dd** [Ross-Patterson/Portals-Desktop-Organization#202]
Is it possible to change just the left hand margin size?  I don't want to change any gaps, height or width values between icons, I'd just prefer there was a larger gap on the left of the Portal Content.

**Comment by Ross-Patterson** [comment]
Not on individual sides no, this is the closest setting:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/c90ebd10-b0d2-4289-98c0-30a5aa6f61e1)
