### ISSUE TITLE
Portals window disappearing on double-click

### ISSUE THREAD

**Issue by aguaagua2** [Ross-Patterson/Portals-Desktop-Organization#207]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aguaagua2** [comment]
I can see sometimes a random behaviour of Portals window disappearing from desktop when I double-click one of its items icons within the window.  It does not happen most of the time.  And when this happens, if I double-click again on the same place on the desktop, the window re-appear, but disappear again if I double-click again on the icon.  Just to let you know, because it's random and I don't know or control how to reproduce it at will.

**Comment by Ross-Patterson** [comment]
#101 

![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/dcd90a25-d3f2-4987-98ed-4346f8dff813)
