### ISSUE TITLE
Portals vanish, others move position

### ISSUE THREAD

**Issue by xanathon** [Ross-Patterson/Portals-Desktop-Organization#209]
I have multiple problems with portals on Windows 10/64 latest ptachlevel. I have a multi monitor setup. The problems may be related to multi monitors, so I include them both here.

1. Every morning I startup the computer two portals on the left monitor are moved. One is moved to the left, so it only is halfway seen on that monitor, the other one is moved outside of the visible area of that monitor.

2. Two portal on the main monitor sometimes (about every second day) vanish completely. They are no longer in the list of portals in settings. That may be a correlation with changes in the monitor setup via Windows display settings, but I cannot really verify that.

The behaviour is highly inconsistent. Portal positions are not rememebered correctly, other portals vanish and I have to recreate them constantly.

**Comment by xanathon** [comment]
addition: Some portals still switch position with every Windows screen change. This happens a lot, since I have two of six monitors that are activated only sometimes and mirror two other monitors. The Portals on the main screen stay where they should be, the two other portals go outside of the visible area and I have to get them back manually by changing their positions in the settings.

**Comment by xanathon** [comment]
The problems are even there if the screen resolution does not change. Portals move position or are gone completely after a simple reboot. I can get them back via layout settings but it's a big nuisance to open settings every two boots.

I guess this is a problem with Windows 10s very, very bad implemntation of multi monitor setups (that got even worse instead of better with more recend Windows 10 versions). 

If I try to save a new display setup Portals reports that I cannot save that setup because the same setup already exists.

**Comment by xanathon** [comment]
This is not (only) a resolution change problem. i have to Portals on the second monitor that are in wrong positions every morning I boot the computer and without any screen changes.

I move them to the correct position and I save the layout. The next morning they are in the wrong position again.

**Comment by Ross-Patterson** [comment]
Its the complete screen space, like this:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/3bada68d-f237-4893-90ef-d7d9d6b022db)

**Comment by xanathon** [comment]
That cannot be correct in my case, since the two portals on the screen left of the main screen have **negative position values**, as you can see in the coordinate screenshot above. See my screen setup below: the 4K screen (screen three in the screenshot) is the main screen. The two portals insicated by red arrows have negative position values.

![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/24546760/050b28d9-af65-4b03-9bf3-eaadcd441347)

As long as I do not change anything in the screen setup the portal positions should be consistent and stay the same. Of course I would have to reposition if I add or remove screens, but that is not the case. But even if I do not change qanything at all in the screen setup, after every reboot the two portals with the red arrows are in another position.

**Comment by xanathon** [comment]
This is getting extremely annoying. Without any screen setup change portals continuously change positions or vanish completely, even on the main screen. If I assign a layout they are back.

Please at least consider an entry in the Windows context menu to apply layouts so layouts can be accessed without the need to first open the portals settings. And even with apply layout two of my portal **always** are in the wrong position, there is no way whatsoever to get them to a position, save and then make them reappear at that position, they are **always** somewhere else, even if I immediatley reassign the layout.

Portal position and visibility is majorly borked on multiscreen systems even if there ar no screen changes.

**Comment by xanathon** [comment]
Okay, this is a major nuisance. I am going back to Fences. Fences is annoying, but by far more reliable on a multi monitor setup than Portals. I wanted to like and use this, but I simply cannot jump through hoops every time I start up Windows to get Portals back as I want them.

**Comment by Ross-Patterson** [comment]
> That cannot be correct in my case, since the two portals on the screen left of the main screen have **negative position values**, as you can see in the coordinate screenshot above. See my screen setup below: the 4K screen (screen three in the screenshot) is the main screen. The two portals insicated by red arrows have negative position values.
> 
> ![image](https://private-user-images.githubusercontent.com/24546760/288350535-050b28d9-af65-4b03-9bf3-eaadcd441347.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNzg1MTEsIm5iZiI6MTcwOTM3ODIxMSwicGF0aCI6Ii8yNDU0Njc2MC8yODgzNTA1MzUtMDUwYjI4ZDktYWY2NS00YjAzLTliZjMtZWFhZGNkNDQxMzQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDExMTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1YTYzZmU1YmY2MmQzMjQyMTFhY2IzYmIyOWM1OGU5MGUwZDc4NzVmMmM4N2U3NDkyZTFjODI4Mjc1ZDYwNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H1xXEZUkpnqvnVw-YSyMUDReN-eUMeIi5Mo6JusIm2U)
> 
> As long as I do not change anything in the screen setup the portal positions should be consistent and stay the same. Of course I would have to reposition if I add or remove screens, but that is not the case. But even if I do not change qanything at all in the screen setup, after every reboot the two portals with the red arrows are in another position.
> 
> Edit: Windows screen indexes stayed the same.

The negative values are correct since the top left of the 3rd screen (Primary screen) will be 0,0.

Are you using different scaling for the Primary monitor (4k one)?

I found that Windows places a window on startup based on the coordinate system of the Primary monitor. So if your primary monitor is 4K 200% scaling, then on startup all portals will be placed based on that. 

But windows records the position of a window based on the scaling of that monitor.

So if you place a portal on a 100% scaled 1080 monitor, the location will be stored based on that. But if your Primary screen is 4k 200%, then that Portal is unlikely to start up in the same position again, since it will take the stored position and place it as per the 4k 200% scaled monitor.

This is a nightmare to work around since windows doesn't provide any consistency...

I have a test build that if you were willing to I would appreciate if you could test.

Let me know.

**Comment by xanathon** [comment]
The main Monitor is on 175%, the three other monitors are on 100%. The portals are on the main monitor and on the one left from that is 1920x1050 at 100% scaling.

I am willing to test.

**Comment by Ross-Patterson** [comment]
Ok,
Please take a backup of: C:\Users\username\AppData\Local\Portals
So that you will not lose anything.
Then clear out: C:\Users\username\AppData\Local\Portals (you can leave the license.ptl file)

You can download the test version here:
https://downloads.portals-app.com/build-previews%2Fv3.3.0.0_b1%2Fportals_installer_v3-3-0-0_test1.exe?alt=media

Let me know if it resolves the problem.

**Comment by xanathon** [comment]
I just wanted to chime in to tell you that it looks good so far. I moved two portals to the secondary screen and other than earlier versions of Portals they stay there and keep their positions through all reboots. I'll do some more testing with more portals on different screens.

Thanks for your efforts!

**Comment by Ross-Patterson** [comment]
Nice I'm glad to hear it.

Keep me updated.

**Comment by xanathon** [comment]
I tried with more portals on more screens and so far (after quite some reboots) it looks like they all keep their positions. This looks good! Thanks for the fix!
