### ISSUE TITLE
Portal Title is editable even when the portal is locked

### ISSUE THREAD

**Issue by ChewbaccaR2** [Ross-Patterson/Portals-Desktop-Organization#21]
**Describe the bug**
After creating a portal with a title bar name  and locking it you can still click on the title bar name and edit it. This causes unexpected behaviour when you have selected the option to allow any part of the title bar to expand the portal. 

**To Reproduce**
1. Create portal with a title bar name
2. Change setting to allow any part of the title bar to expand the portal
3. Lock the portal
4. Click the area of the title bar where the portal name is and instead of expanding the portal it puts the portal name in edit mode 

**Expected behavior**
After locking the portal the title bar name should not be editable and should simply expand the portal when clicked.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 2.1.0.4

**Comment by Ross-Patterson** [comment]
Hi, this is correct behavior.

The lock feature is only for size & position.

**Comment by ChewbaccaR2** [comment]
Sorry that seems a very strange and poor decision and affects the
usability. When the portal is locked you shouldn't be able to edit
anything. Nobody wants the title bar to go into edit mode when they
just want to expand
