### ISSUE TITLE
drop and drag w/o icon selected

### ISSUE THREAD

**Issue by aminoginji** [Ross-Patterson/Portals-Desktop-Organization#210]
**Describe the bug**
With drag and drop enabled while in a portal without selecting an icon if you drag outside the portal it will select and icon and move one to the destination.

**To Reproduce**
Select an empty portal area left click and drag out of portal area into screen or another portal area

**Expected behavior**
nothing should happen while no icon is selected or option to move portal by dragging content is not selected

**Comment by Ross-Patterson** [comment]
Good find, this will be fixed in the next update.

**Comment by Ross-Patterson** [comment]
This is now fixed.
