### ISSUE TITLE
Have shortcuts to folders act like a normal folder in Portals

### ISSUE THREAD

**Issue by miwabi** [Ross-Patterson/Portals-Desktop-Organization#212]
Hello, while in Portals shortcuts to folders are treated the same as shortcuts to files, such as when using QuickLook on a shortcut to a folder in Portals it will bring up a preview of the .lnk file instead of bringing up the navigatable folder like it would normally. Opening the folder shortcuts in Portals causes it to be opened in a new file browser window instead of navigating in Portals.

Is it possible for this to be implemented?
Many thanks for the massive amount of hard work you've put into this project and I hope you're having a good one.

(btw thanks for implementing folder navigation and the quicklook integration so quickly, as I suggested them I very much appreciate it.)

**Comment by Somastro** [comment]
Just a quick update, I have found a work around, having symlinks to the desired folder instead of a shortcut makes it navigate through them as you would in a file explorer.

**Comment by Ross-Patterson** [comment]
This will be fixed in the next release.

**Comment by Ross-Patterson** [comment]
Now available in beta, you can switch to Beta in the app settings.

**Comment by Ross-Patterson** [comment]
Now fully released.
