### ISSUE TITLE
Bug: Incorrect icons on shortcuts pointing at windows settings pages

### ISSUE THREAD

**Issue by cryptikon** [Ross-Patterson/Portals-Desktop-Organization#215]
Portals will not display the correct icon for shortcut files which point to windows settings pages.

Most typically these shortcuts will be assigned the default icon for web-shortcuts, but occasionally they seem to adopt the icon of another shortcut in the same portal folder.

I assume that any URI that does not point to a web resource, but instead some Windows-defined URI, will be assigned an incorrect icon. It does not occur for Windows internal programs which are associated with a file, such as "C:\Windows\System32\appwiz.cpl"

**To Reproduce**
1. open a folder that is currently displayed by portals in Win Explorer
2. Right click -> New -> Shortcut 
3. As location of item type a ms-settings page i.e. "ms-settings:powersleep" and click Next
4. Set any shortcut name
5. Observe the incorrect icon in the portal

**Expected behavior**
Portals should depict the default icon that is assigned to the shortcut by windows or the one set by the user in the file properties.

**Screenshots**

![2023-12-18_13-25-05](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/9078005/60f07678-0c1b-4b35-ac1b-f757508fe387)

**System**
 - OS: Windows 11 23H2
 - Portals Version [3.1.0.2]

**Comment by Ross-Patterson** [comment]
These are .url files. The current logic assumes the .url file has a line for "IconFile"

Here is an example for a steam game:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/9d62d0c0-a5ec-4384-8255-0f597452bf5a)

What I am currently doing is reading the .url file and extracting the "IconFile" path, if that is not found it uses the default browser icon instead.

for ms-settings:powersleep, the content of the url file is:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/b8924daa-e3af-4c60-b7c3-853b641e8e0c)

So I will need to figure out how to get the correct icon.

Will work on it.

**Comment by Ross-Patterson** [comment]
what is the target of the Programs&Features and sound-devices ones?

**Comment by cryptikon** [comment]
Thanks for having a look at it! 

I didn't realize Windows creates .url files instead of .lnk for URIs. I now notice that if you choose a new icon via the file properties and choose the correct one inside the C:\WINDOWS\System32\SHELL32.dll file it shows you the correct IconIndex=314.

![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/9078005/9d32d7e0-58ed-4943-9198-174dd69139c2)

The Icon Index is not properly reflected in the portal though, it just shows some default icon.

![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/9078005/320838f9-b5fb-4240-a902-2d9b2806f633)

At least it's better than the web-shortcut symbol, though.

**Comment by Ross-Patterson** [comment]
Well, at least if you do that I could read the value of IconIndex and pull it from Shell32.dll, and if IconIndex is not found I could use some default icon from Shell32.dll.

Interestingly, on my PC at least (Win 10) - index 314 returns this:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/9d500fe2-885c-4edf-94a2-757728f516dd)

Which ties in correctly as per this:
https://renenyffenegger.ch/development/Windows/PowerShell/examples/WinAPI/ExtractIconEx/shell32.html

I though Shell32.dll icons were consistent - but maybe not :(

**Comment by Ross-Patterson** [comment]
I have released a new version to beta, you can switch to the beta channel in the settings.

Unfortunately I can't get it to pick up the correct icon by default, but now if you set using the Properties and choose the icon explicitly like you explained above, the correct icon will be shown. Which is better than it was at least.

**Comment by cryptikon** [comment]
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/9078005/cefa5a01-1316-498e-b4cb-0517e3dc75ea)

That's a good solution! May not be completely effortless but I only have to do it once for each icon, so it works for me.

Thanks for your hard work!

**Comment by Ross-Patterson** [comment]
So in the latest update I have got it to the stage where I think it is the best I can get.

The "Settings" links URL files have no icon path in them by default, but now when you assign manually from the Properties then refresh the Portal it should properly pull the icon you set now.
