### ISSUE TITLE
Portals overlapping windows

### ISSUE THREAD

**Issue by Krualten** [Ross-Patterson/Portals-Desktop-Organization#216]
**Describe the bug**
The different portals overlay over the different applications instead of remaining as a conventional desktop.

**Expected behavior**
Every portal should stay at the very back of the screen
**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10

**Comment by Ross-Patterson** [comment]
They do stay at the back.

On a very rare occasion some other application may send/launch its window right to the bottom, in this case a simple click on that window will bring it in front again.
