### ISSUE TITLE
FEATURE REQUEST: A setting to collapse all portals when expanding one.  1 open at a time.

### ISSUE THREAD

**Issue by Pearism** [Ross-Patterson/Portals-Desktop-Organization#219]
FEATURE REQUEST: 
A mode / bool / setting to collapse all portals when expanding one.  AKA: 1 portal open at a time.
This isn't that big of a deal but I think it could be quite useful at times.

Thank you Ross!

**Comment by Ross-Patterson** [comment]
This can be fairly easily accommodated.

The auto-expand on hover setting would do this, but i suppose you do not want to do this but instead manually expand collapse?

**Comment by Pearism** [comment]
You are correct sir! How the heck did I miss that!? DOH! 
Thx Ross!
