### ISSUE TITLE
Adapts when monitor situation is changed

### ISSUE THREAD

**Issue by Karachristou** [Ross-Patterson/Portals-Desktop-Organization#22]
**Is your feature request related to a problem? Please describe.**
So my setup is 2 a laptop and a monitor. My monitor is larger than the laptop screen, whenever I unplug the HDMI, to use the laptop on its own, the portals keep the same settings (x,y coordinates/resolution) , so some of them are off the screen cut off, since my monitor is bigger. Also the picture quality is way worse as they keep the resolution of the other screen.

**Describe the solution you'd like**
The portals to adapt when the screen is changed. So like they have a different layout depending on which screen is used. 

**Additional context**
Here you can see what happens when I unplug my HDMI:
![portalerror](https://user-images.githubusercontent.com/22613596/170306682-ca0ed68b-ad06-44ab-8608-f0c2f9f7dc9f.jpg)

**Comment by Ross-Patterson** [comment]
This is something I am aware of, but it is difficult to get it working consistently unfortunately.

It probably won't come soon, but I am trying to get it figured out.

**Comment by Ross-Patterson** [comment]
In v2.1.0.5 I have made some improvements to the positioning system.

Try using the "Relative Positioning" option and set your Portals to be percentages of the screen width, and let me know how it performs.

![image](https://user-images.githubusercontent.com/66630787/180190120-659dabb3-dccb-4249-ac46-0494d0a8ef35.png)

![image](https://user-images.githubusercontent.com/66630787/180190257-980481cb-c842-4ebf-a529-38b632b696ac.png)
