### ISSUE TITLE
Bug: Portals sometimes covering active windows

### ISSUE THREAD

**Issue by smcnabb1** [Ross-Patterson/Portals-Desktop-Organization#223]
**Describe the bug**
Inconsistently, the portals created will act like they have an "always on top" window priority enabled. This makes it cover up all over windows including active ones. In the screenshot below, I am actively typing into chrome search. If there is ever a button in my window that is under the portals, I need to drag my window away from the portal to click on it.

**To Reproduce**
It seems to happen at random times. I am unable to say exactly how to reproduce it but it has occurred multiple times and over multiple restarts.

**Screenshot**
Will update with a picture next time it occurs

**Expected behavior**
Expected behavior is that my active windows are not covered by the portals

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 (Build 22631.3007)
 - Browser: Chrome
 - Version Version 120.0.6099.216 (Official Build) (64-bit)

**Additional context**
I will try to figure out how to replicate it on-demand but this is an issue that occurs pretty frequently for me, even when I disable all other non-microsoft apps on startup.

**Comment by smcnabb1** [comment]
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/93750147/f34f5c19-b1a4-48ae-9281-a930a95dee27)

Sorry for the delay, here is portals covering my web browser even though web browser is my active window.

**Comment by Ross-Patterson** [comment]
Have you activated the Peek function by accident?

Default keyboard shortcut is CTRL+SHIFT+SPACE

**Comment by smcnabb1** [comment]
Hi you are right, Thank you so much,
it was me accidentally enabling peek (CTRL SHIFT SPACE is key combo for non-breaking space)

I did find a tiny bug related to peek -- If peek is enabled, when you uncheck "enable peek", it will disable the hotkey but it doesn't turn peek to off (until a reset)
Steps:
1. Enable peek via hotkey
2. Go into portal settings and uncheck "Enable Peek"
3. Peek mode is still active until application is restarted

Expected behavior:
unchecking enable peek mode box should set peek mode = False/disabled

Again ty :) Awesome product!
