### ISSUE TITLE
Portal window disappears and reappear when clicking on shortcut application. 

### ISSUE THREAD

**Issue by matt9831** [Ross-Patterson/Portals-Desktop-Organization#224]
Using Portals version 3.1.0.2

After starting the first application from the Portals windows , then next time I need to start a different application the Portals window disappear and then appears when I click on the application shortcut the second time. 

The expected behavoir:

1) The Portal windows should not disappear and reappear when clicking on any application.

**Desktop (please complete the following information):**
 - OS: Windows 10 OS  21H2 LTSC
 - Portal version 3.1.0.2

**Comment by Ross-Patterson** [comment]
You mean the portal is flickering on/off. This is related to the "Show Desktop" windows command. See #101 for a workaround.

**Comment by Ross-Patterson** [comment]
No response - closing
