### ISSUE TITLE
Transparent Header has no hitbox

### ISSUE THREAD

**Issue by D1yt** [Ross-Patterson/Portals-Desktop-Organization#225]
**Describe the bug**
When the header is set to transparent color, only the portals title and buttons are used for the hitbox to expand the portal upon hover (when enabled) or mouseclick.

**To Reproduce**
1. Change a portals header to transparent (alpha on 0)
2. Try to expand or close the portal by clicking on the now transparent header
3. You have to aim for the title of the portal

**Expected behavior**
You should be able to expand/hide/hover with the same hitbox of the portals header.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 3.1.0.2

**Comment by Ross-Patterson** [comment]
Unfortunately this is a feature of a windows window and therefore there is nothing I can do.

The only option is to set the transparency to the lowest possible value that isn't zero, which will keep the hitbox.

**Comment by D1yt** [comment]
@Ross-Patterson 
Could you instead remove the option to make a header completely transparent as a fail-safe for normal users? (e.g. minimum alpha)
#01FFFFFF is almost transparent, but has a hitbox.

If someone wants to accept the hitbox-problem for having "true" transparency, there might be a checkbox for them.

**Comment by Ross-Patterson** [comment]
I don't think I will disable it completely, but maybe make a warning appear when the first two values are 00, so that the user is aware of the consequence.
