### ISSUE TITLE
FEATURE REQUEST: Automatically move desktop files to specified Portal

### ISSUE THREAD

**Issue by MRC-eng** [Ross-Patterson/Portals-Desktop-Organization#227]
**Is your feature request related to a problem? Please describe.**
Sometimes files end up on my desktop, and they make it look cluttered until I have time to sort them out. 

**Describe the solution you'd like**
It would be ideal if I could set a folder as the destination for all files that end up in the desktop folder. I would like it if this moving of files would happen immediately upon the file appearing there. It would also be convenient if this happened once a day on a timer, such as at midnight. 

**Describe alternatives you've considered**
Currently I have a portal on my desktop called Unsorted, and I manually move the files there when I don't have time to sort them properly. It works fine, but would be better if it happened automatically.

**Comment by Ross-Patterson** [comment]
I don't plan to implement anything like this right now.

An option would be to write a Powershell or batch script to process them and schedule the script using the Windows Task Scheduler.
