### ISSUE TITLE
BUG: Portals are unresponsive until the Portals app is opened

### ISSUE THREAD

**Issue by MartinJDK** [Ross-Patterson/Portals-Desktop-Organization#228]
It happens regularly, but most often when the pc's screensaver has been active, and I come back and login. Then all the portals are unresponsive. It doesn't matter whether the portals are opened or closed, but nothing happens when I click on the shortcuts in the portals or the portal header to open/close.
Double-clicking to hide/show portals works but does not make the portals responsive when they reappear.
As soon as I open the Portal app with the listing of portals, everything starts working again.

**To Reproduce**
Steps to reproduce the behavior that works 9 out of 10 times with me:
1. Leave the computer running and wait for the screen saver to activate. Mine is configured to ask for login after being activated.
2. Go to desktop and try to open/close portals or use any of their shortcuts.
3. They are now unresponsive

**Expected behavior**
That the portals keep being responsive after logging back on

**Desktop (please complete the following information):**
 - OS: Windows 10 and 11, both 64bit fully updated.
 - Portals version: 3.1.0.2

**Comment by Ross-Patterson** [comment]
Can you try in the latest beta version? You can switch the beta channel in the settings.

**Comment by MartinJDK** [comment]
Hello.
Sorry it has taken me a while to get back. It looks like the problem is
fixed, I haven't experienced it since I updated to the beta 4 days ago.
👍Thank you!

Med venlig hilsen / Best regards
Martin Johansen



Den søn. 28. jan. 2024 kl. 23.59 skrev Ross Patterson <
***@***.***>:

**Comment by Ross-Patterson** [comment]
Great, glad its sorted.
