### ISSUE TITLE
Feature request: set default portal folder location in AppData

### ISSUE THREAD

**Issue by SvardXI** [Ross-Patterson/Portals-Desktop-Organization#23]
**Is your feature request related to a problem? Please describe.**
I find it annoying that the default location of the folder is on the desktop.

**Describe the solution you'd like**
What the portal ought to do is create that folder inside the user's AppData (Local or Roaming) by default.

**Comment by Ross-Patterson** [comment]
Hi, you already have the option to choose where portal folders get created:
![image](https://user-images.githubusercontent.com/66630787/170966836-df62f787-5030-4c49-b25d-8866bff9d2da.png)

Just set it to your AppData folder.
