### ISSUE TITLE
Ability to place the portal window at the top

### ISSUE THREAD

**Issue by gmdatnvh** [Ross-Patterson/Portals-Desktop-Organization#232]
**Is your feature request related to a problem? Please describe.**

When I select a title or mouse overlap, then the portal window to come to the front.
When multiple windows cover the portal window, need to shrink or minimize the other windows one by one to view the contents of the portal window. A function to bring the portal window to the top is necessary.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ross-Patterson** [comment]
Check out this setting:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/c8219f1a-c73b-4adf-b0e0-75db43d820e0)

**Comment by gmdatnvh** [comment]
Thanks for quick reply.
However, maybe that function is not working at Win11.
My Desktop and Notebook are not working.

**Comment by Dark-Peace** [comment]
@gmdatnvh maybe I'm not sure I understood your post but the software WindowTop might help you

**Comment by Ross-Patterson** [comment]
Ahh after reading @Dark-Peace comment, I think you want it to come to the very top of ALL windows. The app has nothing like this on click or mouse-over, but there is a setting called PEEK which you can bind to a keyboard shortcut.

![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/505fb784-0365-429b-bfd0-2a8b230ae58a)

Or use @Dark-Peace suggestion of WindowTop software which might suit your needs.

**Comment by gmdatnvh** [comment]
Sorry for being late in checking answer.
The feature I wanted was WindowTop.
I understand that this is a feature that has not yet been implemented and I will try to find another way.
Thanks !
