### ISSUE TITLE
BUG: New 3.2.0.1 update broke everything

### ISSUE THREAD

**Issue by Dark-Peace** [Ross-Patterson/Portals-Desktop-Organization#233]
**Describe the bug**
Bug 1 : icons not showing for **some** portals
![EB2HFhEafB](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/74102789/6470d99c-9e1b-495f-a262-cdb2087c2c70)
After reinstalling the update and restarting, the icons finally show.
Bug 2 : icon names disappeared for grid view. And I can't find the option to bring them back
Bug 3 : icons are wrong. Multiple icons accross multiple portals are totally wrong, they're switched with the icon of another app.
![cvvvXhoXLj](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/74102789/21e5513e-ab0e-42c0-8d1e-9d90f9b28e12)

**To Reproduce**
Install 3.2.0.1

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by Ross-Patterson** [comment]
@Dark-Peace - all working ok now?

**Comment by Dark-Peace** [comment]
Hi! So sorry I haven't been able to get back to you. I've been solving bug reports in my own projects, haha

Yes, those were the solutions ! Thank you

**Comment by Ross-Patterson** [comment]
No worries at all! Glad it's working ok now.
