### ISSUE TITLE
BUG: High GPU Usage?!  - Portals Version [3.2.0.1]

### ISSUE THREAD

**Issue by DarkAoRaidenX** [Ross-Patterson/Portals-Desktop-Organization#234]
**Describe the bug**
Notice in the latest update GPU is High. 

Don't remember seeing or having that issue before?

Does Portals need to use the GPU that much??

Thought it was because OBS was up for some reason, but still High Usage after it's closed.

**To Reproduce**
Open Portals

**Expected behavior**
Not use GPU/High GPU

**Desktop (please complete the following information):**
 - OS: Windows 10

![01 29 2024 11 51 01](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/101914106/3e78ca9e-6bcb-4add-aac2-b2615ace8bd2)
![01 29 2024 11 59 38](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/101914106/776ebd5c-5393-45ee-a3d2-cded044b1750)

**Comment by Ross-Patterson** [comment]
I am about to release beta 3.2.0.2 which will fix this.

Turns out the spinning loading icon I introduced for some reason has crazy GPU usage on _some_ PCs, must be a bug in the framework.

I will have to come up with something else.

**Comment by Ross-Patterson** [comment]
3.2.0.2 released - fixing GPU issue
