### ISSUE TITLE
last update all steam and ubisoft connect games defaulted to one icon but in the properties you can see the right one is still there and in the file explorer icons are still as they should be only on the destop it grabbed the first icon and applied it to all the ather games/apps

### ISSUE THREAD

**Issue by Silenceikillyou** [Ross-Patterson/Portals-Desktop-Organization#235]

**Comment by Silenceikillyou** [comment]
version 3.2.0.3 on Widows 10 Version 22H2

**Comment by Ross-Patterson** [comment]
What file extension are they? If they are .lnk or.url files they should be ok.

Anyway, go into the settings and turn off: "Cache icons Per File Extension"
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/c3573ab6-c067-46e5-bb29-6ddc967b6d47)

**Comment by Silenceikillyou** [comment]
i found something odd, i trided manualy assigning icons withing the portals interface and if i selected .ink file even after refresh, no change but when instead of the .ink file i would use the games .exe file for the icon it would work after refresh so i just manualy changed them. I'll change the settings, looks like the last update didnt like the shortcuts that were url (Steamapp) but those that pointed to .exe files were left untouched

**Comment by Silenceikillyou** [comment]
btw thanks for the super fast response

**Comment by Ross-Patterson** [comment]
I will check out the URL ones and see what is happening.

**Comment by Silenceikillyou** [comment]
also reinstalling Portals and restarting pc did not help but right now i fixed it by manualy assigning .exe files for icons so its not a problem for me right now, and also i tried uninstalling the game that had the icon that was overwriting the right ones and it just jumped to the next steam game and all changed to the next one. Lastly it could potetialy be something on my end since this windows instalation is old and went trought 1 HDD and 2 SSDs changes by cloning the drive and multiple HW changes from intel to AMD CPU and from nvidia to AMD GPU so i might be an edge case

**Comment by Ross-Patterson** [comment]
Did you uncheck the setting to cache icons per file extension? That should fix it.

**Comment by Silenceikillyou** [comment]
sadly i cant reproduce the issue because before your first reply i fixed it one by one as i described but i unchecked the setting so i will close it as solved. And if this were to happen in the future i'll report it, the only way to reproduce it would be to update, so if there is no report with the next update rollout then there is no bug just a need to tweak the settig.
