### ISSUE TITLE
BUG: Steam Icons Unifying After Update

### ISSUE THREAD

**Issue by PricklyPorcupine** [Ross-Patterson/Portals-Desktop-Organization#237]
**Describe the bug**
After installing the latest update, all desktop Steam icons changed to a single icon, seemingly selected from a game at random, i.e. everything was represented by the same image. Any icons not related to Steam were unaffected. After reverting to the previous version, all icons were restored to their correct appearance.

**To Reproduce**
1. Install latest version with Steam icons on desktop.

**Expected behavior**
No change in icon appearance.

**Screenshots**
Didn't think to take one.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22H2 for x64

**Additional context**
None.

**Comment by Ross-Patterson** [comment]
In the settings (App Settings Section) there is a new setting called "Cache icons per file type", turn this off and it will be fixed.
