### ISSUE TITLE
Icons all of the sudden have the same pictogram

### ISSUE THREAD

**Issue by EertNL** [Ross-Patterson/Portals-Desktop-Organization#239]
After the last automated update, some of my gaming items have the same, random pictogram of another game....
Inside the actual folder, the pictograms are normal.

The afacted games seem to be only steam and 1 ubisoft game. What they share in common that all use links, like: 'steam://rungameid/2155180' & 'uplay://launch/3037/0'

However, some steam games do have the right pictogram. Like Catan VR or Angry Birds VR.

![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/41252676/c504b36b-4aa9-4806-97b4-d3a12d0ffdb8)

![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/41252676/8ee6621f-ae8e-43ff-8749-8d474f0b9460)

**Comment by Ross-Patterson** [comment]
What file extension are they? Can you open one of them in notepad and show me the contents?

Fix is in the settings:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/3777ae0c-7a7e-4246-bd74-55b2b1d5632e)

**Comment by EertNL** [comment]
Hello Ross,

Thanks for your reply. These files do not have extensions. I also can't open them in notepad. They seem to be URL's.

![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/41252676/78c397a0-5bc8-4c21-987c-75cf3bde4231)

Your fix worked. Thanks a lot.

**Comment by Ross-Patterson** [comment]
Glad the fix worked.

**Comment by Ross-Patterson** [comment]
If you drag the icon into notepad it will open, I need to see the content, this would really help me get to the bottom of whats happening.

Example:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/d532ad61-52c6-49f7-8120-bd201da99bda)

**Comment by EertNL** [comment]
It looks the same as your example.

**Comment by zeddwolffgaming** [comment]
I also have this issue, how do I open the settings menu? When opening portals, I just get a notification that it is already running

**Comment by Ross-Patterson** [comment]
Click the icon in the task bar

**Comment by Ross-Patterson** [comment]
Fixed released (v3.2.1.0)
