### ISSUE TITLE
Feature request: allow image-based theming for each portal

### ISSUE THREAD

**Issue by SvardXI** [Ross-Patterson/Portals-Desktop-Organization#24]
**Is your feature request related to a problem? Please describe.**
Just a feature that could be neat for additional customization.

**Describe the solution you'd like**
It would be great to allow users to be able to change the appearance of their portals with PNG or JPEG images-- one for the title bar, and one for the contents background. There should also be the option to stretch, tile or position the image. I realize this may come at the cost of extra system resources, but there could always be a warning for such if that ends up being the case.

**Comment by Ross-Patterson** [comment]
Hi There,
I have included this feature in v3.0.0.0 which I have made available for early access here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/107

Thanks!

**Comment by SvardXI** [comment]
Looks great so far! Thank you for taking this feature request seriously! Any current plans to expand supported formats to JPEG, or dare I say, GIF, even, and enable individual overrides?

**Comment by Ross-Patterson** [comment]
Maybe JPEG. Definitely not GIF or Opacity at this time.
