### ISSUE TITLE
Problem with icon highlighting on transparent background

### ISSUE THREAD

**Issue by PrzemekkkYT** [Ross-Patterson/Portals-Desktop-Organization#240]
**Describe the bug**
Some time ago I noticed a problem with highlighting/selecting icons on portals while content background is set to transparent (alpha: 0)
It can also mess up scrolling in the portal.

**To Reproduce**
1. Go to Customization of any Portal
2. Expand Portal Content
3. Scroll down to Background Color
4. Set Background Color to transparent by applying alpha value to 0
5. You'll see the problem while hovering over icons on this portal. Now it's a trouble to select any icon

**Expected behavior**
You should be able to select any icon easily like with any other background setting

**Screenshots**
With Alpha set to 0 (transparent) on content background:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/42695398/f1c3b328-c68c-4054-943f-64e6ede01a6a)
video:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/42695398/3ae83374-758a-4f3f-bb8b-628109f76ab5

With Alpha set to anything other than 0 (not fully transparent) on content background (I used 1):
![obraz](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/42695398/c58b43fe-4dc6-4ca0-9f77-dc8489b34081)
video:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/42695398/7efcc313-f43b-49dd-93bb-09a91093b929

**Desktop (please complete the following information):**
 - OS: Windows 10 Education 22H2
 - Version: Current: 3.2.1.0, Happening at least since: 3.0.2.2

**Comment by Ross-Patterson** [comment]
Hi @PrzemekkkYT,
This is because unfortunately windows does not register clicks on a window with a fully transparent background, so it is out of my control.

The only option is to set the background to the lowest possible value that is not 0.

**Comment by PrzemekkkYT** [comment]
Hello Ross,
Thank you for clarification. So it's just Windows being Windows. Now it's totally understandable.
Have a great day.
