### ISSUE TITLE
HELP: app names on multilines

### ISSUE THREAD

**Issue by Dark-Peace** [Ross-Patterson/Portals-Desktop-Organization#241]
Version: 3.2.1.0

Description:
Seems since the last update, it's not displaying the app names on multiple lines. Honestly I'm not sure how it was displaying before, but you can see on my screenshot that there's a space between the bottom row of apps and the bottom limit of the portal, and I think it's before it was displaying text on 2 lines before and not anymore so it takes less vertical space. I can't find a setting to make it display on 2 lines anymore, am I missing something ?

![6JpI4cAPYd](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/74102789/d30ecdc0-9e85-472d-98cf-16bc204107b1)

**Comment by Ross-Patterson** [comment]
There is a setting in the settings for "Item Text Height" (under "Portal Content" near the bottom), increase it and you should be good:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/aa81b604-c8aa-45c5-99ea-e9b8a0073939)

**Comment by Ross-Patterson** [comment]
Default is 35, which makes about 2 lines, not sure how yours defaulted to one line.

**Comment by Dark-Peace** [comment]
Ok thanks, it was related to my last bug report then, when text height had reset to 0. I only had put it back at 11
