### ISSUE TITLE
Excel icon is no longer correct in 3.2.1.0

### ISSUE THREAD

**Issue by wasted0101** [Ross-Patterson/Portals-Desktop-Organization#242]
Immediately following the latest update the icon for an Excel spreadsheet changed to the attached icon

 - OS: Windows 10

![excel](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/67345128/6ea4dbaa-51fa-4cfc-bac8-a9a563bfc64d)

**Comment by Ross-Patterson** [comment]
This icon means the app failed to receive an icon from Windows. Try opening up the menu on the portal, (top right by default) then click "Refresh", see if that pulls it correctly.

Sometimes its just an intermittent issue.

**Comment by Ross-Patterson** [comment]
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/8c6df5a8-79a4-4ce8-848d-d9c3ca7087f1)

**Comment by wasted0101** [comment]
That resolved the issue. Sorry to panicOn Feb 5, 2024, at 7:38 AM, Ross Patterson ***@***.***> wrote:﻿
This icon means the app failed to receive an icon from Windows. Try opening up the menu on the portal, (top right by default) then click "Refresh", see if that pulls it correctly.
Sometimes its just an intermittent issue.
