### ISSUE TITLE
Hide icon text until hover

### ISSUE THREAD

**Issue by rconstantine** [Ross-Patterson/Portals-Desktop-Organization#245]
Like the title says, would it be possible to hide the text of the icons and have them only as tooltips? I think Stardock has this on one or more of their apps. I only have a couple of icons which are hard to distinguish between, so for the most part the text is unnecessary.

**Comment by Ross-Patterson** [comment]
In the settings you can make the item text height 0, tooltips will still work.

![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/81434d90-f569-4e18-93a0-1944d44e2db7)

**Comment by rconstantine** [comment]
Doh! You're right, of course. Sorry for missing that!
