### ISSUE TITLE
Icon overlay appears when icons are on "very small" size

### ISSUE THREAD

**Issue by Dark-Peace** [Ross-Patterson/Portals-Desktop-Organization#246]
Yep, it's me again.

**Describe the bug**
When the icons are on "small" with overlay off, the shortcun icon doesn't appear on the app icon, but when I switch to very small, the shortcut icon shows, even though the overlay option is still off.

**Screenshots**
![Portals_xIGIKdGhld](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/74102789/027ae57b-092d-49f4-8222-d3288f0efe23)

**Desktop (please complete the following information):**
 - OS: Win 10

**Comment by Ross-Patterson** [comment]
Good find - I will fix that.

**Comment by Ross-Patterson** [comment]
This is fixed in the latest release.
