### ISSUE TITLE
BUG: Can't Drag and Drop Shortcuts Into Portals

### ISSUE THREAD

**Issue by snowfi6916** [Ross-Patterson/Portals-Desktop-Organization#247]
I have my portals set to auto expand on hover. When I have a new shortcut I want to add to the portal, I should be able to drag and drop the shortcut into the portal, but I am getting a "not allowed" icon when I try to do it. I can drag and drop the shortcuts back on to the desktop, but not the other way around. I have attempted rebooting the Portals app multiple times with no change.

**To Reproduce**
1. Have a new shortcut on the main desktop.
2. Attempt to drag and drop the shortcut into a portal.
3. See mouse icon telling you that it is not allowed.

**Expected behavior**
I should be able to drag and drop new icons/shortcuts into my portals.

**Screenshots**
![NVIDIA_Share_qhqR7sbE4O](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/30598385/9704445d-2e3d-4b33-8aa0-259aa51cbf6d)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version Portals v3.2.1.0

**Comment by Ross-Patterson** [comment]
Hi, usually this happens when Portals is running in an elevated state i.e. admin. So explorer (running as non-admin) cannot drop files on the Portals.

Restart portals as normal non-elevated and it should work fine.

**Comment by snowfi6916** [comment]
> Hi, usually this happens when Portals is running in an elevated state i.e. admin. So explorer (running as non-admin) cannot drop files on the Portals.
> 
> Restart portals as normal non-elevated and it should work fine.

I'm not sure how the app was started as admin. I don't have the "Run As Administrator" option checked on the shortcut.

![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/30598385/9c7be579-558a-41f7-bfbf-59cbf126e08c)

I tried stopping and starting Portals from the Start Menu and the drag and drop works again. Thanks!
