### ISSUE TITLE
Wrong link to installer v.3.2.1.0 on Portals website

### ISSUE THREAD

**Issue by Max1234-Ita** [Ross-Patterson/Portals-Desktop-Organization#248]
This morning I went to portals-app.com and found that new version 3.2.1.0 was advertised.
However, if I click the Download button, it still points to the previous version (3.2.0.3).

Thanks for your work!

**Comment by Ross-Patterson** [comment]
Oops that's for letting me know, it's much appreciated!

Now fixed.

**Comment by Max1234-Ita** [comment]
Thank you so much! :-)
