### ISSUE TITLE
Send new icons to folder/portal option - Portal Behavior 

### ISSUE THREAD

**Issue by aminoginji** [Ross-Patterson/Portals-Desktop-Organization#249]
**Is your feature request related to a problem? Please describe.**
Unless you place portals to the right of the desktop new icons go under portals

**Describe the solution you'd like**
Add an option to portal behavior to send all new icons to selected portal/folder

**Describe alternatives you've considered**
Move portals to weird spots

**Comment by Ross-Patterson** [comment]
This will not be implemented unfortunately.

I will not manipulate and move users files without their explicit action doing so.

You could write your own batch/powershell script that could potentially do this then use the windows task scheduler to run it every 5mins or something.
