### ISSUE TITLE
Feature request: Content preview for folders (maybe images and txt files, too) when hovering

### ISSUE THREAD

**Issue by SvardXI** [Ross-Patterson/Portals-Desktop-Organization#25]
**Describe the solution you'd like**
Maybe something more in-line with a long-term goal, but it would be nice to be able to hover one's cursor over certain objects, and for a pane to appear that shows the contents of a folder and other certain types of objects.

**Additional context**
Preview sizes should be customizable, but should default to no larger than 256x256. Folder preview panes should allow for scrolling, and should also apply to folder shortcuts. 

Another option on the folder part is to create a Windows style menu (a la pre-Windows Vista) that allows users to go deeper into a directory.

**Comment by Ross-Patterson** [comment]
I don't think this will happen any time soon, but I will keep it in the backburner anyway!

**Comment by Ross-Patterson** [comment]
Someone raised #48, turns out there is already software that does this, so I will not add this. What I will be doing is adding support for Quicklook and Seer - so you can get file previews by using those softwares.

**Comment by SvardXI** [comment]
Great alternative solution, and probably much easier on your part. Thank you!
