### ISSUE TITLE
Portals v.3.2.1 not started on a Windows 10 machine

### ISSUE THREAD

**Issue by dnsjss** [Ross-Patterson/Portals-Desktop-Organization#255]
Portals v.3.2.1 not started on a Windows 10 machine.
After a double click nothing happens. Even in the task manager the process of Portals not available.

A previous version of Portals worked fine on the same machine and under the same conditions.

Take a look at the attached screen recording.

https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/160719848/3d838172-f8c3-4972-ae12-45686f687c74

**Comment by Ross-Patterson** [comment]
Can you go to:
C:\Users\username\AppData\Local\Portals\

And see if any log files are being generated?

**Comment by Ross-Patterson** [comment]
Closing for now due to no response, please re-open and provide extra info requested.
