### ISSUE TITLE
"Auto Expand on Hover" doesn't work on Override

### ISSUE THREAD

**Issue by Kapharnaum** [Ross-Patterson/Portals-Desktop-Organization#258]
**Describe the bug**
I have "Auto Expand on Hover" off.
I customize some of my portals with "Auto Expand on Hover" on.
When I put my mouse over the title, nothing happens.

**Expected behavior**
My portal is minimized and should expand

**Screenshots**
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/16528108/02736480-ac41-4ee4-bde1-63749de073c6)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Ross-Patterson** [comment]
You have checked the box to override the value, but then not actually turned it on.

The check box on the left is still unchecked.
