### ISSUE TITLE
Feature request: Link already existing folders to a portal

### ISSUE THREAD

**Issue by SvardXI** [Ross-Patterson/Portals-Desktop-Organization#26]
**Describe the solution you'd like**
It would be great if we could link already existing folders to a new or existing portal. This would especially be great for users who are constantly working in other directories, such as office workers, programmers, modders and artists.

**Comment by Ross-Patterson** [comment]
This is already there:
![image](https://user-images.githubusercontent.com/66630787/170967326-b44669a0-e774-4741-89ac-a59fb0cec62b.png)

Maybe I have misunderstood, let me know if I have.

**Comment by SvardXI** [comment]
Ah, no. I see it now. It seems I was having a blind moment. Thank you for pointing this out.
