### ISSUE TITLE
BUG: Program crashes on launch

### ISSUE THREAD

**Issue by sshockley** [Ross-Patterson/Portals-Desktop-Organization#262]
**Describe the bug**
The program immediately crashes on launch.

**To Reproduce**
Installed version 3.2.1.  Open the program from Start menu, nothing appears to happen

**Expected behavior**
The program should open?  I haven't seen it work yet.

**Desktop (please complete the following information):**
 - OS: Windows Server 2019 (1809/17763)
 - Browser Firefox
 - Version 123.0.1

**Additional context**
Contents of session log:
```
Portals Session Log
VERSION=3.2.1.0
OS=Microsoft Windows NT 6.2.9200.0
64 Bit OS=True

08/03/2024 21:46:22:864	INFO	Portals Launched...
08/03/2024 21:46:22:864	INFO	Got 0 args on startup
08/03/2024 21:46:22:864	INFO	Command line args=
08/03/2024 21:46:22:864	INFO	RELEASE
08/03/2024 21:46:22:864	INFO	Checking app theme...
```

From Windows event log:
```
Application: Portals.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Portals.EntryPoint.Main(System.String[])
```
and
```
Faulting application name: Portals.exe, version: 3.2.1.0, time stamp: 0xb7aa9971
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ff82bb55c96
Faulting process id: 0x1104
Faulting application start time: 0x01da71cca59fea9a
Faulting application path: C:\Program Files\Portals\Portals.exe
Faulting module path: unknown
Report Id: fdc94e38-1545-44e6-ab3a-06a12db55e87
Faulting package full name: 
Faulting package-relative application ID: 
```
Let me know if you need any other info, thanks.

**Comment by Ross-Patterson** [comment]
Thanks for all of the detail, this tells me exactly what is happening and how I can fix it.

I can send you a test build once complete to try out?

**Comment by Ross-Patterson** [comment]
This crash should no longer happen in v3.3.0.9
