### ISSUE TITLE
Hide on double click, and desktop icons

### ISSUE THREAD

**Issue by CraftyCNC** [Ross-Patterson/Portals-Desktop-Organization#263]
If 'hide on double click of desktop' is enabled, it hides when also clicking on desktop icons

Try to recognize icons as 'not the desktop' and don't hide the Portals.

I don't have any alternatives, other than having zero desktop icons.  I would like to maintain just a few.

**Comment by Ross-Patterson** [comment]
Yes this happens when you have your desktop set to a slideshow - will be fixed in next update.

**Comment by Ross-Patterson** [comment]
This is fixed in the latest version which is available for early testing here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/305

If you want to test it, please read carefully before installing, so you don't lose any of your settings if something goes wrong.

**Comment by Ross-Patterson** [comment]
This is fixed in the latest release.
