### ISSUE TITLE
Corner Radius not working / Not transparent but black

### ISSUE THREAD

**Issue by Nydid** [Ross-Patterson/Portals-Desktop-Organization#265]
**Describe the bug**
When I try to change the corner radius on a portal, it curves the corners but the background is not transparent but black.

**To Reproduce**
1. Go to 'Customize Portal'
2. Click on 'Portal Window'
3. Increase 'Corner Radius'

**Expected behavior**
A corner radius to be respected and for the removed part to be transparent

**Screenshots**
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/30263820/9608ed82-1406-49b9-a168-7811ebd3cee2)

**Desktop (please complete the following information):**
 - OS: Windows 11 64bit
 - Browser: Floorp 
 - Version: 11.10.5

**Smartphone (please complete the following information):**
 - Device: Oneplus 7 Pro
 - OS: crDroid, Android 13
 - Browser: Bromite
 - Version: 108.0.5359.156

**Additional context**
I have a AMD 6700xt GPU and 5700x CPU, with latest drivers.

**Comment by Ross-Patterson** [comment]
Does your PC have another integrated graphics that you could try running the app on? To try and rule out a graphics card issue.

**Comment by Nydid** [comment]
FIX: This issue was related to how Mica for Everyone handles transparency. Disable the rules on Portals fixes the transparency issues.
