### ISSUE TITLE
Bugs when modified portal windows

### ISSUE THREAD

**Issue by Ace-Kyle** [Ross-Patterson/Portals-Desktop-Organization#27]
**describe issue**

1. custom the default templates in settings = OK.
2. custom portal that has been created on desktop = ISSUE.

- I do change some context of the portal, such as: changing the color of the content, changing the content foreground area color,..and so on.
- I expect the chosen color bar to be normal but it usually **doesn't appear** and starts some crashes, lagging because **it causes memory to get higher and higher until the overflow of RAM in seconds**.

**the laptop I use:**

- MSI Modern 15.
- chip Ryzen 7 5700U.
- RAM 8GB.
- Windows 11 Pro.
Sorry for my bad English.

**Comment by Ross-Patterson** [comment]
@Ace-Kyle  if you go to:
C:\Users%USERNAME%\AppData\Local\Portals\crashlogs

Hopefully there will be a crash log there:

Additionally, you can create a file called "debugmode.yes" in:
C:\Users%USERNAME%\AppData\Local\Portals\

This will turn on some debug stuff, but also create some more log files in:
C:\Users%USERNAME%\AppData\Local\Portals\logs

If you could replicate and send both logs if possible I can hopefully see whats happening.

Thanks,
Ross

**Comment by Ross-Patterson** [comment]
Closed due to no response.
