### ISSUE TITLE
blank desktop

### ISSUE THREAD

**Issue by aedui152** [Ross-Patterson/Portals-Desktop-Organization#273]
**Describe the bug**
Have been using the app fine and really like it.  Last three days every time the PC boots the portals appear then disappear and I can't make them return 
**To Reproduce**
Steps to reproduce the behaviour:
1 Boot PC
2 Portals load then disappear
3 run portals app
4 portals appear briefly then disappear

**Expected behaviour**
Expect portals to load and be visible on the desktop

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 232H2 (OS build 22631.3374)

**Additional context**

**Comment by Ross-Patterson** [comment]
Open up the Home window and check if they are hidden, and also check their X,Y positions to see what is going on, this will help us understand what is going on.

**Comment by Ross-Patterson** [comment]
Closing due to no response
