### ISSUE TITLE
FEATURE REQUEST: Auto-Refresh or at least add F5 hotkey to refresh

### ISSUE THREAD

**Issue by imagicalFantasy** [Ross-Patterson/Portals-Desktop-Organization#275]
**Is your feature request related to a problem? Please describe.**
Currently, when folders change from external software, icons of the portal isn't refreshed.

**Describe the solution you'd like**
A way to enable "auto-refresh" when portal contain change or at least an hotkey to render refresh

**Describe alternatives you've considered**
Manualy trigger refresh with mouse clicking on the menu btn and on refresh option,

**Additional context**
It's anoying to do that alway, so until it will be fixed, I will return to the old commercial alternative.

**Comment by Ross-Patterson** [comment]
F5 hotkey can be added easily.

I am already detecting when files in a portal itself change, but I am not watching subfolders for changes - this would be a lot of extra overhead and would have a performance impact more than likely.

**Comment by Ross-Patterson** [comment]
F5 shortcut is added in the latest version which is available for early testing here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/305

If you want to test it, please read carefully before installing, so you don't lose any of your settings if something goes wrong.

**Comment by Ross-Patterson** [comment]
This is added in the latest release.
