### ISSUE TITLE
Harmonize UI

### ISSUE THREAD

**Issue by Mittlebenskrise** [Ross-Patterson/Portals-Desktop-Organization#278]
**Is your feature request related to a problem? Please describe.**
In "Settings"-"Home" the portals are listed with several columns for size and position. If you click on "Layouts" and on the info icon for a layout, you basically get the same screen. However, the columns have a different order. So, if you try to manually copy certain settings, you always mess things up.

**Describe the solution you'd like**
Please harmonize the information on both screens.

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/5927536/0e94429d-bb69-4e79-91d4-b90792483f4f)
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/5927536/f5d125aa-36f1-4186-a0d5-d33047fb4d35)

**Comment by Ross-Patterson** [comment]
This is fixed in the latest release.
