### ISSUE TITLE
Custom Order: Edit order does not work

### ISSUE THREAD

**Issue by gojoy33** [Ross-Patterson/Portals-Desktop-Organization#279]
Rearranging icons does not work:
When I click on EDIT ORDER, every icon I try to move is marked as locked.

UPDATE: Edit order works on my notebook, but not on my desktop!
Both Windows 10. 
I uninstalled and reinstalled Portals, I resetted all settings and reimported them, but edit order still not working on my desktop.
Any idea why?

**Comment by Ross-Patterson** [comment]
Try clearing out the following folder:
C:\Users\<username>\AppData\Local\Portals

Then try again.

(You can keep license.ptl if you want so you dont have to re-enter your license key)

**Comment by gojoy33** [comment]
> Try clearing out the following folder: C:\Users<username>\AppData\Local\Portals
> 
> Then try again.
> 
> (You can keep license.ptl if you want so you dont have to re-enter your license key)

Thanks - I tried, but problem resists, but only on my desktop.
I think it is a problem of the windows installation on my desktop pc, on my notebook no problem.
If it could help you to investigate the problem, I could send you a little video of the strange behaviour.

**Comment by gojoy33** [comment]
ISSUE SOLVED:
My NTUSER.DAT was rather big and has caused the problem.
I made a new local account (Administrator) and partially copied the data from the old user account (C:\users\olduser)
Maybe other issues here have the same reason and could be solved by a fresh user account.
