### ISSUE TITLE
BUG: When relaunching, folder priority does not apply until you edit the sort order

### ISSUE THREAD

**Issue by rinyafii** [Ross-Patterson/Portals-Desktop-Organization#281]
**Describe the bug**
If you have the folder priority in a Portal as First/Last and then relaunch Portals, the priority will be set in the Sort Order menu but not actually applied to the list. You can edit any sort order setting to get it to apply.

**To Reproduce**
1. Set a Portals Folder Priority to First/Last
2. Close and Re-Open Portals
3. Order is not what was chosen

**Expected behavior**
Order is what you chose

**Screenshots**
https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/36645011/add0a202-b9a0-41f4-859b-34731b2f976b

**OS**
Windows 11 Insider Dev 26090

**Comment by Ross-Patterson** [comment]
Thanks for the recording, it really helps, I will get that fixed

**Comment by Ross-Patterson** [comment]
This should be fixed in the latest release.
