### ISSUE TITLE
Incorrect behaviour running executables from a portal!?...

### ISSUE THREAD

**Issue by dhf-esi** [Ross-Patterson/Portals-Desktop-Organization#283]
It has taken me a while to work out why I'm having this problem.  
When I start an application by double clicking on an .exe file (for instance) in a portal window, I sometimes get strange behaviour.  This usually takes the form of "missing" .dll files that are clearly present in the selected folder.  When I use Portals to open Windows Explorer in that same folder, and double-click on the executable from there, everything works.

It now seems to me that Portals is invoking the executable using Windows\System32 as the working directory, breaking any app that uses paths relative to the working directory.

It's not a deal-breaker now that I know what is going on, but it is an unnecessary annoyance.  Others might not work it out.

**Comment by Ross-Patterson** [comment]
thanks for this - I will definitely check on the working directory apps are started with

**Comment by Ross-Patterson** [comment]
This is fixed in the latest version which is available for early testing here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/305

If you want to test it, please read carefully before installing, so you don't lose any of your settings if something goes wrong.

**Comment by Ross-Patterson** [comment]
This is fixed in the latest release.
