### ISSUE TITLE
URL Icons not fetched at all

### ISSUE THREAD

**Issue by wstanzl** [Ross-Patterson/Portals-Desktop-Organization#285]
Portals Version 3.2.1.0 prod
does not show any URL icons.

This is contrary to release-notes_beta_v3-2-0-0.txt which mentioned
Changes in v3.2.0.1:
> Icons for URL files will fetch better. 

Going directly with explorer.exe to the portal folder will show the icon in file properties of .url

**Comment by wstanzl** [comment]
Maybe the option "Cache Icons Per File Extension" should never consider .url files (and .exe, .lnk and the like)

**Comment by wstanzl** [comment]
Sure, thanks for being responsive.
BTW, I am on Windows 10

The Shortcut was originally created by dragging from Firefox onto the Desktop.

The URL Shortcut Name:
YiPs Wiki (i powered) - RPG-2-PASE.URL

The Shortcut Contents:
```
[InternetShortcut]
URL=http://yips.idevcloud.com/wiki/index.php/PASE/RPG-2-PASE
IDList=
HotKey=0
IconFile=C:\Users\Willi\AppData\Local\Mozilla\Firefox\Profiles\bnzcggdr.default-release\shortcutCache\IsEU92g7iuVckL15Ff6mbQ==.ico
IconIndex=0
```

This shortcut was a URL shortcut taken from the original desktop.

The .ico exists in "C:\Users\Willi\AppData\Local\Mozilla\Firefox\Profiles\bnzcggdr.default-release\shortcutCache\IsEU92g7iuVckL15Ff6mbQ==.ico"

And can be successfully viewed, for example with IrfanView.

**Comment by wstanzl** [comment]
I think i found out what the problem is:
**Equal Signs in the .ico Filename cause the icon not to display.**

**Comment by Ross-Patterson** [comment]
Nice find - not sure if there is anything I can do about that - but I will have a look

**Comment by wstanzl** [comment]
Hope this finds its way in the next production builld - 
Firefox very often puts == at the end of the icon cache filename.

**Comment by Ross-Patterson** [comment]
This is fixed in the latest version which is available for early testing here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/305

If you want to test it, please read carefully before installing, so you don't lose any of your settings if something goes wrong.

**Comment by Ross-Patterson** [comment]
This is fixed in the latest release.
