### ISSUE TITLE
Portals keeps crashing

### ISSUE THREAD

**Issue by fqueirozf** [Ross-Patterson/Portals-Desktop-Organization#286]
**Describe the bug**
Portals keeps crashing when hovering over any portal.

**To Reproduce**
1. Try to hover over any portal.
2. Error message appears, Potals crashes.

**Expected behavior**
Expected behaviour would be using it without crashing seconds after opened.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.2.1.0

**Additional context**
One of the numerous error log shows:

"Version: 3.2.1.0
Event Source: AppDomain.CurrentDomain.UnhandledException
Internet Connected: yes

Exception Source: WindowsBase

Message:
The window identifier is invalid

StackTrace:
   em MS.Win32.UnsafeNativeMethods.GetMessageW(MSG& msg, HandleRef hWnd, Int32 uMsgFilterMin, Int32 uMsgFilterMax)
   em System.Windows.Threading.Dispatcher.GetMessage(MSG& msg, IntPtr hwnd, Int32 minMessage, Int32 maxMessage)
   em System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   em System.Windows.Application.RunDispatcher(Object ignore)
   em System.Windows.Application.RunInternal(Window window)
   em Portals.EntryPoint.Main(String[] args)

TargetSite:
Boolean GetMessageW(System.Windows.Interop.MSG ByRef, System.Runtime.InteropServices.HandleRef, Int32, Int32)"

**Comment by Ross-Patterson** [comment]
Please upgrade to the latest version 3.3.0.9, where I have made some changes. If the crashes still happen, let me know.
