### ISSUE TITLE
FEATURE REQUEST: Add "Home " button for Portals

### ISSUE THREAD

**Issue by SourPatchKidd** [Ross-Patterson/Portals-Desktop-Organization#287]
Hope I'm not having a blind moment here as far as looking to see if it's already been requested. But it would be nice to have a "Home" button added to the header/menu of of each Portal that immediately goes to the root folder assigned to that specific Portal. It otherwise can be a bit annoying having to keep clicking "Back" just to get to the root folder.

**Comment by Ross-Patterson** [comment]
Nice idea - will work on this

**Comment by Ross-Patterson** [comment]
This is added in the latest version which is available for early testing here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/305

If you want to test it, please read carefully before installing, so you don't lose any of your settings if something goes wrong.

**Comment by Ross-Patterson** [comment]
This is added in the latest release.
