### ISSUE TITLE
Instant Crash

### ISSUE THREAD

**Issue by http403** [Ross-Patterson/Portals-Desktop-Organization#29]
**Describe the bug**
I don't know what happened. After Windows update, it just crash in a few seconds after launching. I couldn't find a log that can help me to figureout what's going on.

**To Reproduce**
1. Update Windows 10 (?)

**Expected behavior**
A normal no crash launch

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 19043.1706

**Comment by Ross-Patterson** [comment]
@http403 if you go to:
C:\Users\%USERNAME%\AppData\Local\Portals\crashlogs

Hopefully there will be a crash log there (assuming Portals is actually getting a chance to start)

Additionally, you can create a file called "debugmode.yes" in:
C:\Users\%USERNAME%\AppData\Local\Portals\

This will turn on some debug stuff, but also create some more log files in:
C:\Users\%USERNAME%\AppData\Local\Portals\logs

If you could send both logs if possible I can hopefully see whats happening.

Thanks,
Ross

**Comment by http403** [comment]
There's no crashlogs in the directory. And I think I found the problem: Surfshark VPN. After I connected the VPN, Portal will exit (not crash as there isn't a crash log) after a few moment.

The debug log doesn't show any thing interesting but I will upload it anyway. I redacted some information, namely the license key and my name. [portals_log_2022-06-13_17-13-34_3941934.log](https://github.com/Ross-Patterson/Portals-Desktop-Organization/files/8892766/portals_log_2022-06-13_17-13-34_3941934.log)
.

**Comment by http403** [comment]
I found some Windows log about the crash (maybe). Seems something happened with `ntdll.dll`. Hopes this helps
[Portal Error Event Logs.zip](https://github.com/Ross-Patterson/Portals-Desktop-Organization/files/8900723/Portal.Error.Event.Logs.zip) (Ziped as GH doesn't allow me to upload EVTX files)
.

**Comment by http403** [comment]
Here is the log of the latest crash **without** the VPN connection.
[portals_log_2022-06-19_13-44-31_3373255.log](https://github.com/Ross-Patterson/Portals-Desktop-Organization/files/8935525/portals_log_2022-06-19_13-44-31_3373255.log) 
[System Crash Log.log](https://github.com/Ross-Patterson/Portals-Desktop-Organization/files/8935526/System.Crash.Log.log)(Please rename to .evtx)
 
I'm happy to test out for you further if you can provide a debug version with instructions to capture errors.

**Comment by Iwitrag** [comment]
Same problem here. Portals randomly crashes after automatic startup, resulting in no icons on desktop. Sometimes it just works, sometimes it doesn't.

**Comment by RannerBoss** [comment]
Same here crashing on startup and App losing its License every time this happens
Error:
Unhandled exception in Portals v2.1.0.4

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'api.gumroad.com'
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PortalsMVVM.Domain.Utils.LicenseHandler.<>c__DisplayClass1_0.<<CheckLicense>b__0>d.MoveNext() in C:\Users\Ross\Projects\VisualStudioProjects\PortalsMVVM\PortalsMVVM\Domain\Utils\LicenseHandler.cs:line 29
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'api.gumroad.com'
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PortalsMVVM.Domain.Utils.LicenseHandler.<>c__DisplayClass1_0.<<CheckLicense>b__0>d.MoveNext() in C:\Users\Ross\Projects\VisualStudioProjects\PortalsMVVM\PortalsMVVM\Domain\Utils\LicenseHandler.cs:line 29<---


TaskScheduler.UnobservedTaskException

Internet Connected:False

**Comment by Ross-Patterson** [comment]
> Here is the log of the latest crash **without** the VPN connection. [portals_log_2022-06-19_13-44-31_3373255.log](https://github.com/Ross-Patterson/Portals-Desktop-Organization/files/8935525/portals_log_2022-06-19_13-44-31_3373255.log) [System Crash Log.log](https://github.com/Ross-Patterson/Portals-Desktop-Organization/files/8935526/System.Crash.Log.log)(Please rename to .evtx)
> 
> I'm happy to test out for you further if you can provide a debug version with instructions to capture errors.

@http403 you are right it seems to be ntdll.dll causing a crash, there is very little information on what this actually is or does:
_"The ntdll. dll file is a file created by Microsoft with a description of "NT Layer DLL" and is the file containing NT kernel functions."_

Things to try:
1. Clean Boot - to see if the issue persists with only the minimal driver sets - https://support.microsoft.com/en-gb/topic/how-to-perform-a-clean-boot-in-windows-da2f9573-6eec-00ad-2f8a-a97a1807f3dd

2. Test with Windows Application Verifier - https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/application-verifier (I haven't used this myself yet but maybe you can have a go)

**Comment by http403** [comment]
For over a month, I don't saw it crashing again. Not sure why but there are numerous Windows Update. Maybe those fixed the issue. I would like to close it for now but I don't know if @Iwitrag still experiencing the crash.

**Comment by http403** [comment]
It is almost another month. I will close this issue for now.
