### ISSUE TITLE
BUG: Exporting App Settings does not allow Overwrites

### ISSUE THREAD

**Issue by theczorn** [Ross-Patterson/Portals-Desktop-Organization#291]
**Describe the bug**
If I attempt to Export my settings to a local directory as a `zip` file, if an existing file there shares the same name the application fails the export.

**To Reproduce**
1. Go to Customize in the Portals app
2. Click on App Settings
3. Click on `Export Settings` button in the lower right
4. Attempt to overwrite an existing Portal Settings zip file (ie - portal_settings.zip

**Expected behavior**
The Windows OS should prompt me that I'm overwriting an existing file. Selecting `Yes` will overwrite that file. `No` will exit the user flow.

**Actual Behavior**
Selecting Yes proceeds with the save in the OS, but the application is throwing a duplicate file found error.

**Screenshots**
![bug](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/8892871/27a38e58-6215-49c0-8802-35703acaba53)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Version: 23H22/‎11/‎2022
 - OS build: 22631.3527

**Additional context**
N/A

**Comment by Ross-Patterson** [comment]
Thanks for reporting - I will add in the overwrite prompt in the next update

**Comment by Ross-Patterson** [comment]
This is fixed in the latest version which is available for early testing here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/305

If you want to test it, please read carefully before installing, so you don't lose any of your settings if something goes wrong.

**Comment by Ross-Patterson** [comment]
This is fixed in the latest release.
