### ISSUE TITLE
Windows 11: Desktop right-click context menu does not contain "New Portal and Folder" menu entry.

### ISSUE THREAD

**Issue by wstanzl** [Ross-Patterson/Portals-Desktop-Organization#292]
On Windows 11. the desktop right-click context menu does not contain "New Portal and Folder" menu entry.

Steps to reproduce:

1) Install Portals on a Windows 11 computer.
2) Richt click on Desktop. 
-> There is no "New Portal and Folder" menu entry.

**Comment by Ross-Patterson** [comment]
I think on Windows 11 there is a button for "Show more options".

This will show the full old-style menu, and the option will be there.

You can restore the old one I believe through some registry modification.

**Comment by wstanzl** [comment]
Okay, thanks for the info, it is this registry entry:

reg add HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32 /ve /d "" /f
