### ISSUE TITLE
FEATURE REQUEST: Default portal for new desktop icons

### ISSUE THREAD

**Issue by Clavus** [Ross-Patterson/Portals-Desktop-Organization#295]
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### What is the enhancement/feature you would like to see?

I'm not sure if I simply missing something here, but I can't find it anywhere in the settings. It's a feature that I'm missing from Fences:

I would like the option for Portals to detect when a new icon is added to the desktop and automatically move it to a predefined Portal. Especially since desktop icons are now hidden to hide the Portal folders it's kinda useful to know when something new has been added to the desktop.

**Comment by Ross-Patterson** [comment]
I will not be implementing this - with the Portals app I want the user to be in full control and I will not implement anything to move your files around automatically.

However, you could achieve something like this yourself, using PowerShell and the windows Task Scheduler:
1. Write a PowerShell script that copies all files from your Desktop to your specified folder.
2. Schedule it to run every 5mins or something via Task Scheduler.
