### ISSUE TITLE
FEATURE REQUEST:  Sort font names in Customize

### ISSUE THREAD

**Issue by parmstrong7000** [Ross-Patterson/Portals-Desktop-Organization#298]
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### What is the enhancement/feature you would like to see?

When selecting fonts, the list isn't sorted, so my 254 fonts are hard to pick through when they're not sorted by name.

Note: a workaround I found, which means I now love your interface, is to start typing the font name and the list dives down to that font.  [ the problem with that workaround is I typically forget the font name from all the other things cluttering my head ]

**Comment by Ross-Patterson** [comment]
Glad you found a workaround, I will fix it so they are sorted

**Comment by Ross-Patterson** [comment]
This is fixed in the latest release.
