### ISSUE TITLE
Drag-and-drop files from Portals into Discord (and similar clients?)

### ISSUE THREAD

**Issue by Taavirocious** [Ross-Patterson/Portals-Desktop-Organization#3]
Currently, when attempting to drag and drop a file from a Portal directly into a Discord window, it is greeted with a red circular 'not allowed' cursor and the process is not carried out (also when running Portals as admin). The function however works in explorer and in web browsers.

**Comment by Ross-Patterson** [comment]
Hmmm... let me take a look and see if I can figure this one out.

**Comment by Ross-Patterson** [comment]
@Taavirocious I found the problem and it will be fixed in the next update!

**Comment by Taavirocious** [comment]
Oh, that's actually very exciting! I went through a few of similar apps and Portals is getting more ahead of the pack with each update.
I don't know if it's interesting, but the usage case I have used it for is to clear out the desktop with no icons whatsoever and have two portals bars up top with -4 Y axis (so you can fling the mouse straight against the edge and open it without missing the click really really fast, this way the wallpaper is clear and I can quick-launch Steam games one one side and the other I can place the most frequently accessed files (which makes this update a whole new world).
Thanks you!

**Comment by Ross-Patterson** [comment]
This is now available in v2.1.0.4.
