### ISSUE TITLE
Portals starts but won't open my portals 

### ISSUE THREAD

**Issue by HEYDAYcreatives** [Ross-Patterson/Portals-Desktop-Organization#301]
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### Version

3.2.1.0

### Operating System

Windows 11

### What happened?

Portals starts on Double Click from the desktop
The portals are seen on the desktop for a second and collapse again.
The portals icon is in the taskbar now but when I click it it will show the portals settings screen only. Everything seems to be there but the actual portal windows won't be shown.

### Steps to Reproduce

Double click Portals App on the desktop.

### What would you expect to happen?

After double click on the icon of the portals app it should show my portals on the desktop.

**Comment by Ross-Patterson** [comment]
Can you show a screenshot of the setting screen with all of the portals listed?

**Comment by Ross-Patterson** [comment]
Closing due to no response
