### ISSUE TITLE
FEATURE REQUEST: Double click Fix

### ISSUE THREAD

**Issue by Chriscalo123** [Ross-Patterson/Portals-Desktop-Organization#302]
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### What is the enhancement/feature you would like to see?

The screen hides the portals everytime I double click on the folders. But it should only hide them if I double click on the desktop just like Fences does. Could you please fix this? Thanks you.

**Comment by Ross-Patterson** [comment]
Temporary solution is not make your desktop background a slideshow. Then it will work as you expect.

**Comment by Ross-Patterson** [comment]
If you want to try a test version where this is fixed, see here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/305#discussion-6690066

**Comment by Ross-Patterson** [comment]
This is fixed in the latest release.
