### ISSUE TITLE
BUG: Some random folder disappear when click 3.3.0.5

### ISSUE THREAD

**Issue by SSadako** [Ross-Patterson/Portals-Desktop-Organization#307]
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### Version

3.2.1.0

### Operating System

Windows 11

### What happened?

When I click on some folder it just disappear and reappear if i click outside
(I think it's because of some app inside the folder but idk which)

### Steps to Reproduce

1. please fix

### What would you expect to happen?

not blink

**Comment by Ross-Patterson** [comment]
Can you provide any screen recording so I can see exactly what is happening?

There is not enough info here for me to do anything.

**Comment by SSadako** [comment]
i will send a video if it happens again. i mean it does happen randomly

**Comment by SSadako** [comment]
https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66819431/cf5d05e4-74c6-4dc7-a49b-6b031a3fcd92

**Comment by Ross-Patterson** [comment]
Ahh yes, this is a long standing issue, if you look at the pinned issues you should see the workaround in there. (Essentially create a dummy portal, make it bottom-most, then hide it).

It happens to the bottom-most portal window after using Win+D (Show Desktop), and it seems to be a windows issue.

**Comment by Ross-Patterson** [comment]
See here: #101 

Btw those are some impressively customized portals with the images, very nice!
