### ISSUE TITLE
BUG: Custom Sort Order resets when applying it in a subfolder

### ISSUE THREAD

**Issue by mklu-e61** [Ross-Patterson/Portals-Desktop-Organization#308]
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### Version

3.2.1.0

### Operating System

Windows 11

### What happened?

I have a Portal that contains folders. Within each folder, I would like to set a custom sort order. But when I change the custom sort within one of these folders, the custom sort in the parent folder gets reset.

### Steps to Reproduce

Create a subfolder and edit the custom sort order

### What would you expect to happen?

To set a custom sort order per folder.

**Comment by Ross-Patterson** [comment]
Sort order is per Portal window. In the latest version 3.3.0, currently Beta, I have added support to add multiple tabs to a single portal window, and each of those tabs can have its own sort order, thats maybe the way to go.
