### ISSUE TITLE
BUG: 3.2.1 auto download update even it latest, and app not launches after it

### ISSUE THREAD

**Issue by t0otal** [Ross-Patterson/Portals-Desktop-Organization#309]
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### Version

3.2.1.0

### Operating System

Windows 11

### What happened?

Well. first of all, thanks for this FREE (with donation)  alternative to Fences.  It's very nice done application,
The problem is:
I installed 3.2.1 version, and on another day app requires to update itself. And that's it. After update Portals starts and closes itself automatically, even after reboot.
Don't know why, but 3.2.1 version downloading updates... even it latest...

### Steps to Reproduce

1. install portals 3.2.1
2. reboot or wait some time, when portals automatically starts to download new update ~12mb and shows installer. 
3. install
4. run from shortcut
5. crash

### What would you expect to happen?

updated app launches and work properly

**Comment by Ross-Patterson** [comment]
Can you check in the folder:
C:\Users\<username>\AppData\Local\Portals\crashlogs
and see if there are any crashlogs?

Also any log in:
C:\Users\<username>\AppData\Local\Portals\logs
will be helpful also...

**Comment by Ross-Patterson** [comment]
I just pushed out beta version 3.3.0.6, try that one and see if it works:
https://downloads.portals-app.com/installers%2F3.3.0.6%2Fportals_installer_v3-3-0-6.exe?alt=media

**Comment by Ross-Patterson** [comment]
This should be fixed now in the latest release:
https://downloads.portals-app.com/installers%2F3.3.0.8%2Fportals_installer_v3-3-0-8.exe?alt=media
