### ISSUE TITLE
Right click option to open default shell menu

### ISSUE THREAD

**Issue by G1ll0u** [Ross-Patterson/Portals-Desktop-Organization#31]
I use a lot the "open file location" function in the context menu a lot. This option opens the portal folder where my shortcut is and I need to open the shortcut's folder, see ?

I have an idea and here's an image to illustrate it :
![For my frienb](https://user-images.githubusercontent.com/36129824/175123536-6e59b311-2a7f-4de7-8e2c-f7d2f2c67126.png)

Why not add an option to open the Windows context menu of the item ? It would be great !

Thanks for your work, it's a great soft that you've done.

**Comment by Ross-Patterson** [comment]
@G1ll0u,
I have changed the "Open File Location" behaviour in the upcoming version to open the Target path if it is a .lnk file.

I also added your request as above:
![image](https://user-images.githubusercontent.com/66630787/178987853-8702af4a-3a16-4edb-8e37-7f693a4af0a7.png)

Which will open the default Windows Explorer Menu.

**Comment by G1ll0u** [comment]
Good work, thank you !

After thinking about it, I think that an option to make the Windows context menu appear exclusively instead of yours would be a good idea, I have some files that I want to edit or open with a specific application, for example a .BAT file. To access the "Edit" button I will have to go through your new function and ergonomically, it's not great you see?
