### ISSUE TITLE
Retaining Sorting 

### ISSUE THREAD

**Issue by bdhtgcr** [Ross-Patterson/Portals-Desktop-Organization#310]
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### Version

3.2.1.0

### Operating System

Windows 11

### What happened?

The sorting works as it should. But when the pc is restarted, the sorting is lost. Even if a saved layout is applied, the sorting has to get redone. 

### Steps to Reproduce

You can try it yourself

### What would you expect to happen?

I would expect the sorting could be retrained from session to session

**Comment by Ross-Patterson** [comment]
This is fixed in the latest release.
