### ISSUE TITLE
BUG: "Show Desktop" feature (Windows Key + D) Hides Portals

### ISSUE THREAD

**Issue by thx1200** [Ross-Patterson/Portals-Desktop-Organization#313]
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### Version

3.2.1.0

### Operating System

Windows 10

### What happened?

If you click on the "Show Desktop" button (lower left of task bar) or press WIN+D (Show Desktop shortcut), Portals hides with all the other windows.  I consider Portals to be a part of my desktop, so I think the behavior should be that Portals does not hide.  Maybe this needs to be an option.

### Steps to Reproduce

Press Win+D.

### What would you expect to happen?

Portals to not hide.

**Comment by Ross-Patterson** [comment]
If you upgrade to beta version 3.3.0.6 this problem should go away.

**Comment by Ross-Patterson** [comment]
do diagnose this issue, I will need you to do the following:

1. Download and Install: WindowDetective (https://windowdetective.sourceforge.io/)
2. Open Window Detective and drag the "Pick Window" picker over your desktop
3. Send a screenshot of the window it expands to in the list e.g.:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/771f2bf3-60c0-4452-83db-c7c6d02a4666)

If you get me this info, I can maybe figure out what is happening.

**Comment by thx1200** [comment]
Well, today I sat down to troubleshoot and it's just not happening anymore.  Maybe it was a transient issue.  I have not rebooted but I have restarted Portals and tried some other features and I can't really remember all the other changes I made.  If it happens again, I'll run through the troubleshooting steps you outlined above.  Until then, I guess consider this issue closed.

**Comment by thx1200** [comment]
Closing
