### ISSUE TITLE
BUG: After update Portals stopped working at all

### ISSUE THREAD

**Issue by AlexisVAH** [Ross-Patterson/Portals-Desktop-Organization#315]
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### Version

3.3.0.7

### Operating System

Windows 10

### What happened?

Portals stop working after auto update didnt do anything more, I tried to uninstall and reinstall but keeps crashing

### Steps to Reproduce

Didn't do anything out of the ordinary here's the crashlog

Version: 3.3.0.7
Event Source: Application.Current.DispatcherUnhandledException
Internet Connected: yes

Exception Source: WindowsDisplayAPI

Message:
Índice fuera de los límites de la matriz.

StackTrace:
   en WindowsDisplayAPI.DisplayConfig.PathDisplaySource.get_CurrentDPIScale()
   en Portals.Model.Display.AllScreens() en C:\Users\Ross\Projects\VisualStudioProjects\Portals\Model\Display.cs:línea 70
   en Portals.Services.ProvidedServices.DisplayService.GetCurrentSetupAsDisplaySetup() en C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\DisplayService.cs:línea 44
   en Portals.Services.ProvidedServices.DisplayService..ctor() en C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\DisplayService.cs:línea 27
   en Portals.Services.ProvidedServices.DisplayService.<>c.<.cctor>b__14_0() en C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\DisplayService.cs:línea 21
   en System.Lazy`1.CreateValue()
   en System.Lazy`1.LazyInitValue()
   en Portals.Services.ProvidedServices.DisplayService.get_Instance() en C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\DisplayService.cs:línea 23
   en Portals.Services.ProvidedServices.AppManagerService.InitializeApp(Action OnComplete) en C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\AppManagerService.cs:línea 123
   en Portals.ViewModels.SplashScreenViewModel.ExecuteSplashScreenLoadedCommand(Window w) en C:\Users\Ross\Projects\VisualStudioProjects\Portals\ViewModels\SplashScreenViewModel.cs:línea 40
   en Microsoft.Xaml.Behaviors.InvokeCommandAction.Invoke(Object parameter) en C:\A\1\97\s\src\Microsoft.Xaml.Behaviors\InvokeCommandAction.cs:línea 147
   en Microsoft.Xaml.Behaviors.TriggerBase.InvokeActions(Object parameter) en C:\A\1\97\s\src\Microsoft.Xaml.Behaviors\TriggerBase.cs:línea 153
   en System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   en System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   en System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   en System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   en MS.Internal.LoadedOrUnloadedOperation.DoWork()
   en System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   en System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   en System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   en System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   en System.Windows.Interop.HwndTarget.OnResize()
   en System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   en System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
WindowsDisplayAPI.Native.DisplayConfig.DisplayConfigSourceDPIScale get_CurrentDPIScale()

Version: 3.3.0.7
Event Source: Application.Current.DispatcherUnhandledException
Internet Connected: yes

Exception Source: WindowsDisplayAPI

Message:
Índice fuera de los límites de la matriz.

StackTrace:
   en WindowsDisplayAPI.DisplayConfig.PathDisplaySource.get_CurrentDPIScale()
   en Portals.Model.Display.AllScreens() en C:\Users\Ross\Projects\VisualStudioProjects\Portals\Model\Display.cs:línea 70
   en Portals.Services.ProvidedServices.DisplayService.GetCurrentSetupAsDisplaySetup() en C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\DisplayService.cs:línea 44
   en Portals.Services.ProvidedServices.DisplayService..ctor() en C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\DisplayService.cs:línea 27
   en Portals.Services.ProvidedServices.DisplayService.<>c.<.cctor>b__14_0() en C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\DisplayService.cs:línea 21
   en System.Lazy`1.CreateValue()
   en System.Lazy`1.LazyInitValue()
   en Portals.Services.ProvidedServices.DisplayService.get_Instance() en C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\DisplayService.cs:línea 23
   en Portals.Services.ProvidedServices.AppManagerService.InitializeApp(Action OnComplete) en C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\AppManagerService.cs:línea 123
   en Portals.ViewModels.SplashScreenViewModel.ExecuteSplashScreenLoadedCommand(Window w) en C:\Users\Ross\Projects\VisualStudioProjects\Portals\ViewModels\SplashScreenViewModel.cs:línea 40
   en Microsoft.Xaml.Behaviors.InvokeCommandAction.Invoke(Object parameter) en C:\A\1\97\s\src\Microsoft.Xaml.Behaviors\InvokeCommandAction.cs:línea 147
   en Microsoft.Xaml.Behaviors.TriggerBase.InvokeActions(Object parameter) en C:\A\1\97\s\src\Microsoft.Xaml.Behaviors\TriggerBase.cs:línea 153
   en System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   en System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   en System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   en System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   en MS.Internal.LoadedOrUnloadedOperation.DoWork()
   en System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   en System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   en System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   en System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   en System.Windows.Interop.HwndTarget.OnResize()
   en System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   en System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
WindowsDisplayAPI.Native.DisplayConfig.DisplayConfigSourceDPIScale get_CurrentDPIScale()

Version: 3.3.0.7
Event Source: Application.Current.DispatcherUnhandledException
Internet Connected: yes

Exception Source: WindowsDisplayAPI

Message:
Índice fuera de los límites de la matriz.

StackTrace:
   en WindowsDisplayAPI.DisplayConfig.PathDisplaySource.get_CurrentDPIScale()
   en Portals.Model.Display.AllScreens() en C:\Users\Ross\Projects\VisualStudioProjects\Portals\Model\Display.cs:línea 70
   en Portals.Services.ProvidedServices.DisplayService.GetCurrentSetupAsDisplaySetup() en C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\DisplayService.cs:línea 44
   en Portals.Services.ProvidedServices.DisplayService..ctor() en C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\DisplayService.cs:línea 27
   en Portals.Services.ProvidedServices.DisplayService.<>c.<.cctor>b__14_0() en C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\DisplayService.cs:línea 21
   en System.Lazy`1.CreateValue()
   en System.Lazy`1.LazyInitValue()
   en Portals.Services.ProvidedServices.DisplayService.get_Instance() en C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\DisplayService.cs:línea 23
   en Portals.Services.ProvidedServices.AppManagerService.InitializeApp(Action OnComplete) en C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\AppManagerService.cs:línea 123
   en Portals.ViewModels.SplashScreenViewModel.ExecuteSplashScreenLoadedCommand(Window w) en C:\Users\Ross\Projects\VisualStudioProjects\Portals\ViewModels\SplashScreenViewModel.cs:línea 40
   en Microsoft.Xaml.Behaviors.InvokeCommandAction.Invoke(Object parameter) en C:\A\1\97\s\src\Microsoft.Xaml.Behaviors\InvokeCommandAction.cs:línea 147
   en Microsoft.Xaml.Behaviors.TriggerBase.InvokeActions(Object parameter) en C:\A\1\97\s\src\Microsoft.Xaml.Behaviors\TriggerBase.cs:línea 153
   en System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   en System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   en System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   en System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   en MS.Internal.LoadedOrUnloadedOperation.DoWork()
   en System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   en System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   en System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   en System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   en System.Windows.Interop.HwndTarget.OnResize()
   en System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   en System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
WindowsDisplayAPI.Native.DisplayConfig.DisplayConfigSourceDPIScale get_CurrentDPIScale()

### What would you expect to happen?

I just want to keep using it as always

**Comment by Ross-Patterson** [comment]
Try this:
https://downloads.portals-app.com/installers%2F3.3.0.8%2Fportals_installer_v3-3-0-8.exe?alt=media

Its struggling to get the DPI (Scaling) of one of your monitors for some reason.

**Comment by AlexisVAH** [comment]
> Try this: https://downloads.portals-app.com/installers%2F3.3.0.8%2Fportals_installer_v3-3-0-8.exe?alt=media
> 
> Its struggling to get the DPI (Scaling) of one of your monitors for some reason.

Yes! that solved it thanks a lot

**Comment by xanathon** [comment]
I have the same problem, Portals crashes immediately after starting, I tried the new version in the post above, but that does not help. I have a four monitor setup.

Where do I find the logs?

**Comment by xanathon** [comment]
Log after first crash:

```
Version: 3.3.0.8
Event Source: Application.Current.DispatcherUnhandledException
Internet Connected: yes

Exception Source: Prism.Wpf

Message:
Der Wert darf nicht NULL sein.
Parametername: items

StackTrace:
   bei System.Collections.ObjectModel.CollectionExtensions.AddRange[T](Collection`1 collection, IEnumerable`1 items) in /_/src/Wpf/Prism.Wpf/Extensions/CollectionExtensions.cs:Zeile 25.
   bei Portals.Services.ProvidedServices.AppManagerService.InitializeApp(Action OnComplete) in C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\AppManagerService.cs:Zeile 153.
   bei Portals.ViewModels.SplashScreenViewModel.ExecuteSplashScreenLoadedCommand(Window w) in C:\Users\Ross\Projects\VisualStudioProjects\Portals\ViewModels\SplashScreenViewModel.cs:Zeile 40.
   bei Microsoft.Xaml.Behaviors.InvokeCommandAction.Invoke(Object parameter) in C:\A\1\97\s\src\Microsoft.Xaml.Behaviors\InvokeCommandAction.cs:Zeile 147.
   bei Microsoft.Xaml.Behaviors.TriggerBase.InvokeActions(Object parameter) in C:\A\1\97\s\src\Microsoft.Xaml.Behaviors\TriggerBase.cs:Zeile 153.
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   bei System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   bei MS.Internal.LoadedOrUnloadedOperation.DoWork()
   bei System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   bei System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   bei System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   bei System.Windows.Interop.HwndTarget.OnResize()
   bei System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
System.Collections.ObjectModel.Collection`1[T] AddRange[T](System.Collections.ObjectModel.Collection`1[T], System.Collections.Generic.IEnumerable`1[T])
```

Log after update to the above version:

```
Version: 3.3.0.8
Event Source: Application.Current.DispatcherUnhandledException
Internet Connected: yes

Exception Source: Prism.Wpf

Message:
Der Wert darf nicht NULL sein.
Parametername: items

StackTrace:
   bei System.Collections.ObjectModel.CollectionExtensions.AddRange[T](Collection`1 collection, IEnumerable`1 items) in /_/src/Wpf/Prism.Wpf/Extensions/CollectionExtensions.cs:Zeile 25.
   bei Portals.Services.ProvidedServices.AppManagerService.InitializeApp(Action OnComplete) in C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\AppManagerService.cs:Zeile 153.
   bei Portals.ViewModels.SplashScreenViewModel.ExecuteSplashScreenLoadedCommand(Window w) in C:\Users\Ross\Projects\VisualStudioProjects\Portals\ViewModels\SplashScreenViewModel.cs:Zeile 40.
   bei Microsoft.Xaml.Behaviors.InvokeCommandAction.Invoke(Object parameter) in C:\A\1\97\s\src\Microsoft.Xaml.Behaviors\InvokeCommandAction.cs:Zeile 147.
   bei Microsoft.Xaml.Behaviors.TriggerBase.InvokeActions(Object parameter) in C:\A\1\97\s\src\Microsoft.Xaml.Behaviors\TriggerBase.cs:Zeile 153.
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   bei System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   bei MS.Internal.LoadedOrUnloadedOperation.DoWork()
   bei System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   bei System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   bei System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   bei System.Windows.Interop.HwndTarget.OnResize()
   bei System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
System.Collections.ObjectModel.Collection`1[T] AddRange[T](System.Collections.ObjectModel.Collection`1[T], System.Collections.Generic.IEnumerable`1[T])

```

**Comment by Ross-Patterson** [comment]
> Log after first crash:
> 
> ```
> Version: 3.3.0.8
> Event Source: Application.Current.DispatcherUnhandledException
> Internet Connected: yes
> 
> Exception Source: Prism.Wpf
> 
> Message:
> Der Wert darf nicht NULL sein.
> Parametername: items
> 
> StackTrace:
>    bei System.Collections.ObjectModel.CollectionExtensions.AddRange[T](Collection`1 collection, IEnumerable`1 items) in /_/src/Wpf/Prism.Wpf/Extensions/CollectionExtensions.cs:Zeile 25.
>    bei Portals.Services.ProvidedServices.AppManagerService.InitializeApp(Action OnComplete) in C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\AppManagerService.cs:Zeile 153.
>    bei Portals.ViewModels.SplashScreenViewModel.ExecuteSplashScreenLoadedCommand(Window w) in C:\Users\Ross\Projects\VisualStudioProjects\Portals\ViewModels\SplashScreenViewModel.cs:Zeile 40.
>    bei Microsoft.Xaml.Behaviors.InvokeCommandAction.Invoke(Object parameter) in C:\A\1\97\s\src\Microsoft.Xaml.Behaviors\InvokeCommandAction.cs:Zeile 147.
>    bei Microsoft.Xaml.Behaviors.TriggerBase.InvokeActions(Object parameter) in C:\A\1\97\s\src\Microsoft.Xaml.Behaviors\TriggerBase.cs:Zeile 153.
>    bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    bei System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
>    bei System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
>    bei MS.Internal.LoadedOrUnloadedOperation.DoWork()
>    bei System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
>    bei System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
>    bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
>    bei System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
>    bei System.Windows.Interop.HwndTarget.OnResize()
>    bei System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
>    bei System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 
> TargetSite:
> System.Collections.ObjectModel.Collection`1[T] AddRange[T](System.Collections.ObjectModel.Collection`1[T], System.Collections.Generic.IEnumerable`1[T])
> ```
> 
> Log after update to the above version:
> 
> ```
> Version: 3.3.0.8
> Event Source: Application.Current.DispatcherUnhandledException
> Internet Connected: yes
> 
> Exception Source: Prism.Wpf
> 
> Message:
> Der Wert darf nicht NULL sein.
> Parametername: items
> 
> StackTrace:
>    bei System.Collections.ObjectModel.CollectionExtensions.AddRange[T](Collection`1 collection, IEnumerable`1 items) in /_/src/Wpf/Prism.Wpf/Extensions/CollectionExtensions.cs:Zeile 25.
>    bei Portals.Services.ProvidedServices.AppManagerService.InitializeApp(Action OnComplete) in C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\AppManagerService.cs:Zeile 153.
>    bei Portals.ViewModels.SplashScreenViewModel.ExecuteSplashScreenLoadedCommand(Window w) in C:\Users\Ross\Projects\VisualStudioProjects\Portals\ViewModels\SplashScreenViewModel.cs:Zeile 40.
>    bei Microsoft.Xaml.Behaviors.InvokeCommandAction.Invoke(Object parameter) in C:\A\1\97\s\src\Microsoft.Xaml.Behaviors\InvokeCommandAction.cs:Zeile 147.
>    bei Microsoft.Xaml.Behaviors.TriggerBase.InvokeActions(Object parameter) in C:\A\1\97\s\src\Microsoft.Xaml.Behaviors\TriggerBase.cs:Zeile 153.
>    bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    bei System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
>    bei System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
>    bei MS.Internal.LoadedOrUnloadedOperation.DoWork()
>    bei System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
>    bei System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
>    bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
>    bei System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
>    bei System.Windows.Interop.HwndTarget.OnResize()
>    bei System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
>    bei System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 
> TargetSite:
> System.Collections.ObjectModel.Collection`1[T] AddRange[T](System.Collections.ObjectModel.Collection`1[T], System.Collections.Generic.IEnumerable`1[T])
> ```

Try going to C:\Users\username\AppData\Local\Portals

Take the file "layouts.ptl" back back it up somewhere then remove it from that folder.

Restart the app and let me know it it will start after that.

**Comment by xanathon** [comment]
Will I then not loose all my layouts?

**Comment by xanathon** [comment]
I see. I renamed the file and installed the new version. I then saved my layout. This seems to work. Thank you.
