### ISSUE TITLE
BUG: Not working at all after update

### ISSUE THREAD

**Issue by JinxSwe** [Ross-Patterson/Portals-Desktop-Organization#316]
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### Version

3.3.0.8

### Operating System

Windows 11

### What happened?

Got the auto update for 3.3.0.8. Installed it. The splash screen appears. Then nothing. Nothing in task manager. Just not starting. 
Reinstalled. Still nothing.  

### Steps to Reproduce

No idea. 

### What would you expect to happen?

I just want to keep using it as always.

**Comment by Ross-Patterson** [comment]
Please check:
C:\Users\username\AppData\Local\Portals\crashlogs

Send me any crashlogs there and I will have a look.

**Comment by JinxSwe** [comment]
Version: 3.3.0.8
Event Source: Application.Current.DispatcherUnhandledException
Internet Connected: yes

Exception Source: PresentationFramework

Message:
Ett undantag utlöstes när egenskapen System.Windows.Controls.Panel.Background angavs.

StackTrace:
   vid System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   vid System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   vid System.Windows.ResourceDictionary.CreateObject(KeyRecord key)
   vid System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)
   vid System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache)
   vid System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   vid System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   vid System.Windows.FrameworkElement.FindResourceInTree(FrameworkElement feStart, FrameworkContentElement fceStart, DependencyProperty dp, Object resourceKey, Object unlinkedParent, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, DependencyObject boundaryElement, InheritanceBehavior& inheritanceBehavior, Object& source)
   vid System.Windows.FrameworkElement.FindResourceInternal(FrameworkElement fe, FrameworkContentElement fce, DependencyProperty dp, Object resourceKey, Object unlinkedParent, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, DependencyObject boundaryElement, Boolean isImplicitStyleLookup, Object& source)
   vid System.Windows.FrameworkElement.FindImplicitStyleResource(FrameworkElement fe, Object resourceKey, Object& source)
   vid System.Windows.FrameworkElement.GetRawValue(DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry& entry)
   vid System.Windows.FrameworkElement.EvaluateBaseValueCore(DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry& newEntry)
   vid System.Windows.DependencyObject.EvaluateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry newEntry, OperationType operationType)
   vid System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   vid System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   vid System.Windows.FrameworkElement.UpdateStyleProperty()
   vid System.Windows.FrameworkElement.OnInitialized(EventArgs e)
   vid System.Windows.FrameworkElement.TryFireInitialized()
   vid System.Windows.FrameworkElement.OnVisualParentChanged(DependencyObject oldParent)
   vid System.Windows.Media.Visual.FireOnVisualParentChanged(DependencyObject oldParent)
   vid System.Windows.Media.Visual.AddVisualChild(Visual child)
   vid System.Windows.Media.VisualCollection.ConnectChild(Int32 index, Visual value)
   vid System.Windows.Media.VisualCollection.Add(Visual visual)
   vid System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   vid System.Windows.Controls.Panel.GenerateChildren()
   vid System.Windows.Controls.Panel.EnsureGenerator()
   vid System.Windows.Controls.Panel.get_InternalChildren()
   vid System.Windows.Controls.Primitives.TabPanel.MeasureOverride(Size constraint)
   vid System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   vid System.Windows.UIElement.Measure(Size availableSize)
   vid MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   vid System.Windows.Controls.ScrollContentPresenter.MeasureOverride(Size constraint)
   vid System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   vid System.Windows.UIElement.Measure(Size availableSize)
   vid System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   vid System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   vid System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   vid System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   vid System.Windows.UIElement.Measure(Size availableSize)
   vid System.Windows.Controls.ScrollViewer.MeasureOverride(Size constraint)
   vid System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   vid System.Windows.UIElement.Measure(Size availableSize)
   vid System.Windows.Controls.DockPanel.MeasureOverride(Size constraint)
   vid System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   vid System.Windows.UIElement.Measure(Size availableSize)
   vid System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   vid System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   vid System.Windows.UIElement.Measure(Size availableSize)
   vid System.Windows.Controls.Control.MeasureOverride(Size constraint)
   vid System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   vid System.Windows.UIElement.Measure(Size availableSize)
   vid MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   vid System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   vid System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   vid System.Windows.UIElement.Measure(Size availableSize)
   vid System.Windows.Controls.DockPanel.MeasureOverride(Size constraint)
   vid System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   vid System.Windows.UIElement.Measure(Size availableSize)
   vid System.Windows.Controls.Control.MeasureOverride(Size constraint)
   vid System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   vid System.Windows.UIElement.Measure(Size availableSize)
   vid System.Windows.Controls.Border.MeasureOverride(Size constraint)
   vid System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   vid System.Windows.UIElement.Measure(Size availableSize)
   vid System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   vid System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   vid System.Windows.UIElement.Measure(Size availableSize)
   vid MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   vid System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   vid System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   vid System.Windows.UIElement.Measure(Size availableSize)
   vid System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
   vid System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   vid System.Windows.UIElement.Measure(Size availableSize)
   vid System.Windows.Controls.Border.MeasureOverride(Size constraint)
   vid System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   vid System.Windows.UIElement.Measure(Size availableSize)
   vid System.Windows.Window.MeasureOverrideHelper(Size constraint)
   vid System.Windows.Window.MeasureOverride(Size availableSize)
   vid System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   vid System.Windows.UIElement.Measure(Size availableSize)
   vid System.Windows.Interop.HwndSource.SetLayoutSize()
   vid System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   vid System.Windows.Window.SetRootVisual()
   vid System.Windows.Window.SetRootVisualAndUpdateSTC()
   vid System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   vid System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   vid System.Windows.Window.ShowHelper(Object booleanBox)
   vid Portals.Services.ProvidedServices.PortalService.CreatePortalWindow(Portal portal, Boolean saveAfter) i C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\PortalService.cs:rad 47
   vid Portals.Services.ProvidedServices.AppManagerService.InitializeApp(Action OnComplete) i C:\Users\Ross\Projects\VisualStudioProjects\Portals\Services\ProvidedServices\AppManagerService.cs:rad 147
   vid Portals.ViewModels.SplashScreenViewModel.ExecuteSplashScreenLoadedCommand(Window w) i C:\Users\Ross\Projects\VisualStudioProjects\Portals\ViewModels\SplashScreenViewModel.cs:rad 40
   vid Microsoft.Xaml.Behaviors.InvokeCommandAction.Invoke(Object parameter) i C:\A\1\97\s\src\Microsoft.Xaml.Behaviors\InvokeCommandAction.cs:rad 147
   vid Microsoft.Xaml.Behaviors.TriggerBase.InvokeActions(Object parameter) i C:\A\1\97\s\src\Microsoft.Xaml.Behaviors\TriggerBase.cs:rad 153
   vid System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   vid System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   vid System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   vid System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   vid MS.Internal.LoadedOrUnloadedOperation.DoWork()
   vid System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   vid System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   vid System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   vid System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   vid System.Windows.Interop.HwndTarget.OnResize()
   vid System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   vid System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   vid MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   vid MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   vid System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   vid System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
Void RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)

**Comment by Ross-Patterson** [comment]
Ahh ok, update to 3.3.0.9 and this will be rrsolved
