### ISSUE TITLE
BUG: Set property 'System.Windows.Controls.Panel.Background' threw an exception.

### ISSUE THREAD

**Issue by Leab-JB** [Ross-Patterson/Portals-Desktop-Organization#317]
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### Version

3.3.0.8

### Operating System

Windows 10

### What happened?

Since I was previously using the **version 3.2.1**, I never got any issue but after updating it to the latest version (3.3.0.8), whenever I open the app it crashes with the error **"Set property 'System.Windows.Controls.Panel.Background' threw an exception."** Below is the crash log.
[portals-crashlog-20240613_0739.log](https://github.com/user-attachments/files/15815052/portals-crashlog-20240613_0739.log)

### Steps to Reproduce

Donwload and install the latest version (3.3.0.8)

### What would you expect to happen?

I would expect the app work normally as the previous version. Until then, I will continue with an old version.

**Comment by Ross-Patterson** [comment]
Looking into it - will try to get a fix out ASAP

**Comment by Ross-Patterson** [comment]
Can you provide me some info:

Go to: C:\Users\username\AppData\Local\Portals

Open the file: portals.ptl

I need to see the value of any of the Color tags i.e. HeaderBackgroundColor, like this:
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/8afa4c80-0548-4be0-b8a0-f05b887f0143)

**Comment by Leab-JB** [comment]
> Can you provide me some info:
> 
> Go to: C:\Users\username\AppData\Local\Portals
> 
> Open the file: portals.ptl
> 
> I need to see the value of any of the Color tags i.e. HeaderBackgroundColor, like this: ![image](https://private-user-images.githubusercontent.com/66630787/339276779-8afa4c80-0548-4be0-b8a0-f05b887f0143.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjY2OTMsIm5iZiI6MTcxODI2NjM5MywicGF0aCI6Ii82NjYzMDc4Ny8zMzkyNzY3NzktOGFmYTRjODAtMDU0OC00YmUwLWI4YTAtZjA1Yjg4N2YwMTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA4MTMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1YjRiNTQ5NGQwMWRlMmY5YjMyNTAzY2MxYjc4N2E2MzBhMGM2NTkzNzE0OTYxMDU3M2U2OGNiZDI1YjVmODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zDBc-KC2i4lhaQiMzDrOK3_anMN6ZuzUTvdcEFPEZxY)

Sure
Here it is:
![portals_color_tag](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/133040672/e7977d2b-a6a7-4183-988a-368ec69d4c0e)

**Comment by Ross-Patterson** [comment]
Great, try this:
https://downloads.portals-app.com/installers%2F3.3.0.9%2Fportals_installer_v3-3-0-9.exe?alt=media

**Comment by Leab-JB** [comment]
> Great, try this: https://downloads.portals-app.com/installers%2F3.3.0.9%2Fportals_installer_v3-3-0-9.exe?alt=media

Great, it's working now
![portals_organization_stuff](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/133040672/b16821cb-5bda-4590-a2a2-169c1b563a2a)

Thanks

**Comment by Ross-Patterson** [comment]
Great!

**Comment by Leab-JB** [comment]
Complete
