### ISSUE TITLE
FEATURE REQUEST: Hide Down

### ISSUE THREAD

**Issue by jerquiaga** [Ross-Patterson/Portals-Desktop-Organization#320]
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### What is the enhancement/feature you would like to see?

It would be great if you could hide down, so that you could have portals along the bottom of the desktop that when hidden/collapsed would roll down, and when opened would roll up, instead of the current behavior which is the opposite.

**Comment by Ross-Patterson** [comment]
You can do this, just set the header position to bottom and you'll be good to go!

**Comment by jerquiaga** [comment]
That's great! Sorry for missing this in the documentation!
