### ISSUE TITLE
BUG: Portals on 2nd monitors are vanishing on click

### ISSUE THREAD

**Issue by Tom08156** [Ross-Patterson/Portals-Desktop-Organization#322]
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### Version

3.3.0.9

### Operating System

Windows 11

### What happened?

Very cool program/application.
But quite often portals on my second monitor vanish, if I try to click an icon within that portal.
They re-appear after another click (anywhere: Inside the vanished portal, outside of the portal, at monitor 1 or monitor 2)
But you need a multitude of clicks to start a program in that portal.
Seems to get better once I opeen the Portals program itself.

### Steps to Reproduce

Click onto an icon into a portal located at the second monitor.

### What would you expect to happen?

Open the program that is linked.
But the portal vanisehs/is gone. Until you do another mouse-click.

**Comment by Ross-Patterson** [comment]
See here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/issues/101#issuecomment-1523977037

**Comment by Tom08156** [comment]
Dummy portal, invisible, at the bottom of the list => perfectly works - thank you!
