### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by laceyian** [Ross-Patterson/Portals-Desktop-Organization#324]
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### Version

3.3.0.9

### Operating System

Windows 11

### What happened?

I am using Portals on a laptop. Sometimes I plug the laptop into multiple extra monitors at work. When I return home and open the laptop with no extra monitors, the portals are off the screen. As far as the program is aware the portals are open, I can open the setting window and check they are shown. But they are somewhere off the screen and I can't access them. 
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/173674875/2390f67a-5b0c-44b0-a77e-cb9ce18e229a)

### Steps to Reproduce

Have Laptop open with multiple monitors, use portals. Shut down laptop and start again with no extra monitors connected.

### What would you expect to happen?

Ideal would be the software would check if there is only one monitor and ensure the portals are showing on that display. thanks

**Comment by Ross-Patterson** [comment]
You need to use the Display Setups and Layouts features.

Save a Display Setup for each setup you have. 
Create a layout for each setup. 
Assign each layout to its respective Display Setup and set it to auto-apply when a display change is detected.
