### ISSUE TITLE
FEATURE REQUEST: Browse a Folder shortcut

### ISSUE THREAD

**Issue by the-phuctran** [Ross-Patterson/Portals-Desktop-Organization#372]
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### What is the enhancement/feature you would like to see?

Every time I click the shortcut of a Folder it opens in a new File Explorer window, I expect the program can browse folder shortcuts like doing with real folders and can only open in a File Explorer window if I click while pressing the Ctrl.

**Comment by Ross-Patterson** [comment]
Turn on "Navigate Within Portal":
![image](https://github.com/user-attachments/assets/43df9ea5-a864-47e0-aaf6-1d98651bf3a0)
