### ISSUE TITLE
FEATURE REQUEST: Double click on Desktop to hide any Portals.

### ISSUE THREAD

**Issue by the-phuctran** [Ross-Patterson/Portals-Desktop-Organization#373]
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### What is the enhancement/feature you would like to see?

I would like to hide all the portals on desktop when double mouse click so that it will make sense with other program that hide icons on Desktop on double mouse click too.

**Comment by Haitch-1** [comment]
this is already a feature
Customize > App Settings > Double click desktop to show/hide all portals
![image](https://github.com/user-attachments/assets/86db907b-87d4-4ce2-aa69-3fb05ba8e25c)
