### ISSUE TITLE
Feature Request: Support F2 Hotkey to rename selected icon

### ISSUE THREAD

**Issue by reffu42** [Ross-Patterson/Portals-Desktop-Organization#38]
**Is your feature request related to a problem? Please describe.**
While organizing my desktop icons or adding a new shortcut, I often need to rename them. I can right-click an select rename, but that's a pain if using the keyboard instead of the mouse to navigate.

**Describe the solution you'd like**
When an icon in a portal is selected, hitting F2 should show the input for renaming the icon.

**Additional context**
This is a standard Windows Explorer hotkey, so it would be really great if Portals supported it as well.

**Comment by Ross-Patterson** [comment]
This is now implemented and available in v2.1.0.6
