### ISSUE TITLE
Right click near edge of icon does not bring up icon-specific menu

### ISSUE THREAD

**Issue by reffu42** [Ross-Patterson/Portals-Desktop-Organization#39]
**Describe the bug**
Right-clicking an icon normally brings up the icon-specific menu (Open, Open File Location, etc...). If you right click near the edge of the icon, it brings up the background menu (new, paste) instead, even though the icon is still highlighted.

**To Reproduce**
1. Have a Portal with one or more icons 
2. Hover over an icon
3. Right click near the edge (but inside) of the highlighted box around the icon
4. BUG: Background menu is opened

**Expected behavior**
Right clicking anywhere inside the highlighted box for the icon should present the icon's right-click menu, not the backgrounds. Alternatively, shrinking the highlighted box to fit the bounds of the right-click "hitbox" would also work.

**Screenshots**
![image](https://user-images.githubusercontent.com/1823982/180472395-bc886fe3-cf17-4708-afa2-990ee394e7e5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2

**Comment by Ross-Patterson** [comment]
Thanks for reporting, i'll look into it.

**Comment by Ross-Patterson** [comment]
I have fixed this in the next release.

**Comment by Ross-Patterson** [comment]
This is now available in released version 2.1.0.6
