### ISSUE TITLE
Since the last update, 2.1.05, when I to open software that requires credentials. It revert to no loadeing those redentials. If I go to the oprtals folder where the shortcut resides, the same item will open up correctly. 

### ISSUE THREAD

**Issue by JesPir** [Ross-Patterson/Portals-Desktop-Organization#41]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JesPir** [comment]
Since the last update, 2.1.05, when I to open software that requires credentials. It reverts to not loading those credentials. If I go to the portals folder where the shortcut resides, the same item will open up correctly. The example I have posted is a spreadsheet. Opened from the Portal and also opened from the Portal folder. This happens regardless of Microsoft Software and Also happens with Autodesk Cad software. Basically anything that requires some sort of credentials. 

![Screenshot 2022-07-25 080143](https://user-images.githubusercontent.com/109969002/180795777-b3368212-e5ce-4b5f-bdfe-558e57a1181b.png)

OS: Windows 10
Vers: 21H2
Build: 19044.1826

**Comment by Ross-Patterson** [comment]
Ahh, this is an unwanted side effect of a change I made to fix #16.

Will look into it.

**Comment by JesPir** [comment]
Thank you sir. So far I am loving this Portals you have written. I used to get poked fun of because of the amount of icons on my desktop. Now I look like I am organized.

**Comment by Ross-Patterson** [comment]
I am actually unable to replicate this problem unfortunately. Is this happening consistently for you, even after restarting?

**Comment by Ross-Patterson** [comment]
Closed due to no response.
