### ISSUE TITLE
Feature request: Icon size customization per-portal

### ISSUE THREAD

**Issue by Noahitis** [Ross-Patterson/Portals-Desktop-Organization#42]
**Describe the solution you'd like**
I'd like to be able to adjust the icon size for each portal rather than changing it globally. There are overrides for most other customizations but not the icon size.

**Additional context**
This feature is available on nimi places, I attached an example of it. I switched to Portals because of nimi places randomly crashing, Portals seems much more stable and customizable with this being the only exception
![Screenshot (26)](https://user-images.githubusercontent.com/67803024/183268327-56001f4c-c21f-4dcd-ab53-082da3c7ba2c.png)

**Comment by Ross-Patterson** [comment]
This should be easy to do, I will include in the next update.

**Comment by Ross-Patterson** [comment]
This is now implemented and available in v2.1.0.6
