### ISSUE TITLE
Unhandled Exception when clicking "Open File Location" and not running as administrator

### ISSUE THREAD

**Issue by reffu42** [Ross-Patterson/Portals-Desktop-Organization#43]
**Describe the bug**
If Portals is running as the current user, right clicking a program icon in a portal and choosing "Open File Location" causes an unhandled exception error and Portals then crashes. If portals is run as administrator, this does not occur.

**To Reproduce**
1. Run portals (not as administrator)
2. Create a portal with an icon for an app located in Program Files or another "protected" folder
3. Right click the icon and choose "Open File Location"
4. BUG: Portals crashes with an error message

**Expected behavior**
The location that the icon/shortcut refers to is opened in a new explorer window without crashing.
An alternative would be to require/request Portals to have administrator access by default, so that there are no issues accessing protected folders

**Additional context**
Log file is attached. Error says the issue is a permissions issue accessing a folder/file.

[portals_crashlog_2022-08-07_20-52-16_1186590.log](https://github.com/Ross-Patterson/Portals-Desktop-Organization/files/9277930/portals_crashlog_2022-08-07_20-52-16_1186590.log)

**Comment by Ross-Patterson** [comment]
Thanks for uploading the crashlog, I will investigate.

**Comment by Ross-Patterson** [comment]
Unfortunately there isn't much I can do if access is denied by the Os. I have made Portals throw an error message instead of crashing.
