### ISSUE TITLE
Feature request: Auto-add files, folders and program links to specific portals

### ISSUE THREAD

**Issue by enoversum** [Ross-Patterson/Portals-Desktop-Organization#44]
**Is your feature request related to a problem? Please describe.**
At the time being, any new file that is being created or pasted onto the Desktop does not automatically get added to a portal. Just like with Fences, it would be lovely if a file, folder or program shortcut would auto-move itself to a folder specified. 

**Describe the solution you'd like**
Some rule-based settings would be awesome, so I could specify that e.g. _files_ always get added to Portal 1, _folders_ auto-move to Portal 2, and _program shortcuts_ land in Portal 3. 

**Describe alternatives you've considered**
I could only think of configuring my screenshot app to auto-store its created files in a portal's Desktop folder, but that would not help for any items created by setup programs which I cannot control, and would also make pasting files or folders onto my Desktop mindlessly and still have them auto-appear in a portal impossible. 

**Additional context**
Since you're relying on actual folders to store content in portals, this might possibly be difficult to achieve, as contrary to Fences, elements would have to be moved physically to a portal = sub-folder on a Desktop.

**Comment by Ross-Patterson** [comment]
This is possible, I could listen to the users Desktop for new files then move them based on a ruleset.

I am always hesitant about manipulating the users desktop, as this was never the intention of the Portals app.

But I will certainly consider it.

**Comment by enoversum** [comment]
Hey @Ross-Patterson, I understand that, again, your Portals is working differently from Fences. Whereas Fences creates some kind of 'virtual' Desktop, and everything is as it was before when unloaded, Portals uses _actual_ folders for its management. But who am I telling, thanks for considering my idea :)!

**Comment by Ross-Patterson** [comment]
I had a think about this again and have decided I am not in the game of taking control of peoples desktops - so I will not be implementing this.
