### ISSUE TITLE
Feature request: Hide portal folders

### ISSUE THREAD

**Issue by enoversum** [Ross-Patterson/Portals-Desktop-Organization#45]
**Is your feature request related to a problem? Please describe.**
As your portals depend on physical folders, by default these folders show beside the actual folders. 

**Describe the solution you'd like**
An option to hide the actual folders for the portal, so I only see my portals and possible stray elements that I didn't throw into them. 

**Describe alternatives you've considered**
No idea :) .

**Comment by Ross-Patterson** [comment]
I would suggest just moving your Portal folders to somewhere else other than your desktop, where they are out of sight i.e. Documents

**Comment by enoversum** [comment]
Hi @Ross-Patterson, just saw you replied to my requests. I think I'm just a bit spoilt by Fences, which doesn't need to configure folders outside your Desktop, but lets you start the app and has your Desktop organised, including new files that are being added. 
I understand the concept of Fences might be a completely different one, and I'm happy to watch your app grow and develop 😊! Moved it all to a different folder already, so that's doable. It's just easier and approachable if you'll just get your Desktop arranged in portals right away and without fiddling 😉.
