### ISSUE TITLE
Quicklook Compatibility

### ISSUE THREAD

**Issue by Somastro** [Ross-Patterson/Portals-Desktop-Organization#48]
Is there any way for compatibility with Quicklook which opens a preview of files files and folders like in MacOS. Folders and files in Portals do not currently work with Quicklook. Many thanks and have a pleasant day.

Link to QuickLook github page: https://github.com/QL-Win/QuickLook

**Comment by enoversum** [comment]
+1 for this. I am using Seeer instead, and I'm also missing using the space bar to preview a file inside a Portal.

**Comment by Ross-Patterson** [comment]
It is unlikely that I will manage to get compatibility with these because I assume that both QuickLook and Seer are both hooking into the Windows API to get what is currently selected, and preview that. So it will only work in windows explorer/desktop.

I wonder how hard it would be to implement something similar, but I don't want to bloat the portals application too much.

**Comment by enoversum** [comment]
Well, I'm certainly no programmer, but Files, an alternative explorer for Windows, managed to implement support for Quicklook not too long ago, so I would guess there are ways to implement it. 

I think the main thing for many, including me, is having said farewell to Fences and hoping to find a worthy contender in Portals, so we're kind of hoping you'd implement features many are used to already from Fences. That's unfortunately not the best way to start off your own app, I suppose...

**Comment by Somastro** [comment]
looking at the QuickLook github, they said their compbatibility issues with fences came from the icons in folder view being non-standard shortcuts, while normal fences for desktop items work with QuickLook, so I'm guessing making compatibility with QuickLook would involve a very bloated work around or redesigning alot of the program? thanks for reading my request anyways, have a nice day

**Comment by Ross-Patterson** [comment]
Turns out its possible to add support for both Quicklook and Seer.

I will work on this for a future version.

**Comment by Ross-Patterson** [comment]
Quicklook and Seer integrations now added as Preview Features in v3.0.2.0.

Switch to the beta channel in the settings to get that version and try it.
