### ISSUE TITLE
Show Desktop button/shortcut hides portals.

### ISSUE THREAD

**Issue by ethanrw** [Ross-Patterson/Portals-Desktop-Organization#5]
**Describe the bug**
Using "show desktop" button on far right side of taskbar, or show desktop shortcut (win+D) shows desktop but portals are hidden.
Opening any program then causes portals to reappear (eg opening explorer, spotify, whatever).

**To Reproduce**
1. Show desktop via taskbar button or Win+D

**Expected behavior**
Desktop shows with portals visible.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H1

Other than that I have no issues and the software is excellent, cheers!

**Comment by Ross-Patterson** [comment]
@ethanrw Have you updated to the latest version (2.1.0.3)? I fixed this issue in that release.

**Comment by Ross-Patterson** [comment]
Ok so turns out this isn't working how I thought, and it seems it is near impossible to get this to work well (after many hours on StackOverflow).

I will keep researching though...
