### ISSUE TITLE
Hotkey to hide portals

### ISSUE THREAD

**Issue by Wolfen420** [Ross-Patterson/Portals-Desktop-Organization#55]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
I would like to be able to:

-Double click the desktop to hide all portals

**Describe alternatives you've considered**

- Assign a hotkey to hide/unhide all portals

**Additional context**
As you may be aware of the original requests to hide portals, Stardock Fences allows you to double-click the desktop. The current implementation in Portals is either to hide all from the main portals home menu or to individually hide each portal. It would be more efficient to allow for double-clicking the desktop or assigning a hotkey to hide/unhide all portals.

**Comment by Ross-Patterson** [comment]
Double click on desktop is cumbersome to implement, a key-combination would probably be easier and more lightweight.

It is something that I definitely want to add, one way or another. So it will come maybe in the next release.

**Comment by Wolfen420** [comment]
Understood and much appreciated. Thanks for the consideration!

**Comment by Ross-Patterson** [comment]
This is now implemented and available in v2.1.0.6 (needs to be turned on in settings) - went for double click desktop route.

**Comment by Wolfen420** [comment]
This is so wonderful! Thank you! Goodbye Stardock fences.
