### ISSUE TITLE
Enter on a selected icon does nothing inside a portal

### ISSUE THREAD

**Issue by Chronon88** [Ross-Patterson/Portals-Desktop-Organization#56]
I have a mini laptop with a touch screen. I often select something on the desktop by touching the screen then hit enter to open, this is because touch screens are a bit inaccuratse when it comes to double click and thus the double touch success rate is less than 100%, However enter does nothing within a portal and it is really bugging me,

Please make enter to be the default Windows function, which basically double clicks the selected icon.

Currently icons area neatly organized but Portals is making the desktop icons less useful and harder to use because I either have to use the trackpad, just search the start menu like I used to or awkwardly try to double tap the touch screen while preparing to try up to three times...

Good software otherwise; thanks!

**Comment by Ross-Patterson** [comment]
@Chronon88 I will add it to the backlog, this is an easy feature to implement. Not sure yet when I am planning to release another version, but it will happen eventually.

**Comment by Ross-Patterson** [comment]
This is now implemented and available in v2.1.0.6
