### ISSUE TITLE
other payment methods than credit card

### ISSUE THREAD

**Issue by jkischel** [Ross-Patterson/Portals-Desktop-Organization#57]
This feature request isn't directly about a technical feature in the software.

When purchasing a licence, it seems that the only payment method is a credit card. Well... I don't have a credit card, so even though I _want_ to pay somthing, I _can't_.

Although this rather seems to be a kind of donation than a real purchase, I'm not sure if it's really necessary to add taxes for the price (at least, here in Germany you don't have to pay VAT for a gift).

**Comment by Ross-Patterson** [comment]
Hi, I think you found it, so thanks for the donation! It's much appreciated.

For anyone else wondering, you can donate via PayPal also, the link is on the "About" section of the main settings window:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/66630787/193636746-fdf70991-97ce-479e-89ef-575524317e80.png">

There is also a link at the top of the GitHub page - "Sponsor":
<img width="82" alt="image" src="https://user-images.githubusercontent.com/66630787/193636935-c347b275-329c-42ea-8bf3-e1242d271b72.png">

Or here is the direct link:
https://www.paypal.com/donate/?hosted_button_id=XZCXSUCQG6WE8
