### ISSUE TITLE
Update Keeps Looping

### ISSUE THREAD

**Issue by votata01** [Ross-Patterson/Portals-Desktop-Organization#62]
**Describe the bug**
Currently running version 2.1.0.5. An update is available to version 2.1.0.6. The installation process completes in full without any error, however portals does not appear to update to the latest version and each time the PC is restarted Portals will keep trying to update or it can be started by searching for updates within the app.

**To Reproduce**
As described, allow installation of update to complete. Open Portals and check version number which is the same, check for updates and try to perform update. Installation completes, but Portals does not update. This is the loop that it is stuck in.

**Expected behavior**
Portals to update and recognise the update.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox
 - Version 106

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ross-Patterson** [comment]
Hi, I am not able to replicate this behaviour, and can already see 500+ people already using 2.1.0.6.

Can you please provide a screen recording, or step by step with screenshots of what you are doing?

Thanks!

**Comment by votata01** [comment]
Video 1 is the initial opening of Portals and selecting update.

Unseen is the Windows "Do you want to allow this app to make changes", which I selected Yes.

Video 2 is the update process and re-opening of Portals once the update has completed. This is the update loop that I am stuck in.

**Comment by Ross-Patterson** [comment]
@votata01 
Please check two things:

- Your install location:  E:\Program Files\Portals\Portals
   There is folder duplication here.
   Check the Portals.exe version:
   
![image](https://user-images.githubusercontent.com/66630787/206683957-969217d9-02e4-49a7-bfef-ea43c3dc4aa3.png)


- Check where the shortcut on your desktop/taskbar is pointing to.

I think you have v2.1.0.5 installed, and you are installing v2.1.0.6 to a **different location**. And the shortcuts on your desktop/taskbar are still pointing to the old version.

**Comment by Ross-Patterson** [comment]
Closed due to inactivity.
