### ISSUE TITLE
Path edit; sub portals

### ISSUE THREAD

**Issue by Alexnoj** [Ross-Patterson/Portals-Desktop-Organization#63]
- option to Path edit.
- option to create sub portals.  (I add img for example)
- 
![image](https://user-images.githubusercontent.com/30004592/197326027-56b81014-69f1-41b3-89d4-cf6a2a57f443.png)

**Comment by Ross-Patterson** [comment]
**Path Edit:** I will consider.
**Sub Portals:** Won't Happen (at least in the way you show above) - I am considering "tabbed portals", but that is likely a long way off.

**Comment by Ross-Patterson** [comment]
Duplicate of #111
