### ISSUE TITLE
Ability to change icon spacing or space vetween icons. Currently the icons too closely packed together making them feel very cluttered. 

### ISSUE THREAD

**Issue by GlitchGamingX** [Ross-Patterson/Portals-Desktop-Organization#64]
The icons feel way to cluttered together. It would be nice to have more space horizontally as well as bit vertically between each icon. 

Screenshot here shows icons appearing too cluttered together. 
![image](https://user-images.githubusercontent.com/37849930/197463910-273f470c-1c74-4123-a621-97fa73a50bcc.png)

A way to adjust the spacing between icons much like the screenshots you have on your website home page.

**Comment by bipolarbunny** [comment]
I am having the same issue. Seeing others pictures, it seems it shouldn't be looking like this. I'd love for this feature to be added.

![example](https://user-images.githubusercontent.com/116678045/197862136-f3e23f91-07b3-4008-b171-0fed5d81ea18.png)

**Comment by Ross-Patterson** [comment]
Next release will come with the ability to chose your own margin value for items.

**Comment by Ross-Patterson** [comment]
Hi There,
I have included this feature in v3.0.0.0 which I have made available for early access here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/107

Thanks!
