### ISSUE TITLE
Global keyboard shortcut to bring portals to front

### ISSUE THREAD

**Issue by detlefs** [Ross-Patterson/Portals-Desktop-Organization#65]
**Is your feature request related to a problem? Please describe.**
If I have a lot of windows open, I can't access the icons on my desktop

**Describe the solution you'd like**
I would like to temporarily have all icons above of all windows. It should be possible to use drag & drop to drag icons to any window (while shortcut is held). I think, a global shortcut-key like Ctrl+Win+Space would be perfect for this

**Describe alternatives you've considered**
I tried other tools, but they lack of the other great features of Portals

**Additional context**
n/a

**Comment by Ross-Patterson** [comment]
I think I could make this work.

**Comment by Ross-Patterson** [comment]
Hi There,
I have included this feature in v3.0.0.0 which I have made available for early access here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/107

Use CTRL+SHIFT+SPACE to bring to top, press again to send back to bottom.

Thanks!
