### ISSUE TITLE
Path Bug

### ISSUE THREAD

**Issue by Pouetpouet01** [Ross-Patterson/Portals-Desktop-Organization#66]
**Describe the bug**
The saved path selecting a network drive contain two "\" after the drive letter instead of one. This is leading to a wrong portal path and nothing is shown inside the portal.

**To Reproduce**
1. Go to portal setting --> Home
2. Select the root of a network drive for a new portal
3. Enter a portal name
4. Click on "New portal and folder"
5. Scroll down to see the path of the new portal folder
6. The new portal folder path is structure that way : DriveLetter + ":\\\\" + NewFolderName

**Expected behavior**
The new portal folder path should be structure that way : DriveLetter + ":\\" + NewFolderName

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox (but it does not matter since i use desktop application
 - Version of the portal desktop application : 2.1.0.6

**Temporary solution**
Changing the path in the files below solve the issu : 
C:\Users\osurcouf\AppData\Local\Portals\portals.ptl
C:\Users\osurcouf\AppData\Local\Portals\savedlayouts\ All files

**Comment by Ross-Patterson** [comment]
Is this still happening for you in the latest version?

**Comment by Ross-Patterson** [comment]
No response
