### ISSUE TITLE
Multi monitor setup with changing Primary monitor

### ISSUE THREAD

**Issue by S0und** [Ross-Patterson/Portals-Desktop-Organization#67]
**Describe the bug**
First i would like to ask a question. What is the point to setting a Portal to a specific Display, and then ignoring this setting and just using the overall screen resolution? 

This is my default setup, 1080p - 4k - 1080p vertical. My portals are set to Display 2 (0,1,2)
![image](https://user-images.githubusercontent.com/1266308/197788298-66cd3152-f95c-4b4c-994d-0790fe025769.png)

The moment i either set my Left 1080p screen primary 

![image](https://user-images.githubusercontent.com/1266308/197792141-19f251b5-56bd-46c4-9d2d-3f49f707ab4a.png)

OR if i set my 4k to 1080p, my portals are shifting off from my vertical monitor. 

![image](https://user-images.githubusercontent.com/1266308/197789237-0c9e8671-14f1-4e65-bba2-ebb8e437bdf0.png)

Normally i don't set my 4k monitor to 1080p, i'm just using it as an example. What i actually do a lot, is setting my left 1080p monitor (gaming monitor) to primary to play games. In this case, the portals are shifted to the right, so they're not visible anymore, and i'm unable to access them unless i switch back to my default setup.

I even change my portal positions to based on percentage in hopes that they would translate better when i switch between primary monitors. 

**To Reproduce**
1. place the portals where you want
2. change one of your monitor's resolution in a multi monitor setup

**Expected behavior**
If i'm able to set my portals to a specific monitor when i expect them to say on that monitor regardless to the settings of my other monitors. 

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 19044.2130
 - Version 2.1.0.6

**Comment by Ross-Patterson** [comment]
Different monitor setups, screen resolutions, DPI settings and scaling settings have been the bane of my life for this program unfortunately.

Have you tried the "Relative Positioning" option? (Which by the way is a very experimental feature).

Long term I think I will change my strategy on handling all of these different potential setups, the new strategy will probably be:
1. Using the "Saved Layouts" feature, any layout that is saved will remember its monitor setup.
2. When monitor setup changes, if that layout is marked as "Auto-Apply", Portals will automatically apply that Saved Layout if the new monitor setup matches.
3. Users then have a Saved Layout for each monitor setup, which they can mark as Auto-Apply.

**Comment by S0und** [comment]
@Ross-Patterson  Yes, as you probably saw on my screenshots i tried and hoped that "Relative Positioning" will solve my problem. Unfortunately it didn't, because even if i set the display and the % for the Portal positions, when i change the Primary Display, everything shifts around. 

If i use don't use the feature, then this is what happens when i change the primary monitor:
![image](https://user-images.githubusercontent.com/1266308/200185277-265d94ae-ffcb-4565-9edd-1aa011d04662.png)

Pretty much the same thing.

**Comment by Elektrik1** [comment]
Related to #7, same problem with DPI scaling.

**Comment by Ross-Patterson** [comment]
I am removing the "Relative Positioning" option. It's too bloaty and doesn't really work.

I have taken a new approach as follows:
1. You save all of your different display setups in the app.
2. You save a Layout for each saved display setup.
3. When Portals detects a display change, it will check if the new display settings match a saved one and if it has an associated layout - it will be applied.

**Comment by Ross-Patterson** [comment]
New approach is implemented in v3.0.0, give it a try
