### ISSUE TITLE
Icon scaling

### ISSUE THREAD

**Issue by zigzerg** [Ross-Patterson/Portals-Desktop-Organization#69]
**Is your feature request related to a problem? Please describe.**
If an icon of the required size does not exist in the icon group, a different sized icon will be displayed.
![Untitled](https://user-images.githubusercontent.com/45770260/199173090-3b890656-2054-4dac-962c-0dc929ff33f6.jpg)

**Describe the solution you'd like**
Please implement the feature to scale up and down as in Windows.

Sorry for the machine translation.

**Comment by Savasdotexe** [comment]
I've added a folder with images or PDF files, I'd like to be able to increase the icon size, similar to how you can increase it with windows explorer to "extra large icons", but maybe go further and make it customizable to go larger than that too.

**Comment by Ross-Patterson** [comment]
Icons are pulled direct from Windows ImageList and cannot be scaled up.

You can change the size of the icons to Extra Large in the settings - but icons without extra large icons in the windows ImageList will remain small
