### ISSUE TITLE
Relative positions on different screens

### ISSUE THREAD

**Issue by Elektrik1** [Ross-Patterson/Portals-Desktop-Organization#7]
Portals is definitely awesome!
I would like to suggest to implement a feature to save relational position of a portal. 
Why? I do create a portal at top right edge with X coordinate 2000 on 4K screen with 150% scaling. Later I do connect to that machine via Remote Desktop with FHD screen and 100% scaling - the portal is outside of the screen and the only way to get it back is to manually adjust X coordinate.
Later on when I switch back to 4K screen - the portal appears in the middle of the screen.

Would be nice to have a feature of X/Y coordinate to be set as a relative value like (0.9 of screen width), or implement an automatic recalculation based on scaling and screen dimensions.

**Comment by Ross-Patterson** [comment]
@Elektrik1 , the easiest option to implement would definitely be window width/height based relational positioning i.e. 0.9 of screen width.

I will definitely add it to the list for implementation (for both position and size).

Thanks for the suggestion!

**Comment by Ross-Patterson** [comment]
This is now available in v2.1.0.4. Feedback is appreciated as always.

**Comment by Elektrik1** [comment]
Thanks for the bump. How could it be used? Some keyword like 'screen_width' or I am missing some new button somewhere?

**Comment by Elektrik1** [comment]
Thank you for your work.
I have tested it, unfortunately, the recalculations are a bit off.
How it looks on 1650x1050 100% scaling screen:
![sshot-20220417-231245](https://user-images.githubusercontent.com/1433249/163730762-310374a2-b4fd-449f-b224-281dc283b6f0.png)
and how it looks on the same machine but with 1920x1080 175% scaling:
![sshot-20220417-231354](https://user-images.githubusercontent.com/1433249/163730787-26ba8f35-c5b2-4c28-935f-7dc6774ff0dd.png)

![image](https://user-images.githubusercontent.com/1433249/163730808-4e123b71-d37d-4ee0-823c-6bee47ccad95.png)

As you can see I always use portals in very right edge of the screen.

I think in my case it would be easier add another option to anchor the portal to top-left ant top-right edge, then calculate relative portal position according to that option (in my case top-right: X=screen_width-portal_width), but I assume that portal_width also changes with scaling/resolution.

**Comment by Ross-Patterson** [comment]
I haven't taken into account scaling, need to do a bit more research onto how scaling works pixel-wise, i'll investigate and see if I can get it working better with scaling.

**Comment by Ross-Patterson** [comment]
I have made some improvements to the relative positioning to better handle scaling, let me know what you think.

**Comment by Elektrik1** [comment]
Any news here? After recent monitors upgrade this issue is really annoying, constantly connecting to the computer with portals installed through RDP via different monitors (FullHD, 2K, 4K) the menu is always off, when switching from 4K to FHD the widget is completely otside of monitor bounds, therefore making it unusable in such case.

**Comment by Ross-Patterson** [comment]
I am removing the "Relative Positioning" option. It's too bloaty and doesn't really work.

I have taken a new approach as follows:
1. You save all of your different display setups in the app.
2. You save a Layout for each saved display setup.
3. When Portals detects a display change, it will check if the new display settings match a saved one and if it has an associated layout - it will be applied.
