### ISSUE TITLE
Bigger Icons

### ISSUE THREAD

**Issue by EllieBree** [Ross-Patterson/Portals-Desktop-Organization#71]
Issue:
I have portals for folders that I use as moodboards and picture collections on a 4K screen. Even at the "Extra Large" size, thumbnails are too small to make out what the content is.

Solution:
Options for bigger icon sizes. Or the added possibility to manually define the size of the thumbnails in pixels.

**Comment by Ross-Patterson** [comment]
Hi @EllieBree - the icons are pulled from the windows icon list for that application. 

The largest size is 256x256. Making any larger would just make them pixelated.
