### ISSUE TITLE
Resize Icons in Portal

### ISSUE THREAD

**Issue by billinmex** [Ross-Patterson/Portals-Desktop-Organization#72]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I cannot resize icons in a portal like I can on the desktop ([right click>view>small icons or crtl+shift+4 on windows11)

**Describe the solution you'd like**
resize icons within a portal - large, medium, small

**Describe alternatives you've considered**
not using portals

**Additional context**
none

**Comment by Ross-Patterson** [comment]
Its in the settings.

![image](https://user-images.githubusercontent.com/66630787/206682364-63417cd4-6ae2-4228-8b65-4e2124377c78.png)

It would be inconsistent to add only this one setting to the Right Click context menu.
