### ISSUE TITLE
Currently it is not possible to open a portal from an existing folder.

### ISSUE THREAD

**Issue by luukvanderweide** [Ross-Patterson/Portals-Desktop-Organization#73]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ross-Patterson** [comment]
It very much is possible:
![image](https://user-images.githubusercontent.com/66630787/201644340-90e6755b-a434-4f17-a6b4-0785cbe2d397.png)
