### ISSUE TITLE
Open portal from existing folder. 

### ISSUE THREAD

**Issue by luukvanderweide** [Ross-Patterson/Portals-Desktop-Organization#74]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by luukvanderweide** [comment]
Currently it is not possible to open a portal from an existing folder. A current workaround is to create a new portal and folder, and move all files from the existing folder to it. Adding a feature to also be able to open portals from existing folders would solve the problem. This could be very usefull for temporarily having a portal to a folder you have to access a lot for a while.

**Comment by Ross-Patterson** [comment]
It very much is possible:
![image](https://user-images.githubusercontent.com/66630787/201645245-b5d04901-8692-42cc-9e11-203484524bf2.png)
