### ISSUE TITLE
Full transparency unless moused over

### ISSUE THREAD

**Issue by mad-ph33r** [Ross-Patterson/Portals-Desktop-Organization#75]
**Is your feature request related to a problem? Please describe.**
Fences are always visible regardless of settings.

**Describe the solution you'd like**
I'd like the ability to set them to be fully transparent unless the _fence_ is moused over, not just the title.

**Additional context**
This is the main function that I used Stardocks Fences for.

**Comment by Ross-Patterson** [comment]
With the framework I am using, when a window is fully transparent it does not register mouse events (including Mouse Over). So this would be hard to implement without adding a calculation every time the mouse moves a pixel to see if the mouse position is within the bounds of any portal.

This would add significant bloat, and therefore this is unlikely to happen.
