### ISSUE TITLE
Add possibility to hide application names

### ISSUE THREAD

**Issue by pr3dd1** [Ross-Patterson/Portals-Desktop-Organization#79]
Names below icons are not always necessary, eg. if we are using very large icons for games.

Add an option to hide names below icons, so that only icons will be visible in the folder view. The space reserved for names should be removed in this case.

**Comment by Ross-Patterson** [comment]
Should be possible - I will add it to the backlog

**Comment by pr3dd1** [comment]
Thank you

**Comment by Ross-Patterson** [comment]
Hi There,
I have included this feature in v3.0.0.0 which I have made available for early access here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/107

Thanks!

**Comment by pr3dd1** [comment]
Thants great to hear, I will check it out

Thanks

4 Mar 2023 19:35:37 Ross Patterson ***@***.***>:
