### ISSUE TITLE
Option to expand/maximize folder containers from the left/right of titlebar (+ any potential extra quirks)

### ISSUE THREAD

**Issue by Marcassius** [Ross-Patterson/Portals-Desktop-Organization#8]
I figured I'd add some more feature requests here to try to help improve the app after finding out about the developer's thoughtful & responsive reply to a previous feature request/bug-fix email I sent some time ago. I'll see if I can occasionally submit stuff I think could be useful in the hopes of having this program eventually featured in bigger communities!

     I find that a majorly-overlooked feature enhancement opportunity in software similar to fences such as this are unorthodox mechanisms of placement within the desktop's screen space. This could be an option implemented for each individual folder's respective menu, similar to the "Titlebar on Bottom" option. Being able to open containers/icons out from the sides of a folder portal's titlebar both serves an aesthetic, yet also practical flexibility use-case. For instance, this would make the organization of folder portals less messy when you can also orient & place titlebars alongside EVERY edge/side of the desktop monitor screen, this is a major bonus for minimalists who want icons/folder-portals to be as far away from the center of the screen as possible. Titlebars also can take up a lot of horizontal space, (assuming you want the title to be readable &/or the icons displayed a certain way) so opting for vertical space instead allows for titlebar placement to be easier to work with. Lastly, there's a high novelty value for users who used similar, but less user-friendly software. For instance, I can see this being a stand-out feature attracting new eyes over a demonstration post on a rainmeter-related subreddit. 
     
     The only drawback I could think of would be that this feature would probably result in the titlebars being read horizontally, but I think this is fairly minor, as it's still readable enough & easy to get used to. I've seen many instances of rainmeter skins where certain app-launchers (that function like folder-portals) have nothing labeled for their titlebars, (or at the most, an icon) so this wouldn't be an issue at all for them. One possible workaround for this could entail making the 'TITLE' segment of the titlebar only appear after maximizing the folder container, (only when the horizontal titlebar toggle is enabled) where it can be placed at the top of the maximized container area (perhaps within some empty space only allotted for horizontal container titles). At the same time, titlebar itself would be kept in the horizontal orientation whether the portal is minimized or maximized.
     
     Additionally, I think having a toggle for a basic (but fairly quick) "slide-out" animation for maximizing/minimizing may enhance the aesthetic flexibility of portals, similar to certain app-launchers implemented within many rainmeter skins. I'm sure there's more that can be done on the aesthetic route, although that increases the risk of unnecessary feature-bloat, doubly so if this program is designed to have a greater emphasis on practicality over aestheticism. Therefore, I'm more interested in the possible implementation of the practical route use-case, described above.

**Comment by Ross-Patterson** [comment]
@Marcassius thanks for keeping the feedback coming. From reading your request i'm trying to extract the requirement, what I am thinking is something like this:
![image](https://user-images.githubusercontent.com/66630787/162686556-847dd290-a69c-4a40-8d10-ae6577100be1.png)

Is this what you mean? A picture speaks a thousand words, if you could mock-up something it would help a lot.

As for the slide in/out animation, this _should_ be fairly easy to implement, i'll add it to the list.

**Comment by Marcassius** [comment]
Actually yes, that image is exactly how I envisioned the concept! I mocked-up the mirrored version of this, for when the user prefers to place titlebar on the right-side of the container as opposed to the left-side: (Clicking on the below imgur links redirects to an empty github page, just copy-paste in browser search bar I guess)

[https://imgur.com/a/WCSPtMY](url)

I also made a mock-up of the workaround I described in the original post of this issue for folks who absolutely hate titlebars that have to be read horizontally like that. Doubtful that this is worth doing, but I figured it would be useful just as a reference to picture what I had in mind; perhaps some may request it later on so I tried to think ahead to see what hypothetically could be done. 🤷‍♂️

[https://imgur.com/a/NHPw6RK](url)

**Comment by Ross-Patterson** [comment]
Here is what I have came up with as a first pass:
![image](https://user-images.githubusercontent.com/66630787/163423781-de05eef7-1a26-4c25-acbe-99e75a0134ed.png)

**Comment by agamotto** [comment]
This is a great feature, I have some portals usually collapsed and having the titlebar on left/right side will keep things more tidy.

**Comment by Marcassius** [comment]
Agreed, this looks great!

**Comment by Ross-Patterson** [comment]
This is exactly how I implemented it:
![image](https://user-images.githubusercontent.com/66630787/163725337-a24dda12-1cca-43ea-b45e-f4fc3a4bf8da.png)

It is now available in v2.1.0.4.
