### ISSUE TITLE
portal disappears when I click on it

### ISSUE THREAD

**Issue by ThinkSalat** [Ross-Patterson/Portals-Desktop-Organization#80]
**Describe the bug**
One of my portals constantly disappears
**To Reproduce**

Unsure how but just clicking on a certain portal causes it to disappear - other portals don't have this behavior

**Expected behavior**
clicking portal doesn't disappear it
**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11

new windows 11 install on latest update. I have one portal that doens't exhibit this behavior, and there are only shortcuts inside. The other portal I've created exhibits this behavior and it has folders, exes, etc inside. I am unsure if that's making the difference.

**Comment by ThinkSalat** [comment]
https://imgur.com/k7tNqEb here's what it looks like when it's happening

**Comment by Ross-Patterson** [comment]
I have seen this happen before - you can recreate the portal and it will stop happening. Not entirely sure what is causing it.

**Comment by ThinkSalat** [comment]
It’s really odd. It happens on more than one portal. There should be logs or something that could tell more to help debug. Would be happy to share if they exist On Dec 13, 2022, at 11:35 AM, Ross Patterson ***@***.***> wrote:﻿
I have seen this happen before - you can recreate the portal and it will stop happening. Not entirely sure what is causing it.

**Comment by ThinkSalat** [comment]
I should mention that I've recreated the portal a couple times and it still happens

**Comment by GameIT-Official** [comment]
Same here

**Comment by ashalexemail** [comment]
Same.  
Made a new post before seeing this.

**Comment by ashalexemail** [comment]
> I should mention that I've recreated the portal a couple times and it still happens

+1

**Comment by ThinkSalat** [comment]
I ended up just buying a lifetime subscription to fences. It's cheap,
there's sales, and the time spent trying to debug this already surpassed
the value of free vs $20 haha. Would love to see improvements for others
who are against using fences or paying for it - but just want to point out
that fences is working perfectly for me since I got it and it's a really
good program

**Comment by Ross-Patterson** [comment]
Try upgrading to v3.0.0, I hope this issue will be resolved. We can reopen this one if not.
