### ISSUE TITLE
Dual Screen, portals changing side, random

### ISSUE THREAD

**Issue by DavidOBE** [Ross-Patterson/Portals-Desktop-Organization#81]
**Describe the bug**
Sometime, when I restart my computer or wake it from sleep, the portals will move from one screen to another. It doesn't remain on the screen I created them.

**To Reproduce**
I do not know how to reproduce, it is very random. I want them to remain on screen 1 (per windows). I tried random things to force it back to screen 1 but it didn't work.

     1. Restart
     2. Close and open portals after restart
     3. Wake from sleep

**Expected behavior**
The portal would remain on screen 1.

**Screenshots**
![image](https://user-images.githubusercontent.com/120540768/207497586-8bb50f49-1591-4d31-9cda-17392a49d4ad.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 22H2, 19045.2364

**Additional context**
If that is possible, I propose to add an option in the program to tell which screen # the portal should be on and if that screen # doesn't exist, it should show on screen #1. Also, since some PC could have delays detecting the screens upon bootup or wake from sleep, maybe ensure that all screen are detected before setting the portals on the proper screen, either allowing a delay before showing up the portals (a selectable option for those who don't want this delay to be forced on them).

Thanks for your great tool!

**Comment by Ross-Patterson** [comment]
Try v3.0.0, if this still happens, let me know
