### ISSUE TITLE
Saving a edit

### ISSUE THREAD

**Issue by 2107dra** [Ross-Patterson/Portals-Desktop-Organization#83]
When I open a document in portals and edit it. I would very much like if I could save the file directly. But instead, I have to save it as a new file.

I am sure that it's possible but haven't figured it out yet.

![portals fejl](https://user-images.githubusercontent.com/120632045/207813478-b9945382-10f6-4d5a-82f1-98f4378b1350.JPG)

Kind regards
Dennis

**Comment by Ross-Patterson** [comment]
I have never came across this issue, it looks like you are creating your Portals in "Program Files", maybe this is due to some Admin Permission issue.

Try creating your Portal folders somewhere where Admin Permission isnt required i.e. Documents.
