### ISSUE TITLE
Frequent crashes on startup

### ISSUE THREAD

**Issue by AmyGilhespy** [Ross-Patterson/Portals-Desktop-Organization#84]
**Describe the bug**
Portals crashes on startup over half the time I launch it.  It crashes about 67%-75% of the time.  I assume this isn't the case for most people or you would probably have noticed this and fixed it by now, so if there is anything I can do to help debug please let me know.  It's not a big deal because I can just start it again and eventually it will start, and it doesn't crash once it has started fully.  It takes about 60 seconds of fiddling each time I start my computer of trying to launch it over and over before it works.  I have numerous portals on my desktop, and it crashes mid-way through loading them, usually after 1-3 of them have loaded but not the rest.

**To Reproduce**
1. Launch Portals.
2. It probably crashed.

**Expected behavior**
Portals can start without crashing.

**Screenshots**
![image](https://user-images.githubusercontent.com/120238507/211219815-11ccbbe7-ad38-4229-90e3-0ab368a78e40.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Portals 2.1.0.6

**Additional context**
It also crashes frequently when I click "Exit Portals".

**Comment by AmyGilhespy** [comment]
I wanted to attach my Portals configuration to be helpful but I couldn't figure out how to upload the .ptl files to GitHub, so I shared them with you via Google Drive at the address you have on your contact page.  I hope that was ok.

**Comment by twhiting9275** [comment]
right there with you. This has been going on for a few months now.

Uninstalling and reinstalling is about the only thing that works

Using Windows 11 myself, so it's not a Win10 issue

One thing I HAVE noticed is that the tray icon remains, but you cannot actually relaunch the application.

Also, using task manager to kill it? Yeah, that doesn't work either. It literally does nothing.

**Comment by Ross-Patterson** [comment]
Try upgrading to v3.0.0 - see if it resolves this issue.
