### ISSUE TITLE
Display name for a portal that is different from the folder name

### ISSUE THREAD

**Issue by AmyGilhespy** [Ross-Patterson/Portals-Desktop-Organization#85]
**Is your feature request related to a problem? Please describe.**
I hid my desktop items on the Windows desktop and then made a portal of my desktop folder (to contain the icons to a tidy area).  I wanted to rename the associated portal to something more helpful than "Desktop", but in doing so Portals renamed my entire Windows "Desktop" folder and made a lot of other programs unhappy (like 3 things crashed).  I renamed it back and restarted my computer, and now everything is happy again but I really wanted to change the title of the "Desktop" portal and I don't see a way to do that with the current version of Portals.

**Describe the solution you'd like**
I would like a setting called like "Display name" or something that lets you change the title that shows up for a portal in the portal's title bar without renaming the folder.  This name should be blank by default, and if it is blank then the title should use the folder name.  If the "Display name" property is *not* blank then it should use *that* for the portal's title instead of the folder name.

**Describe alternatives you've considered**
I've considered putting up with the "Desktop" name, which is what I have been doing for 2 months.  I've considered looking up if it's practical to rename the Windows "Desktop" folder in such a way that other programs get the memo, but that seems like too much work for lazy Amy and also some badly-written programs might assume it is called "Desktop" and not check whatever registry key I would likely be changing.  I hid the title bar for that portal for a while, but then the "Desktop" portal didn't look like the other portals and I didn't like that, and also I really do want a title, I just don't want it to be "Desktop".

**Additional context**
If you added this feature then it would additionally be practical to have titles with special characters that Windows doesn't like you to use in folder names.  This would let me name a super important portal "<< Important! >>" or idk, I probably wouldn't do this but it would become possible if anyone else wanted to for some reason.

**Comment by Ross-Patterson** [comment]
I will put this enhancement in the backlog.

**Comment by Ross-Patterson** [comment]
Hi There,
I have included this feature in v3.0.0.0 which I have made available for early access here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/107

Thanks!

**Comment by AmyGilhespy** [comment]
Thank you!! <3
