### ISSUE TITLE
Clicking in taskbar down right button to hide windows is hiding portal

### ISSUE THREAD

**Issue by dliedke** [Ross-Patterson/Portals-Desktop-Organization#87]
**Describe the bug**
Clicking in taskbar down right button to hide windows is hiding portal windows

**To Reproduce**
Clicking in taskbar down right to hide windows is hiding portal windows windows

**Expected behavior**
portal windows should still be in the desktop

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2

**Comment by Ross-Patterson** [comment]
Try v3.0.0, reopen if needed.

**Comment by dliedke** [comment]
Thanks a lot! Retested here and worked fine!!
