### ISSUE TITLE
Feature Request: Dragging items from portals to desktop accidentally.

### ISSUE THREAD

**Issue by darxian** [Ross-Patterson/Portals-Desktop-Organization#88]
**Is your feature request related to a problem? Please describe.**
It's annoying, that sometimes i happen to click and end up dragging the executable or shortcut and make a duplicate on desktop

**Describe the solution you'd like**
Somehow add a setting to not allow the items to be dragged, only clicked to launch

**Describe alternatives you've considered**
Currently i may have to disable desktop icons and just use portals for everything i have on desktop.

**Additional context**

**Comment by Ross-Patterson** [comment]
I can add an option to turn off drag and drop, that's fairly simply

**Comment by darxian** [comment]
That would be perfect and probably solve this issue.

**Comment by darxian** [comment]
Not to rush you or anything, just wanting to know some sort of ETA for update including this feature. Thanks!

**Comment by Ross-Patterson** [comment]
Should be in the next release coming soon

**Comment by Ross-Patterson** [comment]
Hi There,
I have included this feature in v3.0.0.0 which I have made available for early access here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/107

Thanks!

**Comment by darxian** [comment]
I have another feature suggestion. I am a bit crazy with detail sometimes. I want my portals to be exact side of the amount of icons available, so when i click on it, the blue box around the item is perfect with the size of the portal. Is it possible to implement it or gonna be too tough? I have multiple windows, where sometimes one of my portals needs to be made bigger when i need to add extra items, then i need to manually resize like a crazy person, trying to find the perfect size pixel perfect.

**Comment by Ross-Patterson** [comment]
You want the portal to automatically resize to fit its contents?

**Comment by darxian** [comment]
I mean that can also be there as a setting, sounds useful for something i might want to use. But what i mean is that when i have a certain amount of icons to be presented in a portal, there is a button to automatically resize the portal to match the icons selection (the blue box around it). Then i can just add more items into a portal when needed and don't need to manually find the sweetspot.

![Untitled](https://user-images.githubusercontent.com/104892211/233807809-675caaa4-0877-4557-a9b3-147d48aabdc4.png)

I mean i am too much of a perfectionist, so i need to always scratch my itch with new layouts. It would make it easier to make the size perfect.

In the end just a suggestion. I can handle doing it manually as well.
