### ISSUE TITLE
Feature Request: Windows Explorer Menu as default behaviour for right clicking

### ISSUE THREAD

**Issue by NyaomiDEV** [Ross-Patterson/Portals-Desktop-Organization#89]
**Is your feature request related to a problem? Please describe.**
I don't think this particularly relates to a problem, since people can get around it quickly, but I still want to point it out as a feature request.

**Describe the solution you'd like**
There should be an option in the portal behaviour section that allows for files and folders inside portals to be interacted with using the default Explorer context menu directly, upon right clicking; this is to help people out with muscle memory and overall consistency.

**Describe alternatives you've considered**
Using other software, but come on? I've been trying Portals and this is me being nitpicky - the software is awesome, otherwise.

**Additional context**
Nothing, sadly

**Comment by MRGOOSE81** [comment]
i wish they would add an option to disable portal's context menu and just use window's instead

**Comment by Ross-Patterson** [comment]
This is now available in the latest beta, and coming to prod soon. You can switch to Beta channel in the app settings.

**Comment by Ross-Patterson** [comment]
This is now available in the latest update.
