### ISSUE TITLE
Feature Request: Add Keyboard shortcut to "Edit order" option when Custom sorting is enabled

### ISSUE THREAD

**Issue by Max1234-Ita** [Ross-Patterson/Portals-Desktop-Organization#90]
I like to customize the layout of the icons in the Portals I create, so I often enable the Custom sorting (click on Portal Menu -> Sort by... -> Custom -> Turn on)

When i need to move some icon, however, I have to go to the same menu (click on Portal Menu -> Sort by... -> Custom) and then select the Edit order option.

This is quite uncomfortable, since it requires 4 clicks to reach the option while the feature should be very immediate to use (my personal opinion).

I wonder if it could be possible to have some kind of shortcut (i.e keeping Shift or CTRL key pressed while dragging the icon) to enable the function without having to go through the menu tree.

**Describe the solution you'd like**
A way to immediately enable the Edit order function, i.e. holding CTRL while dragging the icon, would be welcome.

**Describe alternatives you've considered**
Maybe an additional MenuItem in the Portal context menu (i.e. "_Edit icon order_") would be useful as well. That option, if selected, could automatically trigger the _Custom sorting_.

**Additional context**
N/A

**Comment by Ross-Patterson** [comment]
This is now available in the beta channel v3.0.1.0, switch to it in the settings:
![image](https://user-images.githubusercontent.com/66630787/234682669-8ce63df9-325e-4ed9-8c67-b08c545183b6.png)

CTRL+E will turn on edit mode if the portal is active and custom sorting is enabled for that portal

**Comment by Ross-Patterson** [comment]
This is now released to prod channel, so closing this issue

**Comment by Max1234-Ita** [comment]
Thank you very much!
