### ISSUE TITLE
Search feature in portals.

### ISSUE THREAD

**Issue by Scadooshy** [Ross-Patterson/Portals-Desktop-Organization#91]
A feature to allow a search bar within portals so that you could more quickly find items you are looking for within large directories.

**Comment by Ross-Patterson** [comment]
This is coming in the next release which should be in the next few weeks.

**Comment by Ross-Patterson** [comment]
Hi There,
I have included this feature in v3.0.0.0 which I have made available for early access here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/107

Thanks!
