### ISSUE TITLE
Booting PC-Position/Height/Width Changes the Values

### ISSUE THREAD

**Issue by DarkAoRaidenX** [Ross-Patterson/Portals-Desktop-Organization#94]
**Describe the bug**
When i restart/turn on the computer, the position and the other values of the Portals change. Especially one by a big margin. 

I try to set everything close to even numbers like Y Position to 10 but when i go to settings it says 11 and every number is just some random values. Then this one Portal always goes to like Y 42.

**To Reproduce**
1. Restart/Turn back on PC.

**Expected behavior**
To save the values i entered.

**Screenshots**
Attached them if not seen let me know.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64bit
 - Portals Version: 2.1.0.6

**Additional context**
![02 11 2023 15 03 38](https://user-images.githubusercontent.com/101914106/218282026-2b8c5aa6-338a-4dd4-9c56-7a2cf0a7ca95.png)
![02 11 2023 15 23 30](https://user-images.githubusercontent.com/101914106/218282030-c2376ef7-e542-4bd8-b5c9-7468c7da0aa6.png)

**Comment by DarkAoRaidenX** [comment]
![02 15 2023 05 50 34](https://user-images.githubusercontent.com/101914106/219020351-1828e488-4fc8-4dc5-b81b-4e5217064a08.png)

Restarted PC again and it happened again.

**Comment by Ross-Patterson** [comment]
This should be fixed in the next release coming soon!

**Comment by Ross-Patterson** [comment]
Hi There,
This should be fixed in v3.0.0.0 which I have made available for early access here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/107

Thanks!

**Comment by DarkAoRaidenX** [comment]
> Hi There, This should be fixed in v3.0.0.0 which I have made available for early access here: #107
> 
> Thanks!

Yes it fixed it thanks!
