### ISSUE TITLE
Resize, when "auto expand/minimize on hover" is enabled. 

### ISSUE THREAD

**Issue by NimeRAD** [Ross-Patterson/Portals-Desktop-Organization#96]
**Describe the bug**
Wrong minimize.
I can't resize fence by mouse, when "auto expand/minimize on hover" is enabled. 

**To Reproduce**
1. Go to 'Settings'
2. Check "Auto Expand/Minimize Portals On Hover"
3. Move cursor to fence for expand.
4. Move cursor to border.
5. When cursor change, fence will minimize

**Expected behavior**
There must be an easy way to change size after adding new shortcat, when "auto" is enabled.
Maybe a button to hold on fence expanded. 

**Screenshots**
![portals](https://user-images.githubusercontent.com/125450839/219005652-ce0d65f7-0056-4968-b89e-6b8108afe48f.gif)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 2.1.0.6

**Additional context**

**Comment by Ross-Patterson** [comment]
I don't think there is any way around this unfortunately - you will probably just have to turn it off temporarily until you get everything sized correctly.
