### ISSUE TITLE
Feature Request: List/Details  view

### ISSUE THREAD

**Issue by NimeRAD** [Ross-Patterson/Portals-Desktop-Organization#97]
**Please describe.**
When the folder contains a lot of different elements, it's hard to look for something. 

**Describe the solution you'd like**
A different type of portal. And it would be great, if we can select fields/properties showing it the portal.

**Describe alternatives you've considered**
View as a list.

**Comment by Ross-Patterson** [comment]
Coming soon...
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/e43a2a20-d9c2-4d34-b89a-701f7ef65960)

**Comment by Ross-Patterson** [comment]
This has been deployed in the latest beta release: 3.1.0.0, switch to the beta channel in the settings to get the update.

**Comment by Ross-Patterson** [comment]
Now released

**Comment by Liel4494** [comment]
how change to "Details View" ?

**Comment by Ross-Patterson** [comment]
![image](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/66630787/890ebb3e-732a-4a62-82fc-279b01d802a3)
