### ISSUE TITLE
Ability to adjust/customize spacing/grid size of icons within portals

### ISSUE THREAD

**Issue by just4747** [Ross-Patterson/Portals-Desktop-Organization#98]
Just wondering if it is possible to get a setting added that lets you customize the spacing/grid size of the icons within each portal grid. Previously I used an application that allowed you to better center or adjust the icons inside a grid so that they look more even/centered if desired and it looked a little less cramped inside. I wasn't able to accomplish this by adjusting icon and font size from what I can tell.

Thanks!

**Comment by Ross-Patterson** [comment]
Yes this will be coming in the next release which should be within the next few weeks.

**Comment by Ross-Patterson** [comment]
Hi There,
I have included this feature in v3.0.0.0 which I have made available for early access here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/107

Thanks!
