### ISSUE TITLE
Ability to force shortcut/icon titles to show full titles even if it requires multiple lines, similar to Nova Launcher for Android devices

### ISSUE THREAD

**Issue by just4747** [Ross-Patterson/Portals-Desktop-Organization#99]
Wondering if it is possible to allow the option to force all shortcut/icon titles in a Portal to show full the full shortcut text/titles, even if it requires multiple lines to show it, similar to Nova Launcher for Android devices. This would be similar to the click to show full text option but just a persistent/always on version of that that still would look neat/not weird (if possible).

Thanks!

**Comment by Ross-Patterson** [comment]
Yes I can add that - i'll add it to the backlog

**Comment by Ross-Patterson** [comment]
Hi There,
I have included this feature in v3.0.0.0 which I have made available for early access here:
https://github.com/Ross-Patterson/Portals-Desktop-Organization/discussions/107

Thanks!
